//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageCellView.h"

#import "IAppDataExt.h"
#import "IContactMgrExt.h"
#import "IQQContactMgrExt.h"
#import "IStrangerContactMgrExt.h"
#import "WCActionSheet.h"

@class AppMessageBlockButton, CTRichTextView, CommonMessageViewModel, MMCPLabel, MMHeadImageView, NSString, UIActivityIndicatorView, UIButton, UIView, YYAsyncImageView;

@interface CommonMessageCellView : BaseMessageCellView <IAppDataExt, IContactMgrExt, IStrangerContactMgrExt, IQQContactMgrExt, WCActionSheetDelegate>
{
    CGRect m_bubbleBorderFrame;
    MMHeadImageView *m_headImageView;
    MMCPLabel *m_chatRoomNameLabel;
    YYAsyncImageView *m_bgImageView;
    YYAsyncImageView *m_maskImageView;
    UIActivityIndicatorView *m_sendingView;
    UIButton *m_sendFailButton; /**< 发送失败按钮 */
    UIButton *m_cancelButton;
    UIView *m_sourceViewInside;
    UIView *m_sourceViewBottom;
    AppMessageBlockButton *m_appMessageBlockButton;
    CTRichTextView *m_crashWarningLabel;
}


#pragma mark - IQQContactMgrExt
- (void)onModifyQQContact:(CQQContact *)arg1;

#pragma mark - WCActionSheet
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;

#pragma mark - IStrangerContactMgrExt
- (void)onStrangerContactUpdated:(NSString *)arg1 Contact:(CContact *)aContact;

#pragma mark - IAppDataExt
- (void)OnAppInfoChanged:(NSString *)arg1;
- (void)OnAppWatermarkChanged:(NSString *)arg1;

#pragma mark - IContactMgrExt
- (void)onModifyContact:(CContact *)contact;

- (_Bool)handleMagicTapAction:(id)arg1;
- (_Bool)accessibilityPerformMagicTap;
- (void)addMagicTapActions:(id)arg1;
- (void)triggerLongPressFor3DTouchAtLocation:(struct CGPoint)arg1 inCoordinateView:(id)arg2;
- (void)onAppButtonClicked:(id)arg1;
- (void)onCancelButtonClicked:(id)arg1;
- (void)onSendFailButtonClicked:(id)arg1;
- (void)onHeadImageLongPressed:(id)arg1;
- (void)onHeadImageClicked:(id)arg1;
- (void)layoutForCrashWarning;
- (void)setHighlighted:(_Bool)arg1;
- (void)initAppMessageBlockButton;
- (void)initSourceViewInside;
- (void)initSourceViewBottom;
- (void)addCancelButton;
- (void)addSendFailButton;
- (void)addSendingView;
- (void)initMaskImageView;
- (void)initBgImageView;
- (void)initChatRoomNameLabel;
- (void)initHeadImageView;
- (void)initCrashWarningLabel;
- (void)setFrameForBgImageView:(struct CGRect)arg1;
- (struct CGRect)showRectForMenuController;
- (void)showUIStatus;
- (void)hideUIStatus;
- (void)updateStatus;
- (void)updateNodeStatus;
- (void)layoutContentView;
- (void)layoutInternal;
- (void)dealloc;
- (void)prepareForReuse;
- (void)setViewModel:(id)arg1;





@property(readonly, nonatomic) CommonMessageViewModel *viewModel; // @dynamic viewModel;

@end

