//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ContactsDataLogicDelegate.h"
#import "MMSearchBarDelegate.h"
#import "WCActionSheet.h"
#import "ContactSelectViewDelegate.h"

@class ContactsDataLogic, MMSearchBar, MMTableView, NSDictionary, NSMutableDictionary, NSString;

@interface ContactSelectView : UIView <UISearchDisplayDelegate, UITableViewDelegate, UITableViewDataSource, MMSearchBarDelegate, WCActionSheetDelegate, ContactsDataLogicDelegate>
{
    id <ContactSelectViewDelegate> m_delegate;
    MMTableView *m_tableView;
    NSDictionary *m_dicExistContact;
    BOOL m_bShowHistoryGroup;
    BOOL m_bShowRadarCreateRoom;
    BOOL m_bMultiSelect;
    NSMutableDictionary *m_dicMultiSelect;
    ContactsDataLogic *m_contactsDataLogic;
    NSUInteger m_uiGroupScene;
    UIView *_tableFooterView;
    NSString *nsCurrentSearchText;
    MMSearchBar *m_mmSearchBar;
}

@property(nonatomic) BOOL m_bMultiSelect; // @synthesize m_bMultiSelect;
@property(strong, nonatomic) NSMutableDictionary *m_dicMultiSelect; // @synthesize m_dicMultiSelect;
@property(nonatomic) NSUInteger m_uiGroupScene; // @synthesize m_uiGroupScene;
@property(nonatomic) BOOL m_bShowRadarCreateRoom; // @synthesize m_bShowRadarCreateRoom;
@property(nonatomic) BOOL m_bShowHistoryGroup; // @synthesize m_bShowHistoryGroup;
@property(strong, nonatomic) NSDictionary *m_dicExistContact; // @synthesize m_dicExistContact;
@property(nonatomic, weak) id <ContactSelectViewDelegate> m_delegate; // @synthesize m_delegate;



- (NSUInteger)getTotalSelectCount;
- (void)handleSelectRadarCreateRoom;
- (void)handleSelectHistoryGroup;
- (void)makeHistoryGroupCell:(id)arg1;
- (void)makeMultiTalkSessionCell:(id)arg1;
- (void)makeRadarCreateRoomCell:(id)arg1;
- (void)makeCell:(id)arg1 tableCell:(id)arg2 section:(NSUInteger)section row:(NSUInteger)row;
- (void)makeGroupCell:(id)arg1 head:(id)arg2 title:(NSString *)title;
- (void)makeCell:(id)arg1 contact:(CContact *)contact showMatchTip:(BOOL)isShow;
- (void)makeCell:(id)arg1 contact:(CContact *)contact;

- (void)searchTextFieldDidBeginEditing;

- (void)resetTableViewOffset:(id)arg1;
- (void)initView;
- (void)initTableView;
- (void)initSearchBar;
- (void)reloadTableView;
- (instancetype)initWithFrame:(CGRect)frame delegate:(id <ContactSelectViewDelegate>) delegate;
- (void)initData:(NSUInteger)arg1;
- (void)setExtraCellLineHidden:(id)arg1;
- (BOOL)updateMultiSelect:(id)arg1;
- (void)addSelect:(id)arg1;
- (id)getCellTextView:(id)arg1;
- (id)getCellImage:(id)arg1;
- (BOOL)isSelected:(id)arg1;
- (BOOL)isExisted:(id)arg1;
- (void)multiSelectWithSearchResult:(id)arg1;
- (id)getMatchTipForUsername:(id)arg1;
- (void)removeSelect:(id)arg1;

@end

