//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ChatViewModelDelegate.h"

@class CBaseContact, CMessageWrap;

@interface BaseChatViewModel : NSObject
{
    double m_layoutWidth;
    double m_cachedHeight;
    id m_cellView;
}

@property(nonatomic, weak) id <ChatViewModelDelegate> delegate;
@property(nonatomic) double createTime;
@property(nonatomic) unsigned long long splitPosition;
@property(nonatomic) int modelType;
@property(retain, nonatomic) CBaseContact *chatContact;

- (_Bool)isDisableEditMode;
- (_Bool)isTailPart;
- (_Bool)isHeadPart;
- (id)cellDataForRow:(unsigned long long)arg1;
- (long long)numberOfRowsInSection;
- (void)updateLayouts;
- (void)resetLayoutCache;
- (struct CGSize)measure:(struct CGSize)arg1;
- (double)rowHeight;
- (_Bool)shouldLayoutIfNeeded;
- (double)sectionHeight;
- (id)cellIdentifier;
- (id)cellViewClassName;
- (void)updateChatContact:(id)arg1;
- (id)initWithChatContact:(id)arg1;
@property(readonly, nonatomic) CMessageWrap *messageWrap;
@property(nonatomic) __weak id cellView;

@end

