//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@protocol AutoplayController;

@interface AutoplayController : MMObject
{
    NSMutableArray *m_arrMesLocalIDs;
    id <AutoplayController> m_delegate;
    BOOL m_bCanPlay;
    BOOL m_bCanStart;
}

@property(nonatomic, weak) id <AutoplayController> m_delegate; // @synthesize m_delegate;

- (void)dealloc;
- (void)Reset;
- (void)systemActived:(id)arg1;
- (void)systemResigned:(id)arg1;
- (void)onStopPlayingVideo;
- (void)onStopRecordingVideo;
- (void)onBeginRecordVideo;
- (void)onBeginPlayVideo;
- (void)onStopRecording;
- (void)onStartPlaying:(id)arg1;
- (void)onEndPlaying:(unsigned int)arg1 isForceStopped:(BOOL)arg2;
- (void)onBeginStartRecording;
- (void)onMessageDownloaded:(unsigned int)arg1;
- (void)onMessagePlayed:(unsigned int)arg1;
- (void)AddMessageLocalID:(unsigned int)arg1;
- (void)PlayList;
- (BOOL)isPlayOK;
- (id)init;
- (void)UnRegister;
- (void)Register;

@end

@protocol AutoplayController <NSObject>
- (BOOL)canAutoplayWhenMessageDownloaded;

@optional
- (void)PlayNodeAtId:(unsigned int)arg1;
- (NSArray *)GetMessagesNodeArray;
@end
