//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUINavigationController.h"
#import "MMImagePickerControlCenter.h"
#import "MMImagePickerControllerDelegate.h"

@class EditImageLogicController, MMAlbumPickerController, MMImagePickerControllerPreviewReportObject, NSArray, NSString;

@interface MMImagePickerController : MMUINavigationController <MMImagePickerControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, MMImagePickerControlCenter>
{
    __weak id <MMImagePickerControllerDelegate> m_delegate;
    MMImagePickerControllerPreviewReportObject *m_previewReportObject;
}

@property(nonatomic) _Bool isEditMode;
@property(retain, nonatomic) EditImageLogicController *editImageLogicController;
@property(retain, nonatomic) MMImagePickerControllerPreviewReportObject *m_previewReportObject; // @synthesize m_previewReportObject;
@property(nonatomic) _Bool isOriginalImage;
@property(retain, nonatomic) NSArray *selectedImageAssets;
@property(retain, nonatomic) NSArray *selectedImageURLs;
@property(retain, nonatomic) NSString *currentAlbum;
@property(retain, nonatomic) NSString *finishWording;
@property(nonatomic) int compressType;
@property(nonatomic) int maxImageCount;
@property(nonatomic) _Bool canSendGif;
@property(nonatomic) _Bool showPreviewView;
@property(nonatomic) _Bool needThumbImage;
@property(nonatomic) _Bool canSendMultiImage;
@property(nonatomic) _Bool isNotShowVideoSizeAlertView;
@property(nonatomic) _Bool isOnlyShowVideoMessage;
@property(nonatomic) _Bool canSendVideoMessage;
@property(nonatomic) _Bool canSendOriginImage;
@property(nonatomic, weak) MMAlbumPickerController *photoPicker;
@property(nonatomic) __weak id <MMImagePickerControllerDelegate> m_delegate; // @synthesize m_delegate;

- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)MMImagePickerControllerDidCancel:(id)arg1;
- (void)MMImagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (int)getPickerScene;
- (void)reportPreviewCount;
- (void)increasePreviewCount;
- (void)selectedGif:(id)arg1;
- (void)selectedSight:(id)arg1;
- (void)selectedVideo:(id)arg1;
- (void)selectedAssets:(id)arg1;
- (void)cancelImagePicker;
- (void)removeImageDatas;
- (id)init;
- (id)initForJustReturnMMAsset:(_Bool)arg1 withAdjustRevertIndex:(unsigned long long)arg2 withDirectToFirstAlbum:(_Bool)arg3 withOnlyShowVideoMessage:(_Bool)arg4 withNotShowVideoSizeAlertView:(_Bool)arg5;


@end

