//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@interface MMSearchBarDisplayController : MMUIViewController <UISearchDisplayDelegate, UISearchBarDelegate>
{
    UISearchBar *m_searchBar;
    UISearchDisplayController *m_searchDisplayController;
    BOOL m_isActive;
}

@property(strong, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController=m_searchDisplayController;
@property(strong, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=m_searchBar;

- (BOOL)isSeachActive;


- (BOOL)statusBarFontOriginalWhite;

@end

