//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ICertInfoMgrExt.h"
#import "LocationRetrieveDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "SeePeopleNearByUIDelegate.h"

@class CLLocation, LbsContactInfoList, LocationRetriever, NSRecursiveLock, NSString;

@interface SeePeopleNearByLogicController : MMObject <ICertInfoMgrExt, LocationRetrieveDelegate, PBMessageObserverDelegate>
{
    unsigned int m_uiEventID;
    unsigned int m_lbsEventID;
    unsigned int m_uiTryCount;
    NSRecursiveLock *m_oLock;
    LbsContactInfoList *m_lbsContactList;
    LocationRetriever *m_locationRetrieve;
    id <SeePeopleNearByUIDelegate> m_delegate;
    unsigned int m_uiCurOpCode;
    CLLocation *m_location;
}

@property(strong, nonatomic) CLLocation *m_location; // @synthesize m_location;
@property(strong, nonatomic) LocationRetriever *m_locationRetrieve; // @synthesize m_locationRetrieve;
@property(strong, nonatomic) LbsContactInfoList *m_lbsContactList; // @synthesize m_lbsContactList;

- (void)onSelectedWithLbsPoiItem:(id)arg1;
- (void)onSelectedWithLbsContactInfo:(id)arg1;
- (BOOL)CreateJoinLBSRoomEvent:(id)arg1;
- (void)tryJoinChatRoom;
- (BOOL)CreateLBSFindEvent:(id)arg1;
- (BOOL)CreateLBSPoiListEvent:(id)arg1;
- (BOOL)CreateClearLBSDataEvent;
- (BOOL)clearMyLbsData;
- (void)cancelUpdateLbsContactInfo;
- (void)updateLbsContactInfo;
- (instancetype)initWithDelegate:(id<SeePeopleNearByUIDelegate>)delegate;

@end

