//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class GetGameIndex2Response_TypeNavModule;

@interface GameCenterNavCategoryView : MMUIView
{
    GetGameIndex2Response_TypeNavModule *_navCategory;
    id <GameCenterNavCategoryViewDelegate> _delegate;
}

@property(nonatomic) __weak id <GameCenterNavCategoryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onNavItemClicked:(id)arg1;
- (id)genLabelWithBoldFontSize:(double)arg1 text:(id)arg2 textColor:(id)arg3 x:(double)arg4 y:(double)arg5 maxWidth:(double)arg6 superView:(id)arg7;
- (id)genLabelWithFontSize:(double)arg1 text:(id)arg2 textColor:(id)arg3 x:(double)arg4 y:(double)arg5 maxWidth:(double)arg6 superView:(id)arg7;
- (id)getNavItemView:(id)arg1 ItemIndex:(int)arg2;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1 navCategoryData:(id)arg2;

@end

