//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUILabel, MMWebImageView, NSString, UIButton, UIImageView, UIScrollView, WCPayControlData;

@interface WCPayNewPaidOrderDetailView : MMUIView
{
    id <WCPayNewPaidOrderDetailViewDelegate> _delegate;
    WCPayControlData *_data;
    NSString *_selectedBrandUsername;
    NSString *_outerBtnTitle;
    UIScrollView *_contentView;
    UIButton *_activityBtn;
    MMWebImageView *_activityLogoImgView;
    MMUILabel *_sloganLabel;
    MMUILabel *_titleLabel;
    UIButton *_doneBtn;
    UIImageView *_selectedImageView;
}

@property(retain, nonatomic) UIImageView *selectedImageView; // @synthesize selectedImageView=_selectedImageView;
@property(retain, nonatomic) UIButton *doneBtn; // @synthesize doneBtn=_doneBtn;
@property(retain, nonatomic) MMUILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMUILabel *sloganLabel; // @synthesize sloganLabel=_sloganLabel;
@property(retain, nonatomic) MMWebImageView *activityLogoImgView; // @synthesize activityLogoImgView=_activityLogoImgView;
@property(retain, nonatomic) UIButton *activityBtn; // @synthesize activityBtn=_activityBtn;
@property(retain, nonatomic) UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSString *outerBtnTitle; // @synthesize outerBtnTitle=_outerBtnTitle;
@property(retain, nonatomic) NSString *selectedBrandUsername; // @synthesize selectedBrandUsername=_selectedBrandUsername;
@property(retain, nonatomic) WCPayControlData *data; // @synthesize data=_data;
@property(nonatomic) __weak id <WCPayNewPaidOrderDetailViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getOrderDetail;
- (void)setDoneButtonTitle:(id)arg1;
- (void)refreshH5ActivityContentWithActivityUrl:(id)arg1 logoUrl:(id)arg2 mainTitle:(id)arg3 subTitle:(id)arg4 btnText:(id)arg5;
- (void)refreshNativeActivityBtnTitle:(id)arg1;
- (void)activityBtnClick;
- (void)doneBtnClick;
- (void)tinyAppBtnClick;
- (void)selectBtnClick:(id)arg1;
- (id)getActivityInfoView;
- (id)getTinyAppInfoView;
- (id)getBrandSubscribeView;
- (id)getDiscountView;
- (void)setupBottomContentViewWithContentBottom:(double)arg1;
- (double)setupCenterContentViewWithContentBottom:(double)arg1;
- (double)setupHeaderContentView;
- (void)setupContentView;
- (id)initNewOrderDetailViewWithFrame:(struct CGRect)arg1 delegate:(id)arg2 controlData:(id)arg3;

@end

