//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MMUIView;

@interface MMTableViewCell : UITableViewCell
{
    MMUIView *m_subContentView;
}

+ (id)getCellAttributeDetailTextHightlightedColor;
+ (id)getCellAttributeTextHightlightedColor;
+ (id)getCellTextHightlightedColor;
@property(retain, nonatomic) MMUIView *m_subContentView; // @synthesize m_subContentView;

- (void)addBackgroundView;
- (void)addCustomArrow;

@end

