#!/bin/sh

#  ccache-clang.sh
#  KKCL
#
#  Created by sunshinek31 on 2017/8/10.
#  Copyright © 2017年 sunshinek31. All rights reserved.

if type -p ccache >/dev/null 2>&1; then
export CCACHE_MAXSIZE=10G
export CCACHE_CPP2=true
export CCACHE_HARDLINK=true
export CCACHE_SLOPPINESS=file_macro,time_macros,include_file_mtime,include_file_ctime,file_stat_matches

# 指定日志文件路径到桌面，等下排查集成问题有用，集成成功后删除，否则很占磁盘空间
export CCACHE_LOGFILE='~/Desktop/CCache.log'
exec ccache /usr/bin/clang "$@"
else
exec clang "$@"
fi
