//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "textViewDelegate.h"
#import "MMGrowTextViewDelegate.h"

@class MMTextView;

/**
 聊天输入textView
 */
@interface MMGrowTextView : MMUIView <UITextFieldDelegate, UITextViewDelegate, UIScrollViewDelegate, textViewDelegate>
{
    id <MMGrowTextViewDelegate> m_delegate;
    UIImageView *_backgroundView;
    CGSize textViewMaxSize;
    CGFloat _textViewOriginHeight;
    UIEdgeInsets backgroundImageInsets;
    MMTextView *_textView;
    BOOL enabled;
    NSRange _selectedRange;
    BOOL _isKeyboardOwner;
    BOOL _isKeyboardHiding;
    struct timeval _last3rdKeyboardStartEventTime;
    NSString *text;
    NSString *placeHolder;
    NSInteger maxLength;
    NSInteger maxFontSize;
}

@property(nonatomic) CGRect keyboardFrameInScreen;
@property(nonatomic) NSInteger maxFontSize; // @synthesize maxFontSize;
@property(nonatomic) NSInteger maxLength; // @synthesize maxLength;
@property(nonatomic) NSInteger iKeyboardAnimationCurve;
@property(nonatomic) CGFloat fKeyboardAnimationDuration;
@property(retain, nonatomic) NSString *extensionKey;
@property(nonatomic) BOOL enabled; // @synthesize enabled;
@property(nonatomic, weak) id <MMGrowTextViewDelegate> m_delegate; // @synthesize m_delegate;
@property(nonatomic) UIEdgeInsets backgroundImageInsets; // @synthesize backgroundImageInsets;
@property(nonatomic) CGSize textViewMaxSize; // @synthesize textViewMaxSize;
@property(nonatomic) CGFloat textViewMinHeight;
@property(nonatomic, weak) NSString *placeHolder; // @synthesize placeHolder;
@property(nonatomic, weak) NSString *text; // @synthesize text;
@property(nonatomic, weak) UIResponder *menuResponder;

- (instancetype)initWithOriginHeight:(CGFloat)originHeight;
- (BOOL)canChangeTextValue;
- (void)deleteBackward;
- (void)insertString:(id)arg1;
- (CGFloat)getTextViewHeight;
- (void)setPlaceHolderColor:(UIColor *)plactHolderColor;
- (void)setTextColor:(UIColor *)textColor;
- (void)setTextFont:(UIFont *)textFont;
- (void)resetTextWidth;
- (void)setTextWidth:(CGFloat)width;
- (void)keyboardDidChangeFrame:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;

/**
 发送文本消息
 */
- (void)sendTextViewMessage;
- (NSRange)getTextSelectRange;
- (void)saveTextSelectRange;
- (id)textArea;
- (void)adjustRect;
- (void)adjustSize;
- (void)resetScrollPositionForIOS7;
- (CGFloat)measureHeight;
- (void)MenuControllerWillHide:(id)arg1;
- (void)UITextViewTextDidBeginEditingNotification:(NSNotification *)notification;
- (void)UITextViewTextDidChangeNotification:(NSNotification *)notification;
- (void)setBackgroundImage:(UIImage *)backgroundImage;
- (BOOL)isExtenalKeyboardAttatched;
- (void)postTextChangeNotification;
- (void)setTextViewContentInsets;
- (void)setAdjustToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation;



@end

