//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ABTestItem, MMTimer;

#import "MMQuickSendEmoticonViewDelegate.h"

@interface MMQuickSendEmoticonView : UIButton <UICollectionViewDelegate, UICollectionViewDataSource>
{
    UICollectionView *m_collectionView;
    UICollectionViewFlowLayout *m_collectionLayout;
    NSArray *m_wrapList;
    NSString *m_desc;
    MMTimer *m_timer;
    NSTimeInterval m_timeInterval;
    int m_viewCount;
    NSTimeInterval m_startTime;
}

@property(retain, nonatomic) ABTestItem *abTestItem;
@property(nonatomic, weak) id <MMQuickSendEmoticonViewDelegate> delegate;
@property(readonly, nonatomic) NSString *curShowingDesc;

- (void)hideQuickSendEmoticonView;
- (void)checkNeedHide;
- (void)showQuickSendEmoticonView;
- (void)configCollectionView;
- (void)hide;
- (NSUInteger)emoticonWrapCount;
- (void)setEmoticonWrapList:(id)arg1 desc:(id)arg2;


@end

