//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUITextView.h"
#import "MMInputAccessoryViewDelegate.h"
#import "textViewDelegate.h"

@class MMInputAccessoryView, NSString, UIColor, UIResponder;

@interface MMTextView : MMUITextView <MMInputAccessoryViewDelegate>
{
    NSString *placeholder;
    BOOL _shouldDrawPlaceholder;
    id <textViewDelegate> m_delegate;
    BOOL _externalKeyboardAttatched;
    MMInputAccessoryView *_accessoryView;
}

@property(nonatomic) CGFloat textViewOriginHeight;
@property(strong, nonatomic) UIColor *placeHolderColor;
@property(nonatomic, weak) UIResponder *overrideNextResponder;
@property(nonatomic) CGFloat fForceY; ;
@property(nonatomic, weak) id <textViewDelegate> m_delegate; // @synthesize m_delegate;
@property(strong, nonatomic) NSString *placeholder; // @synthesize placeholder;



- (BOOL)isExtenalKeyboardAttatched;
- (void)keyboardWillShow:(id)arg1;
- (void)_textChanged:(id)arg1;
- (void)_updateShouldDrawPlaceholder;
- (void)setContentOffset:(CGPoint)offset;

@end

