//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"
#import "MMImagePickerManagerDelegate.h"
#import "ImageBrowseDelegate.h"
#import "MMImagePickerControllerDelegate.h"

@class MMImagePickerManagerOptionObj;

/**
 照片选择管理器
 */
@interface MMImagePickerManager : MMObject <MMImagePickerControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, ImageBrowseDelegate>

@property(strong, nonatomic) NSMutableArray *tempImagePool;
@property(strong, nonatomic) MMImagePickerManagerOptionObj *optionObj;
@property(nonatomic, weak) id <MMImagePickerManagerDelegate> m_delegate;

+ (_Bool)isCaptureByImagePicker:(id)arg1;
+ (id)getImagePickerControllerWithOptionObj:(id)arg1;
+ (id)getImagePickerFromCameraWithOptionObj:(id)arg1 withManager:(id)arg2;
+ (id)getImagePickerFromPhotoLibraryWithOptionObj:(id)arg1 withManager:(id)arg2;
+ (void)showWithOptionObj:(id)arg1 inViewController:(id)arg2;
+ (_Bool)isSupportViewController:(id)arg1;


- (void)OnShowDidFinished;
- (void)OnShowWillFinished;
- (id)init;
- (void)didSelectImage:(id)arg1 Data:(id)arg2 Finish:(_Bool)arg3 fromImagePicker:(id)arg4;
- (void)didSelectImage:(id)arg1 Data:(id)arg2 fromImagePicker:(id)arg3;
- (void)didSelectImage:(id)arg1 fromImagePicker:(id)arg2;
- (void)MMVideoPickerController:(id)arg1 didFinishPickingSightWithInfo:(id)arg2;
- (void)MMVideoPickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)MMImagePickerControllerDidCancel:(id)arg1;
- (void)MMImagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)statusBarShowOniOS10;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerController:(id)arg1 didFinishPickingImage:(id)arg2 editingInfo:(id)arg3;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(_Bool)arg3;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;

@end

