//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

@class NSRecursiveLock, NSString;

@interface SendMessageMgr : MMService <MMService>
{
    NSRecursiveLock *m_oLock;
    NSUInteger m_uiQueueCount;
    BOOL m_isMigrated;
}

- (id)getPBPath;
- (NSUInteger)GetCountOfSendMessage;
- (id)getSendMessages;
- (void)DeleteSendMessageByChatName:(id)arg1 localId:(unsigned int)arg2;
- (void)AddMsgToSendTable:(id)arg1 MsgWrap:(id)msgWrap;
- (void)saveMessages:(id)arg1;
- (id)loadMessages;
- (void)migrateSendMessage:(id)arg1;

@end

