//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YoutuBeautyManager : NSObject
{
    long long _state;
}

+ (id)sharedManager;
@property long long state; // @synthesize state=_state;
- (void)setMultiThreadEnabled:(_Bool)arg1;
- (void)unlockMemory;
- (void)lockMemory;
- (void)freeMemory;
- (void)initMemory;

@end

