//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface UiUtil : NSObject
{
}

+ (CGFloat)screenScale;
+ (void)showCameraAlertForSplitViewIfNeed:(id)arg1 currentWidth:(CGFloat)width;
+ (BOOL)isiPadSplitViewModeNow;
+ (BOOL)isiPadSplitViewMinimizeModeNow;
+ (void)setStatusBarStyle:(UIStatusBarStyle)statusBarStyle;
+ (void)refreshStatusBarStyle;
+ (void)setStatusBarFontBlack;
+ (void)setStatusBarFontWhite;
+ (CGFloat)tabBarHeight;
+ (CGRect)screenRectRelativeToView:(id)arg1;
+ (void)fixNavigationController:(id)arg1;
+ (CGFloat)groupedStyleCellSubViewRight;
+ (CGFloat)groupedStyleCellWidth;
+ (CGFloat)topBarNormalOffset;
+ (BOOL)isTopBarInNormalState;
+ (CGFloat)keyboardHeightByNotification:(NSNotification *)notification;
+ (CGFloat)keyboardHeightCurOri;
+ (CGFloat)taskBarHeight;
+ (void)setTaskBarHeight:(CGFloat)height Animated:(BOOL)animated;
+ (BOOL)isTaskBarHidden;
+ (void)setTopBarHidden:(BOOL)topBarHidden withAnimation:(NSInteger)animation;
+ (void)setTopBarHidden:(BOOL)topBarHidden;
+ (BOOL)isTopBarHidden;
+ (NSInteger)getRotatedOrientation;
+ (void)setStatusBarHidden:(BOOL)statusBarHidden withAnimation:(NSInteger)animation;
+ (void)setStatusBarHidden:(BOOL)statusBarHidden;
+ (BOOL)isStatusBarLandscape;
+ (BOOL)isStatusBarHidden;
+ (void)OnSystemStatusBarFrameChange;
+ (void)OnSystemStatusBarOrientationChange:(NSInteger)arg1;
+ (UIWindow *)getTopVisibleWindow;
+ (UIWindow *)mainWindow;
+ (CGFloat)visibleHeight:(id)arg1;
+ (CGRect)screenBoundsOri:(NSInteger)arg1;
+ (CGRect)windowBounds;
+ (CGRect)screenBounds;
+ (CGSize)screenSizeOri:(NSInteger)arg1;
+ (CGSize)screenSize;
+ (CGFloat)mainScreenWidth;
+ (CGFloat)screenWidth:(NSInteger)width;
+ (CGFloat)screenWidthCurOri;
+ (CGFloat)screenHeight:(NSInteger)height;
+ (CGFloat)screenHeightCurOri;
+ (CGFloat)navigationBarHeight:(NSInteger)height;
+ (CGFloat)navigationBarHeightCurOri;
+ (CGFloat)navigationBarHeight;
+ (CGFloat)statusBarHeight:(NSInteger)arg1;
+ (CGFloat)statusBarHeight;

@end

