//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface __BlueChannel : NSObject
{
    int _m_state;
    NSInteger _m_deviceId;
    NSInteger _m_channelId;
    NSInteger _m_sessionId;
}

@property(nonatomic) int m_state; // @synthesize m_state=_m_state;
@property(nonatomic) NSInteger m_sessionId; // @synthesize m_sessionId=_m_sessionId;
@property(nonatomic) NSInteger m_channelId; // @synthesize m_channelId=_m_channelId;
@property(nonatomic) NSInteger m_deviceId; // @synthesize m_deviceId=_m_deviceId;

@end

