//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBCoding.h"

@class NSData, NSDictionary, NSString;

@interface CBaseContact : NSObject <PBCoding, NSCoding>
{
    NSString *m_nsUsrName;
    NSString *m_nsEncodeUserName;
    NSString *m_nsAliasName;
    NSUInteger m_uiConType;
    NSString *m_nsNickName;
    NSString *m_nsFullPY;
    NSString *m_nsShortPY;
    NSString *m_nsRemark;
    NSString *m_nsRemarkPYShort;
    NSString *m_nsRemarkPYFull;
    NSString *m_nsDisplayNamePY;
    NSUInteger m_uiSex;
    NSUInteger m_uiType;
    NSUInteger m_uiChatState;
    NSData *m_dtUsrImg;
    NSString *m_nsImgStatus;
    NSString *m_nsHDImgStatus;
    NSString *m_nsHeadImgUrl;
    NSString *m_nsHeadHDImgUrl;
    NSString *m_nsHeadHDMd5;
    NSString *m_nsDraft;
    NSUInteger m_uiDraftTime;
    NSString *m_nsAtUserList;
    NSUInteger m_uiQQUin;
    NSString *m_nsQQNickName;
    NSString *m_nsQQRemark;
    NSString *m_nsMobileIdentify;
    NSString *m_nsGoogleContactName;
    NSString *m_nsGoogleContactNickName;
    NSUInteger m_uiFriendScene;
    NSUInteger m_uiImgKey;
    NSUInteger m_uiExtKey;
    NSUInteger m_uiImgKeyAtLastGet;
    NSUInteger m_uiExtKeyAtLastGet;
    BOOL m_hasDetectPlugin;
    BOOL m_isPlugin;
    BOOL m_hasDetectSelf;
    BOOL m_isSelf;
    NSString *m_nsAntispamTicket;
    NSDictionary *_externalInfoJSONCache;
}

+ (void)initialize;
@property(strong, nonatomic) NSDictionary *externalInfoJSONCache; // @synthesize externalInfoJSONCache=_externalInfoJSONCache;
@property(strong, nonatomic) NSString *m_nsDisplayNamePY; // @synthesize m_nsDisplayNamePY;
@property(strong, nonatomic) NSString *m_nsAntispamTicket; // @synthesize m_nsAntispamTicket;
@property(strong, nonatomic) NSString *m_nsShortPY; // @synthesize m_nsShortPY;
@property(strong, nonatomic) NSString *m_nsAtUserList; // @synthesize m_nsAtUserList;
@property(nonatomic) NSUInteger m_uiDraftTime; // @synthesize m_uiDraftTime;
@property(nonatomic) NSUInteger m_uiFriendScene; // @synthesize m_uiFriendScene;
@property(strong, nonatomic) NSString *m_nsGoogleContactNickName; // @synthesize m_nsGoogleContactNickName;
@property(strong, nonatomic) NSString *m_nsGoogleContactName; // @synthesize m_nsGoogleContactName;
@property(strong, nonatomic) NSString *m_nsMobileIdentify; // @synthesize m_nsMobileIdentify;
@property(strong, nonatomic) NSString *m_nsQQRemark; // @synthesize m_nsQQRemark;
@property(strong, nonatomic) NSString *m_nsQQNickName; // @synthesize m_nsQQNickName;
@property(nonatomic) NSUInteger m_uiQQUin; // @synthesize m_uiQQUin;
@property(nonatomic) NSUInteger m_uiExtKeyAtLastGet; // @synthesize m_uiExtKeyAtLastGet;
@property(nonatomic) NSUInteger m_uiImgKeyAtLastGet; // @synthesize m_uiImgKeyAtLastGet;
@property(nonatomic) NSUInteger m_uiExtKey; // @synthesize m_uiExtKey;
@property(nonatomic) NSUInteger m_uiImgKey; // @synthesize m_uiImgKey;
@property(strong, nonatomic) NSString *m_nsDraft; // @synthesize m_nsDraft;
@property(strong, nonatomic) NSString *m_nsHeadHDMd5; // @synthesize m_nsHeadHDMd5;
@property(strong, nonatomic) NSString *m_nsHeadHDImgUrl; // @synthesize m_nsHeadHDImgUrl;
@property(strong, nonatomic) NSString *m_nsHeadImgUrl; // @synthesize m_nsHeadImgUrl;
@property(strong, nonatomic) NSString *m_nsHDImgStatus; // @synthesize m_nsHDImgStatus;
@property(strong, nonatomic) NSString *m_nsImgStatus; // @synthesize m_nsImgStatus;
@property(strong, nonatomic) NSData *m_dtUsrImg; // @synthesize m_dtUsrImg;
@property(nonatomic) NSUInteger m_uiChatState; // @synthesize m_uiChatState;
@property(nonatomic) NSUInteger m_uiType; // @synthesize m_uiType;
@property(nonatomic) NSUInteger m_uiSex; // @synthesize m_uiSex;
@property(strong, nonatomic) NSString *m_nsRemarkPYFull; // @synthesize m_nsRemarkPYFull;
@property(strong, nonatomic) NSString *m_nsRemarkPYShort; // @synthesize m_nsRemarkPYShort;
@property(strong, nonatomic) NSString *m_nsRemark; // @synthesize m_nsRemark;
@property(strong, nonatomic) NSString *m_nsFullPY; // @synthesize m_nsFullPY;
@property(nonatomic) NSUInteger m_uiConType; // @synthesize m_uiConType;
@property(strong, nonatomic) NSString *m_nsAliasName; // @synthesize m_nsAliasName;
@property(strong, nonatomic) NSString *m_nsEncodeUserName; // @synthesize m_nsEncodeUserName;
@property(strong, nonatomic) NSString *m_nsUsrName; // @synthesize m_nsUsrName;
@property(readonly, nonatomic) BOOL m_isPlugin; // @synthesize m_isPlugin;
- (id)localizedStringForMale:(id)arg1 female:(id)arg2 andUnkownSex:(id)arg3;
- (int)getImageStatusCode;
- (BOOL)isHasGMail;
- (id)getQQDisplayName;
- (BOOL)isHasQQDisplayName;
- (BOOL)isHasQQ;
- (BOOL)isWeixinTeamContact;
- (BOOL)isSelf;
- (BOOL)hasContactDisplayUsrNameByCache;
- (BOOL)hasContactDisplayUsrName;
- (id)getContactDisplayUsrName;
- (id)getContactTalkRoomName;
- (id)getContactDisplayName;
- (void)setDisplayNamePY;
- (id)getRemark;
- (void)saveUserImage;
- (id)getContactHeadImage;
- (BOOL)isNeedGetHDImg;
- (BOOL)isHasHDImg;
- (BOOL)isNeedGetUsrImgWithoutCheckLocalFile;
- (BOOL)isNeedGetUsrImg;
- (BOOL)isEnterpriseContact;
- (BOOL)isWeSportContact;
- (BOOL)isChatStatusNotifyOpen;
- (BOOL)isMacHelper;
- (BOOL)isQQ;
- (BOOL)isQQMBlog;
- (BOOL)isTemplateMsgHolder;
- (BOOL)isFileHelper;
- (BOOL)isBrandSessionHolder;
- (BOOL)isGroupCard;
- (BOOL)isChatroom;
- (BOOL)isLbsroom;
- (BOOL)isWeixin;
- (BOOL)isMMContact;
- (BOOL)isFavour;
- (void)setSnsBlack:(BOOL)arg1;
- (BOOL)isSnsBlack;
- (void)setBlack:(BOOL)arg1;
- (BOOL)isBlack;
- (BOOL)isEqualToName:(id)arg1;
- (BOOL)isEqualToContact:(id)arg1;
- (id)getEncodeUserName;
- (BOOL)isValid;
- (void)setChatRoomTopic:(id)arg1;
- (id)chatRoomTopic;
- (long long)compare:(id)arg1;
@property(readonly, copy) NSString *description;
- (BOOL)copyFrom:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (void)setRemarkWithoutEmojiChange:(id)arg1;
- (void)setNickNameWithoutEmojiChange:(id)arg1;
@property(strong, nonatomic) NSString *m_nsNickName; // @synthesize m_nsNickName;
- (NSUInteger)realFriendScene;
- (const map_490096f0 *)getValueTagIndexMap;
- (id)getValueTypeTable;


@end

