//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSFileHandle, NSString;

@interface CBaseFile : NSObject
{
    NSFileHandle *m_fhFile;
    NSString *m_nsFilePath;
    unsigned int m_uiMode;
    BOOL m_bOpen;
}

+ (void)tryResetFileProtection:(id)arg1;
+ (id)GetDataMD5:(id)arg1;
+ (id)GetFileMD5:(id)arg1;
+ (id)GetFileCreateTime:(id)arg1;
+ (BOOL)SysAppendData:(id)arg1 toPath:(id)arg2;
+ (BOOL)SysOverWriteDataToPath:(id)arg1 Data:(id)arg2;
+ (BOOL)OverWriteDataToPath:(id)arg1 Data:(id)arg2;
+ (BOOL)AppendData:(id)arg1 toPath:(id)arg2;
+ (BOOL)WriteDataToPath:(id)arg1 Offset:(unsigned int)arg2 Data:(id)arg3;
+ (id)LoadDataFromPathEx:(id)arg1 Offset:(unsigned int)arg2 MaxLen:(unsigned int)arg3;
+ (id)LoadDataFromPath:(id)arg1 Offset:(unsigned int)arg2 Len:(unsigned int)arg3;
+ (BOOL)CreateSymbolLink:(id)arg1 LinkName:(id)arg2;
+ (void)ClearPath:(id)arg1 WithOut:(id)arg2;
+ (void)SyncClearPath:(id)arg1;
+ (void)ClearPath:(id)arg1;
+ (BOOL)RemoveFile:(id)arg1;
+ (BOOL)LoadSubFolders:(id)arg1 SubFiles:(id)arg2 fromFolderPath:(const char *)arg3;
+ (id)SubFilesName:(const char *)arg1;
+ (id)SubFoldersName:(const char *)arg1;
+ (long long)FolderSizeAtPath:(const char *)arg1;
+ (long long)GetFileSize:(id)arg1;
+ (long long)GetFiLeModifyTime:(id)arg1;

/**
 判断文件是否存在

 @param filePath 文件路径
 @return 结果
 */
+ (BOOL)FileExist:(NSString *)filePath;
+ (BOOL)CopyFile:(id)arg1 To:(id)arg2;
+ (BOOL)SafeRenameFiles:(id)arg1 error:(id *)arg2;
+ (BOOL)SafeRenameFiles:(id)arg1;
+ (BOOL)RenameFile:(id)arg1 To:(id)arg2;
+ (void)EnsureCreateParentDir:(id)arg1;
+ (BOOL)CreatePath:(id)arg1;
+ (BOOL)CreateFile:(id)arg1;
@property(retain, nonatomic) NSFileHandle *m_fhFile; // @synthesize m_fhFile;
@property(retain, nonatomic) NSString *m_nsFilePath; // @synthesize m_nsFilePath;

- (BOOL)WriteLargeData:(id)arg1;
- (BOOL)WriteData:(id)arg1;
- (BOOL)ReadData:(id)arg1 Len:(unsigned int)arg2;
- (unsigned long long)SeekToEndOfFile;
- (BOOL)Seek:(long long)arg1;
- (BOOL)SetFileSize:(long long)arg1;
- (void)Close;
- (BOOL)Open;
- (BOOL)IsOpen;
- (BOOL)SetFileInfo:(id)arg1 Mode:(unsigned int)arg2;
- (void)dealloc;
- (id)init;

@end

