//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class NSMutableDictionary;
@class CContact;

@interface CContactOPLog : NSObject
{
    NSMutableDictionary *m_dicSkipContacts;
}

+ (NSUInteger)start_ModifyContact:(CContact *)contact;
+ (id)getModifyContactData:(id)arg1 addScene:(NSUInteger)addScene delScene:(NSUInteger)delScene;

- (BOOL)add_ModifyNotifyStatus:(id)arg1 withStatus:(NSUInteger)status NeedSync:(BOOL)isNeed;
- (BOOL)add_DeleteChatMsg:(id)arg1 sync:(BOOL)isSync;
- (BOOL)add_DeleteChatContact:(id)arg1 sync:(BOOL)isSync;
- (BOOL)add_ModifyContact:(id)arg1 delScene:(NSUInteger)delScene sync:(BOOL)isSync;
- (BOOL)add_ModifyContact:(id)arg1 addScene:(NSUInteger)addScene sync:(BOOL)isSync;
- (BOOL)add_ModifyContact:(id)arg1 sync:(BOOL)arg2;
- (BOOL)add_ModifyContact:(id)arg1 addScene:(NSUInteger)addScene delScene:(NSUInteger)delScene sync:(BOOL)isSync;
- (BOOL)isSkipContact:(id)arg1;
- (void)add_SkipContact:(id)arg1;
- (instancetype)init;

@end

