//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"
#import "PBMessageObserverDelegate.h"

@interface ContactRemarkLogic : MMObject <PBMessageObserverDelegate>

- (BOOL)deleteCardImg:(id)arg1;
- (void)onUploadCardImg:(id)arg1;
- (BOOL)uploadCardImg:(id)arg1 image:(id)arg2 clientId:(id)arg3 startPos:(unsigned int)pos;
- (BOOL)uploadCardImg:(id)arg1 image:(id)arg2;
- (void)onDownloadCardImg:(id)arg1;
- (void)downloadCardImg:(id)arg1;
- (void)tryDeleteInvalidateCardImg:(id)arg1;
- (id)getCardImg:(id)arg1;
- (id)pathForCardImage:(id)arg1 url:(id)arg2;
- (id)listCardImgFile;


@end

