//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class NSArray, UIView;

@interface EditImageColorSquareBar : MMUIView
{
    NSArray *colorArr;
    double colorBarIndividualWidth;
    UIView *selectDotView;
    long long colorIndex;
    id <EditImageColorSquareBarDelegate> _m_delegate;
}

@property(nonatomic) __weak id <EditImageColorSquareBarDelegate> m_delegate; // @synthesize m_delegate=_m_delegate;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (void)setColorSqaureWithIndex:(long long)arg1 withAnimation:(_Bool)arg2;
- (void)setColorSquare:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)didEndTouches:(id)arg1 withEvent:(id)arg2;
- (void)handleTouches:(id)arg1 withEvent:(id)arg2 touchBegan:(_Bool)arg3;
- (void)reloadView;
- (void)initView;
- (id)initWithFrame:(struct CGRect)arg1 withDelegate:(id)arg2 withDefaultColorIndex:(long long)arg3;

@end

