//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSDictionary, NSMutableArray;

@interface FaceRecog3rdVerifyConfirmLogic : MMObject <PBMessageObserverDelegate>
{
    id <FaceRecog3rdVerifyConfirmLogicDelegate> _delegate;
    NSMutableArray *_confirmInfos;
    NSDictionary *_prompts;
}

@property(retain, nonatomic) NSDictionary *prompts; // @synthesize prompts=_prompts;
@property(retain, nonatomic) NSMutableArray *confirmInfos; // @synthesize confirmInfos=_confirmInfos;
@property(nonatomic) __weak id <FaceRecog3rdVerifyConfirmLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleGetConfirmInfo:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)startGetConfirmInfo:(id)arg1 verifyInfo:(id)arg2;
- (id)getPrompts;
- (id)getConfirmInfos;
- (void)dealloc;
- (id)init;

@end

