//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ICdnComMgrExt.h"

@class NSString;

@interface FaceRecogUploadLogic : MMObject <ICdnComMgrExt>
{
    _Bool _uploading;
    unsigned int _currentResourceType;
    id <FaceRecogUploadLogicDelegate> _delegate;
    NSString *_currentFaceResultClientId;
    NSString *_currentFaceVideoClientId;
}

+ (id)genResourceClientId:(id)arg1;
@property(nonatomic) _Bool uploading; // @synthesize uploading=_uploading;
@property(nonatomic) unsigned int currentResourceType; // @synthesize currentResourceType=_currentResourceType;
@property(retain, nonatomic) NSString *currentFaceVideoClientId; // @synthesize currentFaceVideoClientId=_currentFaceVideoClientId;
@property(retain, nonatomic) NSString *currentFaceResultClientId; // @synthesize currentFaceResultClientId=_currentFaceResultClientId;
@property(nonatomic) __weak id <FaceRecogUploadLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onUploadOperationFinish:(id)arg1;
- (void)OnCdnUpload:(id)arg1;
- (_Bool)isUploadedCorrectResource:(id)arg1;
- (_Bool)startUploadFaceVideo:(unsigned long long)arg1;
- (_Bool)startUploadFaceResult:(unsigned long long)arg1;
- (_Bool)isUploading;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

