//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSString;

@interface FaceRecogBindVideoLogic : MMObject <PBMessageObserverDelegate>
{
    _Bool _needRetry;
    int _resultCode;
    id <FaceRecogBindVideoLogicDelegate> _delegate;
    NSString *_identifyId;
    NSString *_resultMsg;
}

@property(nonatomic) _Bool needRetry; // @synthesize needRetry=_needRetry;
@property(copy, nonatomic) NSString *resultMsg; // @synthesize resultMsg=_resultMsg;
@property(nonatomic) int resultCode; // @synthesize resultCode=_resultCode;
@property(copy, nonatomic) NSString *identifyId; // @synthesize identifyId=_identifyId;
@property(nonatomic) __weak id <FaceRecogBindVideoLogicDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleBindVideo:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)startBindVideo:(id)arg1 bioId:(unsigned long long)arg2 videoFileId:(id)arg3 videoAesKey:(id)arg4;
- (void)resetBindVideoLogic;
- (void)dealloc;
- (id)init;

@end

