//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IAcctStorageMgrExt.h"
#import "IBrandAttrMgrExt.h"
#import "IContactProfileMgrExt.h"
#import "IMMLanguageMgrExt.h"
#import "MMService.h"
#import "MessageObserverDelegate.h"
#import "PBMessageObserverDelegate.h"

@class CContactDB, CContactOPLog,CContact, NSMutableDictionary, NSRecursiveLock, NSString, NewContactDB;

@interface CContactMgr : MMService <MMService, MessageObserverDelegate, IContactProfileMgrExt, PBMessageObserverDelegate, IAcctStorageMgrExt, IMMLanguageMgrExt, IBrandAttrMgrExt>
{
    NSRecursiveLock *m_oLock;
    unsigned int m_uiLoadedType;
    CContactDB *m_oContactDB;
    NewContactDB *m_oNewContactDB;
    CContactOPLog *m_oContactOPLog;
    NSMutableDictionary *m_dicRemark;
    NSMutableDictionary *m_dicLastAccessTime;
    NSMutableDictionary *m_dicContacts;
    NSMutableDictionary *m_dicEncodeContacts;
    NSMutableDictionary *m_mapLastGetTime;
    NSMutableDictionary *m_dicHardCodeUsers;
    unsigned int m_uiDBVersion;
    BOOL m_shouldContactDBMigration;
    BOOL m_bContactDBMigrationFinished;
    unsigned int m_uiMaxStrangerCache;
    BOOL m_bOpenStrangerCache;
}

- (id)getAllContactUserName;
- (CContact *)getContactForSearchByName:(id)arg1;
- (BOOL)isOpenStrangerCache;
- (void)callModifyContactForCPState:(id)arg1;
- (BOOL)isHeadImgUpdated:(id)arg1 Local:(id)arg2;
- (BOOL)ChangeNotifyStatus:(id)arg1 withStatus:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)ChangeNotifyStatusForChatRoom:(id)arg1 withStatus:(BOOL)arg2 sync:(BOOL)arg3;
- (void)main_onPushModifyContact:(id)arg1;
- (id)thread_onBatchModifyChatRoomMember:(id)arg1;
- (id)thread_onpushBatchModContact:(id)arg1;
- (void)main_onPushAddContact:(id)arg1;
- (void)main_onPushDeleteContact:(id)arg1;
- (void)setSelfContactUpdated;
- (CContact *)getSelfContact;
- (BOOL)updateContactToCache:(id)arg1;
- (BOOL)shouldUpdateContact:(id)arg1;
- (void)onGetContact:(id)arg1;
- (id)HandleMemContact:(id)arg1;
- (void)MainThread_ReloadMemContact:(id)arg1;
- (void)thread_ReloadMemConact:(id)arg1 ChatRoom:(id)arg2;
- (id)thread_HandleMemContact:(id)arg1;
- (void)main_onPushBatchModContact:(id)arg1;
- (void)updateContactLocalData;
- (void)fixContactPluginOldData;
- (id)getGroupCardMemberList:(id)arg1;
- (BOOL)getContactsFromServer:(id)arg1 chatContact:(id)arg2 withScene:(int)arg3 withTicket:(id)arg4 usrData:(id)arg5;
- (BOOL)getInviteeContactsFromServer:(id)arg1 withTicket:(id)arg2;
- (BOOL)getContactsFromServer:(id)arg1;
- (BOOL)getContactsFromServer:(id)arg1 chatContact:(id)arg2;
- (BOOL)getContactsFromSvrForTempChat:(id)arg1;
- (BOOL)internalGetContactsFromSvr:(id)arg1 chatContact:(id)arg2 usrData:(id)arg3;
- (void)addToGetContactMap:(id)arg1;
- (BOOL)checkIfForbiddenGetContact:(id)arg1;
- (BOOL)syncAllSXContact;
- (void)tryLoadExtInfoForContact:(id)arg1;
- (void)reloadContact:(id)arg1;
- (BOOL)delayLoadAllContactInBackGround;
- (void)reportIDKey:(id)arg1 stranger:(id)arg2;
- (void)thread_saveContactImageStatus:(id)arg1 Status:(id)arg2 Image:(id)arg3 Url:(id)arg4;
- (void)reloadContactImageStatus:(id)arg1 Status:(id)arg2 Image:(id)arg3;
- (BOOL)setHDHeadUpdated:(id)arg1;
- (BOOL)setContact:(CContact *)contact chatState:(unsigned int)arg2;
- (BOOL)setContact:(CContact *)contact antispamTicket:(id)arg2;
- (BOOL)setContact:(CContact *)contact textTranslateOpen:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setLocalContactToUntopSession:(id)arg1;
- (BOOL)setContact:(CContact *)contact sessionTop:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setContact:(CContact *)contact notifyOpen:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setContact:(CContact *)contact hideHashPhone:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setContact:(CContact *)contact watchContact:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setContact:(CContact *)contact favour:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setLocalContact:(id)arg1 notifyOpen:(BOOL)arg2;
- (BOOL)setContact:(CContact *)contact typeBit:(unsigned int)typeBit set:(BOOL)set sync:(BOOL)sync;
- (BOOL)setContact:(CContact *)contact typeBit:(unsigned int)typeBit set:(BOOL)set sync:(BOOL)sync localSet:(BOOL)localSet;
- (BOOL)setNoBlack:(id)arg1 sync:(BOOL)arg2;
- (BOOL)setBlack:(id)arg1 sync:(BOOL)arg2;
- (BOOL)setNoBlack:(id)arg1;
- (BOOL)setBlack:(id)arg1;
- (BOOL)setBlack:(id)arg1 blackFlag:(BOOL)arg2 sync:(BOOL)arg3;
- (BOOL)setContact:(CContact *)contact chatRoomAccessType:(unsigned int)arg2;
- (BOOL)setContact:(CContact *)contact RoomDetail:(id)arg2;
- (BOOL)setContact:(CContact *)contact chatRoomData:(id)arg2;
- (BOOL)setContact:(CContact *)contact owner:(id)arg2;
- (BOOL)setContact:(CContact *)contact snsBlack:(BOOL)arg2;
- (BOOL)setContact:(CContact *)contact mobileIdentify:(id)arg2;
- (BOOL)setContact:(CContact *)contact googleContactName:(id)arg2;
- (BOOL)setContact:(CContact *)contact googleContactNickName:(id)arg2;
- (BOOL)clearDraftForContact:(id)arg1;
- (BOOL)setContact:(CContact *)contact nickName:(id)arg2;
- (BOOL)setContact:(CContact *)contact cardUrl:(id)arg2;
- (BOOL)setContact:(CContact *)contact cardDesc:(NSString *)desc;
- (BOOL)setPhone:(id)arg1 Contact:(id)arg2;
- (BOOL)setContact:(CContact *)contact remark:(id)arg2;
- (BOOL)setContact:(CContact *)contact remark:(id)arg2 hideHashPhone:(BOOL)arg3;
- (void)modifyContactNickName:(id)arg1 nickName:(id)arg2 callMod:(BOOL)arg3;
- (BOOL)RemoveContactFromChatList:(id)arg1;
- (BOOL)deleteContact:(id)arg1 listType:(unsigned int)listType andScene:(unsigned int)addScene sync:(BOOL)sync local:(BOOL)local;
- (BOOL)deleteContact:(id)arg1 listType:(unsigned int)listType andScene:(unsigned int)addScene sync:(BOOL)sync;
- (BOOL)deleteContact:(id)arg1 listType:(unsigned int)listType sync:(BOOL)sync;
- (BOOL)deleteContact:(id)arg1 listType:(unsigned int)listType;
- (BOOL)deleteContactLocal:(id)arg1 listType:(unsigned int)listType;
- (BOOL)addFromMobileContact:(id)arg1;
- (BOOL)addFromQQContact:(id)arg1;
- (BOOL)addLocalContact:(id)arg1 listType:(unsigned int)listType;
- (void)addContactInternal:(id)arg1;
- (BOOL)addContact:(id)arg1 listType:(unsigned int)listType;
- (BOOL)addContact:(id)arg1 listType:(unsigned int)listType opLog:(BOOL)opLog;
- (id)getAllBrandContacts;
- (id)getAllEnterpriseMainBrandContacts;
- (id)getContactList:(unsigned int)arg1 contactType:(unsigned int)contactType needLoadExt:(BOOL)isNeedLoadExt;
- (id)getContactList:(unsigned int)arg1 contactType:(unsigned int)contactType;
- (BOOL)isBelongToMMContactInCache:(id)arg1;
- (BOOL)isInContactList:(id)arg1;
- (BOOL)isContactExistLocal:(id)arg1;
- (BOOL)isContactBlack:(id)arg1;
- (CContact *)getContactByNameFromCache:(id)arg1;
- (CContact *)getContactByNameFromDB:(id)arg1;
- (CContact *)getContactByName:(NSString *)name;
- (void)updateCache:(id)arg1;
- (void)initDB:(id)arg1;
- (void)updateNewDB:(id)arg1 NewUser:(BOOL)arg2;
- (BOOL)isUserNewDB;
- (void)onPushDeleteContact:(id)arg1;
- (void)onPushModifyContact:(id)arg1 updateImage:(BOOL)arg2;
- (void)handleLocalField:(id)arg1 oldContact:(id)arg2;
- (id)reloadContact:(id)arg1 mergeImage:(id)arg2;
- (void)callOnRemoveContactFromAddressBook:(id)arg1;
- (void)callOnModifyContactHeadImageExt:(id)arg1;
- (void)callOnDeleteExt:(id)arg1;
- (void)callOnModifyExt:(id)arg1;
- (void)internalDeleteContact:(id)arg1;
- (void)internalModifyContact:(id)arg1;
- (void)internalNewContact:(id)arg1;
- (void)mergeChatRoomData:(id)arg1 oldContact:(id)arg2;
- (void)handleWeChatTeamNickName:(id)arg1;
- (void)handleOfficalContactName:(id)arg1;
- (BOOL)isContactMatch:(id)arg1 listType:(unsigned int)listType contactType:(unsigned int)contactType;
- (int)interalReloadContacts:(unsigned int)arg1 needLoadExt:(BOOL)isNeedLoadExt;
- (BOOL)isHardCodeContact:(id)arg1;
- (void)addHardCodeContacts;
- (void)addAddHardcodeContact:(id)arg1 selector:(SEL)arg2;
- (id)generateOfficialContact:(id)arg1;
- (id)generatePluginContactNoListContact:(id)arg1;
- (id)generatePluginContact:(id)arg1;
- (id)generatePluginContact:(id)arg1 uiType:(unsigned int)uiType;
- (void)internalUpdateContactLocalDataWithUserName:(id)arg1;
- (void)refreshContactLocalData;
- (void)refreshPluginNickName:(BOOL)arg1;
- (void)addDictoryDataToCache:(id)arg1 listType:(unsigned int)listType;
- (int)autoreloadContacts:(unsigned int)arg1 needLoadExt:(BOOL)isNeedLoadExt;
- (int)autoreloadContacts:(unsigned int)arg1;
- (id)addSelfContactToCache;
- (BOOL)isCacheAllLoaded;
- (void)dealloc;
- (void)removeListen;
- (void)initListen;
- (instancetype)init;
- (BOOL)SetFriendMetaFlag:(unsigned int)arg1 ForUser:(id)arg2;
- (BOOL)SetLastUpdateTime:(unsigned int)arg1 ForUser:(id)arg2;
- (BOOL)ModifyNotifyStatus:(id)arg1 withStatus:(unsigned int)arg2;
- (BOOL)thread_onPushModifyContact:(id)arg1 isInit:(BOOL)isInit;
- (BOOL)thread_BatchModifyContact:(id)arg1;
- (BOOL)thread_BatchModifyContact:(id)arg1 isInit:(BOOL)isInit;
- (id)addOrUpdateContactToDB:(id)arg1 listType:(unsigned int)listType add:(BOOL *)isAdd modify:(BOOL *)arg4;
- (BOOL)getAllRemarkList:(id)arg1 listType:(unsigned int)listType;
- (BOOL)getAllUserName:(id)arg1;
- (BOOL)getAllContactNoExtInfoList:(id)arg1 listType:(unsigned int)listType;
- (BOOL)getAllContactList:(id)arg1 listType:(unsigned int)listType;
- (BOOL)migrationContacts:(unsigned int)arg1 first:(BOOL)arg2;
- (void)reportMigrationStat:(unsigned int)arg1 status:(unsigned int)arg2;
- (BOOL)splist_migrationContactList:(id)arg1;
- (void)setMigrationFinished;
- (BOOL)loadContactExtInfo:(id)arg1;
- (BOOL)updateContactToDb:(id)arg1;
- (BOOL)addContactToDb:(id)arg1;
- (BOOL)removeContactFromDB:(id)arg1;
- (CContact *)getContactFromDB:(NSString *)username;
- (void)removeContactFromDic:(id)arg1;
- (void)setContactToDic:(id)arg1 forKey:(id)arg2;
- (id)getContactFromDic:(id)arg1;


@end

