//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IClearDataMgrExt.h"
#import "MMService.h"

@class NSBundle, NSString;

@interface MMLanguageMgr : MMService <IClearDataMgrExt, MMService>
{
    NSString *m_nsCurSystemLanguage;
    NSString *m_curLanguage;
    NSBundle *m_curBundle;
    NSBundle *m_backupBundle;
    BOOL bDownloadPackageRightNow;
}

- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1 subQueue:(id)arg2;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1 CacheMask:(unsigned int)arg2;
- (void)onDiskStorageWarningCleanedSize:(unsigned long long *)arg1;
- (BOOL)isVersionString:(id)arg1 olderThanMajor:(unsigned int *)arg2 minor:(unsigned int *)arg3 minorex:(unsigned int *)arg4;
- (void)ClearOlderVersionData;
- (void)refreshNewVersionForCurLanguage:(id)arg1 fromViewScene:(unsigned int)arg2;
- (void)setCurLanguage:(id)arg1 shouldChangeMainFrame:(BOOL)arg2;
- (void)setCurLanguage:(id)arg1 forRefresh:(BOOL)arg2 withViewScene:(unsigned int)arg3 shouldChangeMainFrame:(BOOL)arg4;
- (BOOL)curLanguageIsChineseTraditional;
- (NSString *)getStringForLanguage:(id)arg1 withID:(id)arg2 defaultTo:(id)arg3;
- (NSString *)getStringForCurLanguage:(id)arg1 defaultTo:(id)arg2 table:(id)arg3;
- (NSString *)getStringForCurLanguage:(id)arg1 defaultTo:(id)arg2;
- (NSString *)getStringForCurLanguage:(id)arg1 defaultString:(id)arg2;
- (NSString *)getStringForCurLanguageWithBackupBundle:(id)arg1 defaultTo:(id)arg2 table:(id)arg3;
- (NSString *)getStringForCurLanguageWithBackupBundle:(id)arg1 defaultTo:(id)arg2;
- (NSString *)getSupportedLanguageDisplayNames;
- (id)getSupportedLanguages;
- (NSString *)getCurLanguageDisplayName;
- (id)getCurLanguage;
- (id)getCurBundle;

- (void)initLanguage;
- (BOOL)isLanaguageValid;
- (void)initBackUpLanguage;
- (BOOL)ifNeedBackupBundle;
- (id)getBackUpLanguage;
- (id)isSupportedLanguage:(id)arg1;
- (id)getRealCurSystemLanguage;
- (id)getCurSystemLanguage;
- (id)trimForiOS9Plus:(id)arg1;
- (void)internalSetCurLanguage:(id)arg1;
- (id)internalGetCurLanguage;
- (id)getLanguagePath;
- (id)getLangPackageVerifiedFailFileForLang:(id)arg1;
- (id)getLangPackageNotVerifiedFileForLang:(id)arg1;
- (id)getLangPackageFileForLang:(id)arg1;
- (id)getLangPackageZipFileForLang:(id)arg1;
- (id)getLangPackagePathForLang:(id)arg1;
- (id)getLangPackageRootPath;

@end

