//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IContactMgrExt.h"
#import "IMMFontMgrExt.h"
#import "IMMLanguageMgrExt.h"
#import "IMMNewSessionMgrExt.h"
#import "MMService.h"

@class BaseMsgContentLogicController, NSMutableArray, NSString;

@interface MMMsgLogicManager : MMService <MMService, IMMLanguageMgrExt, IMMFontMgrExt, IContactMgrExt, IMMNewSessionMgrExt>
{
    NSMutableArray *_arrLogicControllers;
    BaseMsgContentLogicController *_topLogicController;
    BaseMsgContentLogicController *_weixinLogicController;
    BaseMsgContentLogicController *_roomLogicController;
    BaseMsgContentLogicController *_lastPeekController;
}

- (void).cxx_destruct;
- (void)finishedPeekingWithController:(id)arg1;
- (id)logicControllerForPeekingWithContact:(id)arg1 messageWrap:(id)arg2;
- (id)GetCurrentLogicController;
- (void)PopLogicController:(id)arg1 withReuse:(_Bool)arg2;
- (void)PopLogicController:(id)arg1;
- (void)PresentMultiSelectLogicControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3 onComplete:(CDUnknownBlockType)arg4;
- (void)PushOtherLogicController:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3;
- (void)PushNewLogicController:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3 jumpToLocationNode:(id)arg4;
- (void)PushSearchLogicControllerWithToolBarByContact:(id)arg1 navigationController:(id)arg2 ForMessageWrap:(id)arg3 animated:(_Bool)arg4;
- (void)PushSearchLogicControllerByContact:(id)arg1 navigationController:(id)arg2 ForMessageWrap:(id)arg3 animated:(_Bool)arg4 fromeScene:(int)arg5;
- (void)PushOtherBaseMsgControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3 searchScene:(int)arg4 extraInfo:(id)arg5;
- (void)PushOtherBaseMsgControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3 extraInfo:(id)arg4;
- (void)PushOtherBaseMsgControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3 searchScene:(int)arg4;
- (void)PushOtherBaseMsgControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3;
- (void)PushLBSRoomLogicControllerByContact:(id)arg1 navigationController:(id)arg2 animated:(_Bool)arg3;
- (void)cleanUnuseLogicController;


/**
 推送聊天页面逻辑
 
 @param aContact 通讯对象
 @param navigationController 页面从属导航控制器
 @param animated 动画标识
 @param locationNode 节点
 @param reuse 重用
 @param extraInfo 额外属性: @{@"AllUnReadCount":@(0)}--未读消息数
 */
- (void)PushLogicControllerByContact:(CContact *)aContact navigationController:(UINavigationController *)navigationController animated:(BOOL)animated jumpToLocationNode:(id)locationNode reuse:(BOOL)reuse extraInfo:(NSMutableDictionary *)extraInfo;
- (void)PushLogicControllerByContact:(CContact *)aContact navigationController:(UINavigationController *)navigationController animated:(BOOL)animated jumpToLocationNode:(id)locationNode reuse:(BOOL)reuse;
- (void)PushLogicControllerByContact:(CContact *)aContact navigationController:(UINavigationController *)navigationController animated:(BOOL)animated jumpToLocationNode:(id)locationNode;
- (void)PushLogicController:(id)controller navigationController:(UINavigationController *)navigationController animated:(BOOL)animated;

- (id)GetReuseableLogicControllerFromCacheWithContact:(Class)arg1;
- (id)GetLogicControllerFromCacheWithContact:(id)arg1;
- (void)setMsgLogicToCache:(id)arg1;
- (Class)GetLogicClassByContact:(id)arg1;
- (_Bool)onServiceMemoryWarning;
- (void)onPluginsChanged:(id)arg1;
- (void)onDeleteSession:(unsigned int)arg1;
- (void)onModifyContact:(id)arg1;
- (void)onDeleteContact:(id)arg1;
- (void)onFontSizeChange;
- (void)onLanguageChange;
- (void)onServiceReloadData;
- (void)CheckIfTopViewControllerPoped;
- (void)cleanUpLogicByName:(id)arg1;
- (void)cleanUp;
- (id)getTopLogicController;
- (void)dealloc;
- (void)onServiceInit;
@property(retain, nonatomic) BaseMsgContentLogicController *topLogicController;
@property(retain, nonatomic) NSMutableArray *arrLogicControllers;


@end

