//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

@class MMColor, MMDrawScript, MMRuleSetList, MMScriptInterpreter, MMTheme, NSMutableArray, NSMutableDictionary, NSRecursiveLock, NSString, NSThread;

@interface MMThemeManager : MMService <MMService>
{
    NSMutableArray *m_themeList;
    MMTheme *m_currentTheme;
    MMColor *m_colorList;
    NSMutableDictionary *m_imageCache;
    NSInteger m_cachedImageSize;
    MMRuleSetList *m_ruleSetList;
    MMRuleSetList *m_imageMapList;
    MMRuleSetList *m_resMapList;
    int m_ipadCssStyleType;
    NSThread *m_backgroundWorkerThread;
    MMDrawScript *m_drawScripts;
    MMScriptInterpreter *m_scriptInterpreter;
    NSRecursiveLock *m_lock;
}

+ (BOOL)useiPhone6CssForIpadCompact;
+ (BOOL)useiPadCss;
+ (int)getIpadStyleType;
+ (MMThemeManager *)allocWithZone:(NSZone *)zone;
+ (instancetype)sharedThemeManager;
+ (void)initialize;
@property(strong, nonatomic) MMScriptInterpreter *m_scriptInterpreter; // @synthesize m_scriptInterpreter;
@property(strong, nonatomic) MMDrawScript *m_drawScripts; // @synthesize m_drawScripts;
@property(strong, nonatomic) MMRuleSetList *m_resMapList; // @synthesize m_resMapList;
@property(strong, nonatomic) MMRuleSetList *m_imageMapList; // @synthesize m_imageMapList;
@property(strong, nonatomic) NSRecursiveLock *lock; // @synthesize lock=m_lock;
@property(strong, nonatomic) NSThread *backgroundWorkerThread; // @synthesize backgroundWorkerThread=m_backgroundWorkerThread;
@property(strong, nonatomic) MMRuleSetList *ruleSetList; // @synthesize ruleSetList=m_ruleSetList;
@property(strong, nonatomic) NSMutableDictionary *imageCache; // @synthesize imageCache=m_imageCache;
@property(strong, nonatomic) MMColor *colorList; // @synthesize colorList=m_colorList;
@property(strong, nonatomic) MMTheme *currentTheme; // @synthesize currentTheme=m_currentTheme;
@property(strong, nonatomic) NSMutableArray *themeList; // @synthesize themeList=m_themeList;

- (void)reloadCssForMultiTaskingIfNeed;
- (BOOL)onServiceMemoryWarning;
- (void)onFirstRun;
- (BOOL)changeThemeByThemeID:(id)arg1;
- (NSInteger)reloadThemeList;
- (void)waitForInstallDone;
- (BOOL)isInstallDone;
- (void)installThemeInBundleInBackground:(NSInteger)arg1;
- (void)startInstallThreadAfterDelay;
- (void)installThemeInBundle;
- (void)onBackgroundInstallDone;
- (BOOL)installThemeUpdatePack:(id)arg1;
- (void)uninstallAllThemes;
- (BOOL)isThemeDirExist;
- (id)getThemeDir;
- (id)imageFromScript:(id)arg1 withArguments:(id)arg2;
- (void)runScript:(id)arg1 withArguments:(id)arg2;
- (void)clearSelfCreateImage;
- (void)clearImageCache;
- (id)getValueOfProperty:(id)arg1 inRuleSet:(id)arg2;
- (id)getRuleSetForSeletor:(id)arg1;
- (id)imageFromColor:(id)arg1;
- (id)localizedImageNamed:(id)arg1;
- (id)localizedImageNamed:(id)arg1 inTheme:(id)arg2;
- (id)makeImageWithFitScale:(id)arg1;
- (id)translateToHDImageName:(id)arg1;
- (id)imageNamed:(id)arg1 Alpha:(float)arg2 Suffix:(id)arg3 ForDifferentIosVersion:(BOOL)arg4;
- (id)imageDisableNamed:(id)arg1;
- (id)imageHighlightNamed:(id)arg1;
- (id)getIconImageByName:(id)arg1;
- (id)imageNamed:(id)arg1;
- (id)getImageName:(id)arg1;
- (id)image_disable_for_different_ios_version:(id)arg1;
- (id)image_highlight_for_different_ios_version:(id)arg1;
- (id)image_for_different_ios_version:(id)arg1;
- (void)saveImage:(id)arg1 ToSelfCreateImagePath:(id)arg2;
- (id)imageFromSelfCreateImagePath:(id)arg1;
- (id)imageFromSystemFileContent:(id)arg1;
- (id)imageFromImageMap:(id)arg1;
- (id)pathOfResNamed:(id)arg1;
- (id)pathOfImageNamed:(id)arg1;
- (id)imageFromResPackage:(id)arg1 withName:(id)arg2;
- (id)imageFromStaticResourcePatchWithName:(id)arg1;
- (id)imageNamed:(id)arg1 inTheme:(id)arg2;
- (id)imageNamedWithCurTheme:(id)arg1;
- (void)setUserPreferedTheme:(id)arg1;
- (BOOL)loadUserPreferedThemeNoCallExtension;
- (BOOL)loadUserPreferedTheme;
- (BOOL)loadDefaultTheme;
- (id)getUserThemeIDPrefKey;
- (BOOL)needToClearCache;
- (void)removeImageSizeFromCachedSize:(id)arg1;
- (void)addImageSizeToCachedSize:(id)arg1;
- (void)reloadThemeResource;
- (void)loadScripts;
- (void)loadColors;
- (BOOL)loadCSSFromPath:(id)arg1 IntoRuleSetList:(id)arg2;
- (void)loadImageMap;
- (void)loadResPackageSetting;
- (void)loadRuleSets;
- (BOOL)unPackThemePackToThemeDir;
- (BOOL)isThemesZipInBundle;
- (id)getThemeByThemeID:(id)arg1;
- (id)getDefaultTheme;
- (id)fileOfImageNamed:(id)arg1;
- (BOOL)is568H2xScreen;
- (BOOL)is3xScreen;
- (BOOL)is2xScreen;
- (id)init;
- (void)removeFromThemeList:(id)arg1;
- (void)addToThemeList:(id)arg1;
- (id)getImageCacheObjectForKey:(id)arg1;
- (void)removeImageCacheObjectForKey:(id)arg1;
- (void)setImageCacheObject:(id)arg1 forKey:(id)arg2;

@end

