//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"
#import "WCHomepageDelegate.h"
#import "WCDataProviderDelegate.h"

@class MyWCDB, NSString, WCHomepageDataProvider_Sns;

@interface WCHomepageMgr : MMObject <WCDataProviderDelegate>
{
    NSString *m_username;
    id <WCHomepageDelegate> m_delegate;
    NSMutableArray *m_cache;
    MyWCDB *m_database;
    WCHomepageDataProvider_Sns *m_dataProvider;
}

+ (id)homepageMgrForUser:(id)arg1;
@property(strong, nonatomic) NSObject<OS_dispatch_queue> *homepageDBQueue;
@property(strong, nonatomic) NSString *m_username;
@property(strong, nonatomic) WCHomepageDataProvider_Sns *m_dataProvider;
@property(strong, nonatomic) MyWCDB *m_database;
@property(strong, nonatomic) NSMutableArray *m_cache;
@property(nonatomic, weak) id <WCHomepageDelegate> m_delegate;

- (NSUInteger)onServiceCleanCache;
- (void)onServiceMemoryWarning;
- (id)findDataItemInCacheByItemID:(id)arg1;
- (void)modifyCache:(id)arg1;
- (void)deleteDataItem:(id)arg1 notify:(BOOL)arg2;
- (void)modifyDataItem:(id)arg1 notify:(BOOL)arg2;
- (void)addDataItem:(id)arg1 notify:(BOOL)arg2;
- (id)getHomepageData;
- (BOOL)updateTail;
- (BOOL)updateHeadWithSource:(NSInteger)arg1;
- (BOOL)updateHead;
- (void)endHomepage;
- (void)beginHomepage;
- (id)dataProvider;


@end

