//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class GameIndexNav_Item, GameIndexNav_SearchModule;

@interface GameIndexNav : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) GameIndexNav_Item *myActivities; // @dynamic myActivities;
@property(retain, nonatomic) GameIndexNav_Item *myMessage; // @dynamic myMessage;
@property(retain, nonatomic) GameIndexNav_Item *myProfile; // @dynamic myProfile;
@property(retain, nonatomic) GameIndexNav_SearchModule *search; // @dynamic search;

@end

