//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class GetGameIndex2Response_Recommendation_Banner, GetGameIndex2Response_Recommendation_Item;

@interface GetGameIndex2Response_Recommendation : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) GetGameIndex2Response_Recommendation_Item *leftItem; // @dynamic leftItem;
@property(retain, nonatomic) GetGameIndex2Response_Recommendation_Item *rightItem; // @dynamic rightItem;
@property(retain, nonatomic) GetGameIndex2Response_Recommendation_Banner *topBanner; // @dynamic topBanner;

@end

