//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

/**
 图片信息封装
 */
@interface ImageInfo : NSObject <NSCopying>
{
    unsigned int m_uiImageSource;
    NSURL *m_nuImageSourceURL;
}

@property(retain, nonatomic) NSURL *m_nuImageSourceURL; // @synthesize m_nuImageSourceURL;
@property(nonatomic) unsigned int m_uiImageSource; // @synthesize m_uiImageSource;

- (id)copyWithZone:(NSZone *)arg1;
- (id)init;

@end

