//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface log_13997 : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int clientVersion; // @dynamic clientVersion;
@property(nonatomic) int device; // @dynamic device;
@property(nonatomic) int ds; // @dynamic ds;
@property(nonatomic) int errorCode; // @dynamic errorCode;
@property(retain, nonatomic) NSString *failUrl; // @dynamic failUrl;
@property(nonatomic) int importDs; // @dynamic importDs;
@property(nonatomic) long long timeStamp; // @dynamic timeStamp;
@property(nonatomic) long long uin; // @dynamic uin;

@end

