//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class Log_CanvasComponentButtonInfo, Log_CanvasComponentFullScreenImageInfo, Log_CanvasComponentGroupListInfo, Log_CanvasComponentLocationInfo, Log_CanvasComponentPanoramaInfo, Log_CanvasComponentPureImgInfo, Log_CanvasComponentSightInfo, Log_CanvasComponentStreamVideoInfo, Log_CanvasComponentTelephoneInfo, Log_CanvasComponentTextInfo, Log_CanvasComponentWebViewInfo;

@interface Log_CanvasComponentInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) Log_CanvasComponentButtonInfo *buttonInfo; // @dynamic buttonInfo;
@property(retain, nonatomic) Log_CanvasComponentFullScreenImageInfo *fullScreenImageInfo; // @dynamic fullScreenImageInfo;
@property(retain, nonatomic) Log_CanvasComponentGroupListInfo *groupListInfo; // @dynamic groupListInfo;
@property(retain, nonatomic) Log_CanvasComponentLocationInfo *locationInfo; // @dynamic locationInfo;
@property(retain, nonatomic) Log_CanvasComponentPanoramaInfo *panoramaInfo; // @dynamic panoramaInfo;
@property(retain, nonatomic) Log_CanvasComponentPureImgInfo *pureImgInfo; // @dynamic pureImgInfo;
@property(retain, nonatomic) Log_CanvasComponentSightInfo *sightInfo; // @dynamic sightInfo;
@property(retain, nonatomic) Log_CanvasComponentStreamVideoInfo *streamVideoInfo; // @dynamic streamVideoInfo;
@property(retain, nonatomic) Log_CanvasComponentTelephoneInfo *telephoneInfo; // @dynamic telephoneInfo;
@property(retain, nonatomic) Log_CanvasComponentTextInfo *textInfo; // @dynamic textInfo;
@property(nonatomic) int type; // @dynamic type;
@property(retain, nonatomic) Log_CanvasComponentWebViewInfo *webViewInfo; // @dynamic webViewInfo;

@end

