//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface Log_CanvasReportInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) int clientVersion; // @dynamic clientVersion;
@property(nonatomic) int componentCount; // @dynamic componentCount;
@property(retain, nonatomic) NSMutableArray *componentsList; // @dynamic componentsList;
@property(nonatomic) int device; // @dynamic device;
@property(nonatomic) int ds; // @dynamic ds;
@property(nonatomic) int enableSwipeRight; // @dynamic enableSwipeRight;
@property(nonatomic) long long enterTime; // @dynamic enterTime;
@property(nonatomic) int entranceScene; // @dynamic entranceScene;
@property(nonatomic) int entranceType; // @dynamic entranceType;
@property(nonatomic) int exitType; // @dynamic exitType;
@property(nonatomic) int favCount; // @dynamic favCount;
@property(nonatomic) int importDs; // @dynamic importDs;
@property(nonatomic) int shareFriendCount; // @dynamic shareFriendCount;
@property(nonatomic) int shareSnsCount; // @dynamic shareSnsCount;
@property(retain, nonatomic) NSString *snsId; // @dynamic snsId;
@property(nonatomic) int stayTime; // @dynamic stayTime;
@property(nonatomic) int swipeRightCount; // @dynamic swipeRightCount;
@property(nonatomic) long long timeStamp; // @dynamic timeStamp;
@property(nonatomic) unsigned long long uin; // @dynamic uin;
@property(retain, nonatomic) NSString *uxInfo; // @dynamic uxInfo;

@end

