//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Q2dStatisticData : NSObject
{
    int _tencentHitCount;
    int _worldmapHitCount;
    int _tencentMissCount;
    int _worldmapMissCount;
}

@property(nonatomic) int worldmapMissCount; // @synthesize worldmapMissCount=_worldmapMissCount;
@property(nonatomic) int tencentMissCount; // @synthesize tencentMissCount=_tencentMissCount;
@property(nonatomic) int worldmapHitCount; // @synthesize worldmapHitCount=_worldmapHitCount;
@property(nonatomic) int tencentHitCount; // @synthesize tencentHitCount=_tencentHitCount;
- (void)reset;
- (id)urlQuery;
- (id)init;

@end

