//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QMapConfig : NSObject
{
    int _sceneId;
    int _serverConfig;
}

@property(nonatomic) int serverConfig; // @synthesize serverConfig=_serverConfig;
@property(nonatomic) int sceneId; // @synthesize sceneId=_sceneId;
- (id)init;

@end

