//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WAAppTaskExitInfo : NSObject
{
    _Bool _isUserCancel;
    NSString *_exitAppID;
    NSString *_referrerAppID;
    NSString *_resData;
}

@property(nonatomic) _Bool isUserCancel; // @synthesize isUserCancel=_isUserCancel;
@property(retain, nonatomic) NSString *resData; // @synthesize resData=_resData;
@property(retain, nonatomic) NSString *referrerAppID; // @synthesize referrerAppID=_referrerAppID;
@property(retain, nonatomic) NSString *exitAppID; // @synthesize exitAppID=_exitAppID;
- (void).cxx_destruct;
- (id)description;

@end

