//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CContact, NSString;

@interface WAAppTaskReferrerInfo : NSObject
{
    NSString *_referrerAppID;
    id _referrerData;
    NSString *_hostUserName;
    CContact *_hostContact;
}

@property(retain, nonatomic) CContact *hostContact; // @synthesize hostContact=_hostContact;
@property(retain, nonatomic) NSString *hostUserName; // @synthesize hostUserName=_hostUserName;
@property(retain, nonatomic) id referrerData; // @synthesize referrerData=_referrerData;
@property(retain, nonatomic) NSString *referrerAppID; // @synthesize referrerAppID=_referrerAppID;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isValid;

@end

