//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSContextPluginBase.h"

#import "IMusicPlayerExt.h"
#import "IPluginOperateMusicExt.h"
#import "IRemoteControlMusicPlayerExt.h"

@class NSString;

@interface WAJSContextPlugin_operateMusic : WAJSContextPluginBase <IMusicPlayerExt, IPluginOperateMusicExt, IRemoteControlMusicPlayerExt>
{
    int _musicState;
    _Bool _tapWebView;
    id <IPluginOperateMusicExt> _operateDelegate;
}

@property(nonatomic) __weak id <IPluginOperateMusicExt> operateDelegate; // @synthesize operateDelegate=_operateDelegate;
@property(nonatomic) _Bool tapWebView; // @synthesize tapWebView=_tapWebView;
- (void).cxx_destruct;
- (id)getMusicId:(id)arg1;
- (void)iRemoteControlCheckShouldPrevTrack;
- (void)iRemoteControlCheckShouldNextTrack;
- (void)onMusicPlayFinish:(id)arg1;
- (void)onMusicStopError:(id)arg1;
- (void)onMusicPlayStatusChanged;
- (_Bool)handleEvent:(long long)arg1 userInfo:(id)arg2;
- (void)seekPlay:(float)arg1;
- (void)stopMusic;
- (void)resumeMusic;
- (void)pauseMusic;
- (_Bool)isPlaying;
- (_Bool)isPlaused;
- (void)dealloc;
- (void)onPlayMusic:(id)arg1;
- (_Bool)isValidMusic:(id)arg1;
- (void)playMusic:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

