//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "LocationRetrieveDelegate.h"

@class LocationRetriever, NSString;

@interface WALocationGetter : MMObject <LocationRetrieveDelegate>
{
    _Bool _retrivingLocation;
    id <WALocationGetterDelegate> _delegate;
    LocationRetriever *_locationRetriever;
}

+ (_Bool)isUserDenyToLocationService;
+ (_Bool)isLocationServiceValidWithoutChallenge;
@property(retain, nonatomic) LocationRetriever *locationRetriever; // @synthesize locationRetriever=_locationRetriever;
@property(nonatomic) __weak id <WALocationGetterDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool retrivingLocation; // @synthesize retrivingLocation=_retrivingLocation;
- (void).cxx_destruct;
- (void)onRetrieveLocationOK:(id)arg1;
- (void)onRetrieveLocationTimeOut:(id)arg1;
- (void)onRetrieveLocationError:(int)arg1;
- (void)cancelGetLocation;
- (void)startGetLocationWithAuthorizedChallenge:(_Bool)arg1 busType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

