//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSArray, NSString;

@interface WANearByInfo : MMObject
{
    unsigned int _nearByAppH5LifeSpan;
    unsigned int _appCount;
    unsigned int _startTime;
    NSString *_nearByAppH5String;
    NSString *_listId;
    NSArray *_previewItems;
}

@property(nonatomic) unsigned int startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSArray *previewItems; // @synthesize previewItems=_previewItems;
@property(copy, nonatomic) NSString *listId; // @synthesize listId=_listId;
@property(nonatomic) unsigned int appCount; // @synthesize appCount=_appCount;
@property(nonatomic) unsigned int nearByAppH5LifeSpan; // @synthesize nearByAppH5LifeSpan=_nearByAppH5LifeSpan;
@property(copy, nonatomic) NSString *nearByAppH5String; // @synthesize nearByAppH5String=_nearByAppH5String;
- (void).cxx_destruct;

@end

