//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIScrollViewDelegate.h"
#import "WASearchActionDelegate.h"

@class MMUIViewController, NSDictionary, NSString, WASearchResultLogic;

@interface WASearchFromGlobalProxy : NSObject <WASearchActionDelegate, UIScrollViewDelegate>
{
    NSDictionary *_initParams;
    MMUIViewController *_containerController;
    int _webviewCount;
    _Bool _webViewDidRegisterScrollNotify;
    double _webViewScrollNotifyDiffHeight;
    double _lastOffsetY;
    id <WASearchFromGlobalProxyDelegate> _delegate;
    WASearchResultLogic *_searchResultLogic;
}

@property(retain, nonatomic) WASearchResultLogic *searchResultLogic; // @synthesize searchResultLogic=_searchResultLogic;
@property(nonatomic) __weak id <WASearchFromGlobalProxyDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onLaunchDetailPage:(id)arg1;
- (void)onRegisterWebViewDidScroll:(id)arg1;
- (void)onOpenWAServiceComponent:(id)arg1;
- (void)onSearchInputChanged:(id)arg1;
- (void)onReportWeAppSearchRealTime:(id)arg1;
- (void)onOpenWeAppPage:(id)arg1;
- (void)sendSearchJSEvent:(id)arg1;
- (void)safeSendQueryChangedJSEvent:(id)arg1;
- (void)beginSearch;
- (void)initView;
- (void)initResultLogic;
- (void)prepareWebSearch;
- (_Bool)hasValidWebView;
- (void)didPopToView:(id)arg1;
- (void)stopResultView;
- (void)dealloc;
- (id)initWithViewController:(id)arg1 params:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

