//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAWebViewPlugin_embedView.h"

#import "ForwardMessageLogicDelegate.h"
#import "PBMessageObserverDelegate.h"

@class ForwardMessageLogicController, NSData, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;

@interface WAWebViewPlugin_WeAppMsg : WAWebViewPlugin_embedView <ForwardMessageLogicDelegate, PBMessageObserverDelegate>
{
    struct CGPoint _ptOffset;
    _Bool _offsetChanged;
    NSMutableDictionary *_shareKeys;
    NSMutableArray *_reportArray;
    _Bool _firstShare;
    int _cardType;
    id <IWAWebViewPluginDelegate> _resultDelegate;
    NSData *_thumbData;
    NSMutableDictionary *_customData;
    ForwardMessageLogicController *_forwardLogic;
    NSMutableDictionary *_scrollOffset;
    ForwardMessageLogicController *_shareController;
    NSDictionary *_shareParam;
}

@property(retain, nonatomic) NSDictionary *shareParam; // @synthesize shareParam=_shareParam;
@property(nonatomic) __weak ForwardMessageLogicController *shareController; // @synthesize shareController=_shareController;
@property(retain, nonatomic) NSMutableDictionary *scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(retain, nonatomic) ForwardMessageLogicController *forwardLogic; // @synthesize forwardLogic=_forwardLogic;
@property(retain, nonatomic) NSMutableDictionary *customData; // @synthesize customData=_customData;
@property(nonatomic) int cardType; // @synthesize cardType=_cardType;
@property(nonatomic) _Bool firstShare; // @synthesize firstShare=_firstShare;
@property(retain, nonatomic) NSData *thumbData; // @synthesize thumbData=_thumbData;
@property(nonatomic) __weak id <IWAWebViewPluginDelegate> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
- (void).cxx_destruct;
- (void)takeSnapShot;
- (void)restoreScrollOffsets:(id)arg1;
- (void)resetScrollOffsets:(id)arg1;
- (void)saveScrollOffsets:(id)arg1;
- (void)saveRestoreWebViewScroll:(_Bool)arg1;
- (void)OnForwardWeAppMessageSend:(id)arg1 appMsgItem:(id)arg2;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (id)getCurrentViewController;
- (void)OnForwardMessageSelectSession:(id)arg1;
- (void)OnForwardMessageException:(id)arg1;
- (void)OnForwardMessageCancel:(id)arg1;
- (void)OnForwardMessageSend:(id)arg1;
- (id)pluginReportPageEvent;
- (void)shareToFriend:(int)arg1 appInfo:(id)arg2;
- (void)onCustomWeAppMessage:(id)arg1;
- (void)getWeAppMessage:(int)arg1 customData:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

