//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayOrderDetailTinyAppInfo : NSObject
{
    NSString *_tinyAppName;
    NSString *_tinyAppLogo;
    NSString *_tinyAppDesc;
    NSString *_tinyAppUserName;
    NSString *_tinyAppPath;
}

@property(retain, nonatomic) NSString *tinyAppPath; // @synthesize tinyAppPath=_tinyAppPath;
@property(retain, nonatomic) NSString *tinyAppUserName; // @synthesize tinyAppUserName=_tinyAppUserName;
@property(retain, nonatomic) NSString *tinyAppDesc; // @synthesize tinyAppDesc=_tinyAppDesc;
@property(retain, nonatomic) NSString *tinyAppLogo; // @synthesize tinyAppLogo=_tinyAppLogo;
@property(retain, nonatomic) NSString *tinyAppName; // @synthesize tinyAppName=_tinyAppName;
- (void).cxx_destruct;

@end

