//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LocalAreaNetworkClientDelegate.h"
#import "LocalAreaPeerClientDelegate.h"

@class LocalAreaNetworkClient, LocalAreaPeerClient, NSData, NSString;

@interface WXGLocalAreaCommunicationClient : NSObject <LocalAreaNetworkClientDelegate, LocalAreaPeerClientDelegate>
{
    LocalAreaPeerClient *m_peerClient;
    LocalAreaNetworkClient *m_networkClient;
    unsigned long long m_transferType;
    NSData *m_firstPacketData;
    _Bool _tryPeer;
    unsigned short _server_port;
    id <LocalAreaCommunicationClientDelegate> _delegate;
    NSString *_server_ip;
    NSString *_server_id;
    NSString *_server_hello;
    NSString *_server_ok;
    NSString *_wifiName;
}

@property(retain, nonatomic) NSString *wifiName; // @synthesize wifiName=_wifiName;
@property(nonatomic) _Bool tryPeer; // @synthesize tryPeer=_tryPeer;
@property(retain, nonatomic) NSString *server_ok; // @synthesize server_ok=_server_ok;
@property(retain, nonatomic) NSString *server_hello; // @synthesize server_hello=_server_hello;
@property(retain, nonatomic) NSString *server_id; // @synthesize server_id=_server_id;
@property(nonatomic) unsigned short server_port; // @synthesize server_port=_server_port;
@property(retain, nonatomic) NSString *server_ip; // @synthesize server_ip=_server_ip;
@property(nonatomic) __weak id <LocalAreaCommunicationClientDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned long long)getClientOpenTime;
- (unsigned long long)getTotalReceiveLength;
- (unsigned long long)getTotalSendLength;
- (float)getClientSendSpeed;
- (float)getClientReceiveSpeed;
- (void)onPeerConnected;
- (void)onPeerConnectFailed;
- (void)onPeerDisconnect;
- (void)onPeerReciveData:(id)arg1;
- (void)onNetworkConnectFailWithFirstPacketData:(id)arg1;
- (void)onNetworkDisconnect;
- (void)onNetworkReciveData:(id)arg1 andLength:(unsigned int)arg2;
- (void)p_tryPeer;
- (void)p_stopPeerClient;
- (void)p_stopNetworkClient;
- (void)clientDisconnect;
- (unsigned long long)clientSendData:(id)arg1 andLength:(unsigned int)arg2;
- (id)initWithServerIP:(id)arg1 serverPort:(unsigned short)arg2 serverID:(id)arg3 serverHello:(id)arg4 serverOk:(id)arg5;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

