//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FaceProHandle : NSObject
{
    struct FacePro *mFacePro;
    struct mutex mtx;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)fixOrientation:(id)arg1;
- (id)screenshotOfVideoStream:(struct __CVBuffer *)arg1;
- (basic_string_a490aa4c)engineGetReadNumbers;
- (basic_string_a490aa4c)engineGetData;
- (int)engineRelease;
- (basic_string_a490aa4c)engineVersion;
- (vector_3203cf93)engineGetAllMotion;
- (int)engineGetCurrMotion;
- (basic_string_a490aa4c)engineGetCurrMotionData;
- (int)engineReleaseCurrMotion;
- (int)engineNextMotion;
- (void)engineSetVoiceData:(char *)arg1 withSize:(int)arg2;
- (void)engineGroupChange;
- (void)engineStartRecord;
- (int)engineFaceProcess:(struct opaqueCMSampleBuffer *)arg1;
- (id)initWithConfig:(id)arg1 bioId:(id)arg2;
- (id)init;

@end

