//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchBarDisplayController.h"

#import "AppDetailDelegate.h"
#import "BadRoomLogicControllerDelegate.h"
#import "BannerToastExt.h"
#import "ChatBackgroundExt.h"
#import "ChatViewModelDelegate.h"
#import "FirstUnReadTipViewDelegate.h"
#import "IMsgExt.h"
#import "IMsgRevokeExt.h"
#import "IVOIPExt.h"
#import "IVOIPUILogicMgrExt.h"
#import "IdleTimerUtilExt.h"
#import "MMInputToolViewDelegate.h"
#import "MMMultiSelectToolViewDelegate.h"
#import "MMReadMailViewDelegate.h"
#import "MMScrollActionSheetDelegate.h"
#import "MessageNodeViewDelegate.h"
#import "MessageObserverDelegate.h"
#import "MsgDelegate.h"
#import "MsgImgFullScreenViewControllerDelegate.h"
#import "MsgImgFullScreenWindowDelegate.h"
#import "MsgSearchHelperDelegate.h"
#import "MultiSelectContactsViewControllerDelegate.h"
#import "ShareMessageConfirmLogicHelperDelegate.h"
#import "StreamVoiceInputViewControllerDelegate.h"
#import "TipsViewDelegate.h"
#import "TrackRoomTipsViewDelegate.h"
#import "TypingControllerDelgate.h"
#import "WCActionSheet.h"
#import "WCCanvasPageViewControllerDelegate.h"
#import "WCNetworkMediaPlayerDelegate.h"
#import "contactInfoDelegate.h"
#import "tableViewDelegate.h"
#import "BaseMsgContentDelgate.h"
#import "BaseMsgContentInBackgroundThreadDelgate.h"

@class BadRoomLogicController, BaseChatViewModel, CMessageWrap, FirstUnReadTipView, MMInputToolView, MMLoadingView, MMMultiSelectToolView, MMScrollActionSheet, MMTableView, MMTimer, MMUIWindow, MsgImgFullScreenWindow, MsgSearchHelper, MultiTalkTipsView, NSMutableArray, NSString, ShareMessageConfirmLogicHelper, StreamVoiceInputViewController, TipsView, TrackRoomTipsView, UIActivityIndicatorView, UIBarButtonItem, UIImageView, UIView;

/**
 聊天对话页面视图控制器
 */
@interface BaseMsgContentViewController : MMSearchBarDisplayController <MsgSearchHelperDelegate, MsgImgFullScreenWindowDelegate, BannerToastExt, IdleTimerUtilExt, BadRoomLogicControllerDelegate, MsgImgFullScreenViewControllerDelegate, WCCanvasPageViewControllerDelegate, ChatBackgroundExt, UIViewControllerPreviewingDelegate, StreamVoiceInputViewControllerDelegate, UITableViewDelegate, UITableViewDataSource, WCActionSheetDelegate, UIAlertViewDelegate, UINavigationControllerDelegate, UIDocumentInteractionControllerDelegate, tableViewDelegate, TypingControllerDelgate, MessageNodeViewDelegate, ChatViewModelDelegate, contactInfoDelegate, MsgDelegate, MMInputToolViewDelegate, ShareMessageConfirmLogicHelperDelegate, MMReadMailViewDelegate, IVOIPExt, AppDetailDelegate, TipsViewDelegate, TrackRoomTipsViewDelegate, IMsgExt, IMsgRevokeExt, IVOIPUILogicMgrExt, MMMultiSelectToolViewDelegate, MultiSelectContactsViewControllerDelegate, MMScrollActionSheetDelegate, MessageObserverDelegate, FirstUnReadTipViewDelegate, WCNetworkMediaPlayerDelegate>
{
    NSMutableArray *m_arrMessageNodeData;
    unsigned int m_uLastTime;
    unsigned int m_uLastMoreMsgTime;
    BOOL m_bKeyboardShow;
    BOOL m_bToolViewHidden;
    NSUInteger m_moreMsgIndex;
    BOOL m_bReadtToLoadMoreMsg;
    id <BaseMsgContentDelgate> m_delegate;
    id <BaseMsgContentInBackgroundThreadDelgate> m_backgroundThreadDelegate;
    Class m_delegateClass;
    MMTimer *m_LockerTimer;
    MMTableView *m_tableView;
    UIActivityIndicatorView *m_activityView;
    UIView *m_headerView;
    MMInputToolView *_inputToolView;
    UIView *m_backgroundView;
    NSMutableArray *m_arrDeleteRows;
    UIView *m_deleteContainView;
    BOOL m_bViewDidAppear;
    TrackRoomTipsView *m_trackTipsView;
    MultiTalkTipsView *m_multiTalkTipsView;
    BOOL m_bViewUnloaded;
    struct CGPoint m_pTableViewOffset;
    NSInteger m_keyboardHeight;
    NSString *m_text;
    int m_inputMode;
    int m_positionMode;
    int m_contentMode;
    CGFloat m_fKeyboardAnimationDuration;
    MsgSearchHelper *m_oMsgSearchHelper;
    int m_iInitTableViewContentOffset;
    BOOL m_bNeedAdjustTableViewContentOffset;
    unsigned int m_uiSearchResultNodeViewHeight;
    NSInteger m_uiInterfaceOrientation;
    MMLoadingView *m_loadingView;
    ShareMessageConfirmLogicHelper *_shareMessageConfirmLogicHelper;
    MMMultiSelectToolView *_multiSelectView;
    NSMutableArray *m_arrSelectMsgLocalID;
    UIView *m_msgReceivingTipsView;
    unsigned int m_uiSelectSearchMsgID;
    TipsView *m_chatAddFriend;
    TipsView *m_recommandFriend;
    TipsView *m_securityBanner;
    BOOL m_bChatAddFriendShow;
    BOOL m_bSecurityBannerShow;
    BOOL m_bShouldShowKeyboardAnimation;
    BOOL m_bNeedToUpdateTitle;
    BOOL m_bIsRevokeAdding;
    int m_msgCounerDurOneSync;
    BOOL m_bHightlightedSearchedMsgNode;
    struct CGPoint m_decelerateTarget;
    CMessageWrap *m_firstUnReadMsg;
    FirstUnReadTipView *m_jumpFirstUnReadBtn;
    NSUInteger m_unreadCount;
    MMScrollActionSheet *m_scrollActionSheet;
    MMUIWindow *m_fullScreenWindow;
    BaseChatViewModel *m_fullScreenNodeData;
    UIBarButtonItem *m_voiceStreamCacheLeftBtnItem;
    UIBarButtonItem *m_voiceStreamCacheRightBtnItem;
    BOOL m_isMsgReceiveTipsJacking;
    unsigned int m_openTrackScene;
    struct timeval m_menuHideTime;
    BOOL m_shouldScrollToBottomAfterRotate;
    BOOL m_resignInputToolViewFirstResponder;
    BOOL m_textFloatPreviewHiding;
    BOOL m_scrollingTableToBottom;
    struct _NSRange m_scrollingInvisibleRange;
    BOOL m_needLayoutOnMenuHide;
    BOOL m_needScrollOnMenuHide;
    NSUInteger m_lastSectionCount;
    BOOL m_scrollingToFirstUnRead;
    CMessageWrap *m_lastMsgInNewArray;
    UIView *m_footerView;
    UIActivityIndicatorView *m_footerActivityView;
    BOOL m_needLoadMoreWhenScrollToFistUnRead;
    BOOL m_needHideFirstUnReadBtn;
    BOOL m_bMovingToMainFrameTab;
    CGFloat m_bannerHeight;
    BOOL m_isPeekPreview;
    MsgImgFullScreenWindow *m_imgFullScreenWnd;
    UIView *m_snapshotView;
    unsigned int m_uiEnterRoomTime;
    unsigned int m_uiEnterRoomUnreadCount;
    BOOL m_bCloseForViewDetail;
    UIImageView *m_showNewView;
    unsigned int _startTime;
    id <UIViewControllerPreviewing> _previewingContext;
    StreamVoiceInputViewController *m_streamVoiceInputViewController;
    int m_searchScene;
    NSMutableArray *m_shareContacts;
}

@property(strong, nonatomic) BadRoomLogicController *m_badRoomLogicController;
@property(nonatomic) BOOL m_bIsInMainFrame;
@property(nonatomic) int m_searchScene; // @synthesize m_searchScene;
@property(strong, nonatomic) NSMutableArray *m_shareContacts; // @synthesize m_shareContacts;
@property(strong, nonatomic) UIView *m_msgReceivingTipsView; // @synthesize m_msgReceivingTipsView;
@property(strong, nonatomic) MMTimer *m_LockerTimer; // @synthesize m_LockerTimer;
@property(strong, nonatomic) MMInputToolView *toolView; // @synthesize toolView=_inputToolView;
@property(nonatomic, weak) id <BaseMsgContentInBackgroundThreadDelgate> m_backgroundThreadDelegate; // @synthesize m_backgroundThreadDelegate;
@property(nonatomic, weak) id <BaseMsgContentDelgate> m_delegate; // @synthesize m_delegate;

#pragma mark - IUiUtilExt
- (void)onTopBarFrameChanged;

#pragma mark - BaseMsgContentDelgate
- (id)GetContact;
- (id)getLeftBarButton;
- (void)onLoadDownMoreMessage:(id)arg1;
- (BOOL)isChatStatusNotifyOpen;

- (void)initView;
- (void)initSearchBar;
- (void)initMultiSelectToolView;
- (void)initToolView;
- (void)initToolEmoticonView;
- (void)initTableView;
- (void)initTableHeaderView;
- (void)initNavigationView;
- (void)initData;

#pragma mark - loading
- (void)loadingAfterForwardMessageOK;
- (void)stopLoadingAndAndShowErrorWithText:(id)arg1;
- (void)stopLoadingAndShowOkWithText:(id)arg1;
- (void)showLoadingViewWithText:(id)arg1;
- (void)showLoadingView;

#pragma mark - tap
- (void)tapAppNodeView:(id)arg1;
- (void)tapFriendCard_NodeView:(id)arg1 WithContact:(id)arg2 WithMsg:(id)arg3;
- (void)tapPushMail_NodeView:(id)arg1 withPushMailWrap:(id)arg2;
- (void)tapWeAppImage_NodeView:(id)arg1;
- (void)tapImage_NodeView:(id)arg1;
- (void)tapLocation_NodeView:(id)arg1;
- (void)tapVideoStatus_NodeView:(id)arg1 DownloadMode:(NSUInteger)arg2;
- (void)tapVideoStatus_NodeView:(id)arg1;
- (void)tapStatus_NodeView:(id)arg1;

- (void)showSightDraftBoxView;
- (void)showAttachmentView;
- (void)traitCollectionDidChange:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(CGPoint)location;
- (BOOL)isPeekPreview;
- (void)setIsPeekPreview:(BOOL)arg1;
- (CGRect)getVisibleRectInScreen:(id)arg1;
- (CGRect)getInnerVisibleRectInScreen:(CGRect)screenBounds;
- (NSInteger)getMessageNodePosition:(id)arg1;
- (void)onSYncEnd;
- (void)showReceiveMsgTips;
- (void)stopReceiveMsg;
- (void)startReceiveMsgWithTips:(id)arg1;
- (CGFloat)getInvisibleHeight;
- (BOOL)isContactSizeOverScreen;
- (void)endSearchAndDisplay;
- (void)ShowMultiSelectMoreOperation:(id)arg1;
- (void)showAlertTooMany;
- (void)didRotateFromInterfaceOrientation:(NSInteger)arg1;
- (void)rotate:(NSInteger)arg1 duration:(CGFloat)arg2;
- (void)hideMultiTalkTips;
- (void)hideTrackRoomTips;
- (void)showMultiTalkTips;
- (void)showTrackRoomTips;
- (void)updateBanner;
- (BOOL)shouldHideOrginInputToolView;
- (CGFloat)getCustomizedAreaWidth;
- (void)updateChatRoomData:(id)arg1;
- (BOOL)isAllowWxTalk;
- (BOOL)isAllowVoiceInput;
- (BOOL)isAllowVoip;
- (void)PreviewAppNode:(id)arg1 MsgWrap:(id)arg2 Pop:(BOOL)arg3;
- (void)updateToolViewOrigin;
- (void)adjustDeleteViewRect;
- (void)hideToolViewAnimated:(BOOL)arg1;
- (void)onDeleteAllMsg;
- (void)ReloadView;
- (void)Reset;
- (void)resetToolView;
- (void)MenuControllerWillHide:(id)arg1;
- (void)MenuControllerWillShow:(id)arg1;
- (void)lockerTimesup;
- (void)beginLockerTimer;
- (void)stopLockerTimesup;
- (id)getLastContentMessageNodeFromArray:(id)arg1;
- (id)getFirstContentMessageNodeFromArray:(id)arg1;
- (void)scrollToFirstUnReadMessage:(id)arg1;
- (NSUInteger)getFirstUnReadMessageIndex;
- (NSUInteger)getFirstUnReadSplitNodeIndex;
- (void)onScrollToFirstUnReadMsg;
- (void)tryAddUnReadSplitNode;
- (void)updateFirstUnReadButtonOnShowBanner:(CGFloat)arg1;
- (void)animateHideFirstUnReadButton;
- (void)animateShowFirstUnReadButton;
- (void)tryShowFirstUnReadButtonAnimated;
- (void)onTrySHowFirstUnReadButton;
- (CGFloat)getTableViewVisibleHeightWithOrientation:(NSInteger)arg1;
- (void)removeVoipAndPhoneTip;
- (void)removeVoiceTip;
- (void)tryMoveToMainFrame;
- (void)onViewDisappear;
- (void)statEnterMsgChat;
- (void)didExitRoom;
- (void)willEnterRoom;
- (void)trySetInputToolviewFirstResponder;
- (void)fixInputToolViewKeyboard;
- (void)SetVoiceEnabled:(BOOL)arg1;
- (void)updateMessageNodeStatus:(id)arg1;
- (void)onDeleteMessage:(id)arg1;
- (void)handleDeleteAllMessage;
- (void)deleteAllMessage;
- (void)handleAfterDeleteAllMessage;
- (void)onHideMultiSelectView;
- (void)onFinishMultiSelect:(id)arg1;

- (void)onReturn:(id)arg1;
- (void)onEditMessage:(id)arg1;
- (void)updateDeleteCount;
- (void)sendShortVideoMsgWithAsset:(id)arg1;
- (void)sendShortVideoMsg:(id)arg1 thumbImg:(id)arg2 statInfo:(id)arg3;
- (void)editStreamVoiceTxtDone;
- (void)editStreamVoiceTxtReturn;
- (void)doJoinExistMultiTalk;
- (void)reloadMessagesInternal;
- (void)updateTableContentOffsetAnimated:(BOOL)animated OffsetDelta:(CGFloat)offset;
- (void)scrollTableToBottomAnimated:(BOOL)animated init:(BOOL)shouldInit;
- (void)updateTableLayoutAnimateDuration:(CGFloat)arg1 Orientation:(NSInteger)arg2;
- (void)AsyncSendMessage:(id)arg1;
- (void)onTouchDown;
- (void)onPan:(id)arg1;
- (id)indexPathForCellKey:(id)arg1;
- (void)makeCell:(id)arg1 indexPath:(NSIndexPath *)indexPath;

- (void)adjustTableViewOffset;
- (void)reloadBackgroundView;
- (void)resetMsgSearchHelper;
- (void)initMsgSearchHelper:(int)arg1;
- (CGFloat)getSearchBarHeight;
- (BOOL)showTrackExitAlert;
- (void)onBackButtonClicked:(id)arg1;

- (void)updateRightBar;
- (id)getRightBarButton;
- (void)openHomePage:(id)arg1;
- (void)openVoiceCall;
- (void)openVideoCall;
- (id)getVoipBarButton;
- (id)getHomePageBarButton;

- (void)reloadTableHeaderView:(BOOL)arg1;
- (void)startVoiceAnimatingAtNodeId:(unsigned int)arg1;

- (void)updateOpBtnState:(BOOL)arg1;
- (void)MoreMsgBtnUpdate:(unsigned int)arg1 unReadCount:(unsigned int)arg2;

- (void)onSightTipsOK;
- (void)setTableFooterView:(BOOL)arg1;
- (void)initHistroyMessageNodeData;
- (void)addMessageNode:(CMessageWrap *)msgWrap layout:(BOOL)layout addMoreMsg:(BOOL)moreMsg;
- (id)addSplitNode:(id)arg1 addMoreMsg:(BOOL)arg2;
- (void)addTimeNode:(id)arg1 layout:(BOOL)arg2 addMoreMsg:(BOOL)arg3;
- (id)getMessageChatContactByMessageWrap:(id)arg1;
- (BOOL)isShowHeadImage:(id)arg1;
- (void)showAlertWithTitle:(id)arg1;
- (void)jumpToUserProfile:(id)arg1 Displayname:(id)arg2 Scence:(unsigned int)arg3 fromBanner:(BOOL)arg4;
- (id)getLastSentMsg;
- (CGRect)getNodeRectInScreen:(unsigned int)arg1;
- (id)GetMessageNodeDataArray;
- (id)GetMessagesWrapArray;
- (void)ShowVolumeTips;
- (void)ShowEarTips;
- (void)ShowEarBackTips;
- (void)StopPlayingNodeView:(unsigned int)arg1;
- (void)StartPlayingNodeView:(unsigned int)arg1;
- (void)EndPlaying:(id)arg1;
- (void)OnEndPlaying:(id)arg1;
- (void)showPlayVoiceTipsIfNeed;
- (void)BeginPlaying:(id)arg1 FromTouch:(BOOL)arg2;
- (void)setSecurityTipShow:(BOOL)arg1;
- (void)setAddFriendTipShow:(BOOL)arg1 contact:(id)arg2;
- (void)showAddFriendTip:(BOOL)arg1;
- (CGFloat)getSecurityBannerTipHeight;
- (CGFloat)getAddFriendTipHeight;
- (CGFloat)getTipsHeight;
- (void)checkShowSecurityBannerTip:(BOOL)arg1;
- (void)checkShowRecommandFriendTip:(BOOL)arg1;
- (void)checkTips:(BOOL)arg1;
- (void)jumpToDetail:(id)arg1;
- (void)JumpToViewStreamVideo:(id)arg1;
- (id)contactShareMsgFromUser:(id)arg1 toUser:(id)arg2 sharedContact:(id)arg3;
- (void)showExposeViewController;
- (void)showEarModeTips;
- (void)readerViewClickedWithMsg:(id)arg1;
- (void)headerImageClickedWithMsg:(id)arg1;
- (void)headerImageClicked:(id)arg1;
- (void)PlayVideo:(id)arg1 soundable:(BOOL)arg2;

- (void)PreviewImage:(id)arg1 soundable:(BOOL)arg2 snapshotView:(id)arg3;
- (void)PreviewImage:(id)arg1;
- (void)unHighLightSelectSearchCell;
- (void)highLightSelectSearchCell;
- (void)locateToMsg:(id)arg1;
- (void)deleteNode:(id)arg1 withDB:(BOOL)arg2 animated:(BOOL)arg3;
- (void)openChatInfo:(id)arg1;
- (void)tryScrollToBottomAnimated:(BOOL)arg1;
- (BOOL)isScrollToBottom;
- (void)ScrollToBottomAnimated:(BOOL)arg1;
- (void)ScrollToBottomAnimatedAndLoadMoreNode;
- (id)getNavigationButton:(id)arg1;
- (void)updateTitleView:(id)arg1;
- (id)getTitleLableViewWithMaxWidth:(CGFloat)arg1 title:(id)arg2;
- (void)locateTableViewWithLocalID:(unsigned int)arg1;
- (NSUInteger)getMsgContentSizeHeight:(unsigned int)arg1;
- (NSUInteger)getCurContentSizeHeight;
- (NSUInteger)getLastNodePreContentSizeHeight;
- (id)findNodeViewByLocalId:(unsigned int)arg1;
- (id)findNodeDataByLocalId:(unsigned int)arg1;
- (void)removeObjectsFromMessageNodeDatas:(id)arg1;
- (void)removeAllObjectsFromMessageNodeDatas;
- (NSUInteger)findNodeIndexByLocalId:(unsigned int)arg1;



@end

