//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ForwardMessageLogicDelegate.h"
#import "IOplogExt.h"
#import "WCActionSheet.h"
#import "ContactInfoAssistDelegate.h"

@class DelaySwitchSettingLogic, ForwardMessageLogicController, MMTableViewInfo, WCOpLog;

/**
 通讯录好友-资料设置-视图控制器
 */
@interface ContactSettingViewController : MMUIViewController <WCActionSheetDelegate, ForwardMessageLogicDelegate, IOplogExt>
{
    MMTableViewInfo *m_tableViewInfo;
    CContact *m_contact;
    id <ContactInfoAssistDelegate> m_delegate;
    WCOpLog *_wcOpLog;
    NSString *m_recommandRemark;
    unsigned int m_scene;
    ForwardMessageLogicController *m_forwardLogic;
    DelaySwitchSettingLogic *m_delaySwitchLogic;
    BOOL m_toBeDeleted;
}

@property(retain, nonatomic) NSString *m_recommandRemark; // @synthesize m_recommandRemark;

/**
 构造函数

 @param contact 联系对象
 @param scene scene
 @return ContactSettingViewController对象
 */
- (instancetype)initWithContact:(CContact *)contact inScene:(NSUInteger)scene;

/**
 构造函数

 @param contact 联系对象
 @return ContactSettingViewController对象
 */
- (instancetype)initWithContact:(CContact *)contact;

/**
 设置代理对象
 @see ContactInfoAssistDelegate
 @param delegate 代理对象
 */
- (void)setDelegate:(id<ContactInfoAssistDelegate>) delegate;

/**
 重载tableView, 刷新UI显示数据
 */
- (void)reloadTableView;
- (void)opFavour;
- (void)opWCBlacklist:(id)arg1;
- (void)opOutsider:(id)arg1;
- (void)opEditRemarkName;
- (void)opShareMyFriend;

- (void)opDelete:(UIButton *)sender;
- (void)doDelete;
- (void)doDeleteLocal;
- (void)doDeleteAndExpose;

- (void)doExpose:(int)arg1;
- (void)opExpose;

- (void)opBlackList;
- (void)cancelBlackListSwitch;
- (void)doAddToBlackList;
- (void)doAddToBlackListAndExpose;
- (void)addToBlackList;
- (void)removeFromBlackList;
- (BOOL)isShowBlackAction;

- (BOOL)isInMyContactList;



@end

