//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactTagNameEditViewControllerDelegate.h"
#import "IContactLabelMgrExt.h"
#import "MultiSelectContactsViewControllerDelegate.h"

@class ContactTagData, MMTableView, NSMutableArray, NSMutableDictionary, NSString,CContact;

@interface ContactTagNewDetailViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, IContactLabelMgrExt, MultiSelectContactsViewControllerDelegate, ContactTagNameEditViewControllerDelegate, UIAlertViewDelegate>

@property(strong, nonatomic) NSMutableDictionary *contactsDict; // @synthesize contactsDict=_contactsDict;
@property(strong, nonatomic) NSMutableArray *contactsKeyArray; // @synthesize contactsKeyArray=_contactsKeyArray;
@property(strong, nonatomic) NSString *curDisplayTagName; // @synthesize curDisplayTagName=_curDisplayTagName;
@property(nonatomic) BOOL bIsTagNameChange; // @synthesize bIsTagNameChange=_bIsTagNameChange;
@property(nonatomic) BOOL bIsAlreadyDisMissSelf; // @synthesize bIsAlreadyDisMissSelf=_bIsAlreadyDisMissSelf;
@property(nonatomic) NSUInteger curEventID; // @synthesize curEventID=_curEventID;
@property(strong, nonatomic) NSMutableArray<CContact *> *curMemberContactList; // @synthesize curMemberContactList=_curMemberContactList;
@property(strong, nonatomic) ContactTagData *contactTagData; // @synthesize contactTagData=_contactTagData;

/**
 标签详情页面类型:
 1-创建标签,
 2-更新标签
 */
@property(nonatomic) NSInteger curActionType; // @synthesize curActionType=_curActionType;
@property(strong, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int commonSearchScene; // @synthesize commonSearchScene=_commonSearchScene;

- (NSUInteger)updateTagMember;
- (BOOL)isTagNameEmptyOrExist:(id)arg1;
- (NSUInteger)createOrUpdateTagName;
- (void)updateRightBarButtonStatus;
- (void)reloadMemberListAndView:(id)arg1 isChatRoomList:(BOOL)isChatRoomList;
- (void)onSaveBarButtonPress:(id)arg1;
- (void)onDismissBarButtonPress:(id)arg1;
- (void)internalDisMissSelfAnimated:(BOOL)arg1;
- (void)setSaveButtonEnable:(BOOL)arg1;
- (void)onClickContactItemCellWithIndexPath:(id)arg1;
- (void)onClickAddMemberCell;
- (void)onClickTagNameCell;
- (void)makeMemberContactCellContent:(id)arg1 WithIndexPath:(id)arg2;
- (void)makeAddMemberCellContent:(id)arg1;
- (void)makeTagNameCellContent:(id)arg1;
- (void)makeTagDetailEditHeaderContent:(id)arg1;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)handleDeleteContactAtIndexPath:(id)arg1;
- (void)sortTagContactsV2;
- (void)sortTagContacts;
- (id)addContactSectionKey:(id)arg1;
- (void)processContactSectionData:(id)arg1;




@end

