//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactInfoAssistDelegate.h"
#import "ForwardMessageLogicDelegate.h"
#import "ICertInfoMgrExt.h"
#import "IContactMgrExt.h"
#import "IStrangerContactMgrExt.h"
#import "IUpdateProfileMgrExt.h"
#import "MMSayHelloViewControllerDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "VerifyPhoneDelegate.h"
#import "WCFacadeExt.h"
#import "ContactInfoViewControllerDelegate.h"
#import "contactInfoDelegate.h"

@class CBaseContactInfoAssist, CContact, CContactVerifyLogic, CMessageWrap, ForwardMessageLogicController, NSMutableDictionary, NSString;

@interface ContactInfoViewController : MMUIViewController <ForwardMessageLogicDelegate, UIAlertViewDelegate, PBMessageObserverDelegate, ContactInfoAssistDelegate, IContactMgrExt, VerifyPhoneDelegate, MMSayHelloViewControllerDelegate, ICertInfoMgrExt, WCFacadeExt, IStrangerContactMgrExt, IUpdateProfileMgrExt>
{
    unsigned int m_uiVerify;
    CContact *m_contact;
    CContact *m_chatContact;
    id <contactInfoDelegate> m_delegate;
    id <ContactInfoViewControllerDelegate> m_InfoDelegate;
    CBaseContactInfoAssist *m_oContactInfoAssist;
    CContactVerifyLogic *m_contactVerifyLogic;
    NSString *m_nsLocation;
    BOOL m_bPopToRootWhenDelete;
    unsigned int m_uiFromScene;
    int m_wcOperateMode;
    Class m_popToViewControllerClassWhenDelete;
    int m_searchScene;
    id m_userData;
    double m_CurrentWidth;
    ForwardMessageLogicController *m_forwardLogic;
    unsigned int _startTime;
    int m_uiAddFriendStatScene;
}

@property(strong, nonatomic) NSString *reportInfo;
@property(strong, nonatomic) CMessageWrap *sourceMsg;
@property(strong, nonatomic) NSString *searchExtraParamsString;
@property(nonatomic) unsigned int searchFromIndex;
@property(strong, nonatomic) NSString *searchKeyword;
@property(strong, nonatomic) NSString *searchId;
@property(strong, nonatomic) NSMutableDictionary *verifyUserInfoList;
@property(nonatomic) int m_qrCodeAddFriendScene;
@property(nonatomic) int m_uiAddFriendStatScene; // @synthesize m_uiAddFriendStatScene;
@property(strong, nonatomic) id m_userData; // @synthesize m_userData;
@property(nonatomic) int m_searchScene; // @synthesize m_searchScene;
@property(nonatomic) Class m_popToViewControllerClassWhenDelete; // @synthesize m_popToViewControllerClassWhenDelete;
@property(nonatomic) unsigned int m_uiFromScene; // @synthesize m_uiFromScene;
@property(nonatomic) BOOL m_bPopToRootWhenDelete; // @synthesize m_bPopToRootWhenDelete;
@property(strong, nonatomic) NSString *m_nsLocation; // @synthesize m_nsLocation;
@property(nonatomic) unsigned int m_uiVerify; // @synthesize m_uiVerify;
@property(nonatomic, weak) id <ContactInfoViewControllerDelegate> m_InfoDelegate; // @synthesize m_InfoDelegate;
@property(nonatomic, weak) id <contactInfoDelegate> m_delegate; // @synthesize m_delegate;
@property(strong, nonatomic) CContact *m_chatContact; // @synthesize m_chatContact;
@property(strong, nonatomic) CContact *m_contact; // @synthesize m_contact;

- (void)jumpToContentViewController:(id)arg1;
- (void)doReset;
- (BOOL)isQQContact;
- (void)checkNeedForcedUpdateForMemberDetail;
- (void)updateContactFromServer;
- (void)reloadContactAssist;
- (void)reloadView;
- (void)reloadData;
- (void)initSystemPluginData:(int)arg1;
- (BOOL)isInMyContactList;
- (instancetype)initWithTitle:(NSString *)title;
- (void)statBanner;
- (void)confirmExpose:(unsigned int)arg1;
- (BOOL)onFilterSendReceiver:(id)arg1;
- (void)copyContactField:(id)arg1 toContact:(id)arg2;
- (void)onVerifyOKWithContact:(id)arg1;

@end

