//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactTagNameEditViewControllerDelegate.h"
#import "IContactLabelMgrExt.h"
#import "MultiSelectContactsViewControllerDelegate.h"

@class ContactTagData, MMTableView, NSMutableArray, NSMutableDictionary, NSString;

/**
 添加/更新通讯录标签
 */
@interface ContactTagNewDetailViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, IContactLabelMgrExt, MultiSelectContactsViewControllerDelegate, ContactTagNameEditViewControllerDelegate, UIAlertViewDelegate>

@property(strong, nonatomic) NSMutableDictionary *contactsDict;
@property(strong, nonatomic) NSMutableArray *contactsKeyArray;
@property(strong, nonatomic) NSString *curDisplayTagName;
@property(nonatomic) BOOL bIsTagNameChange; // @synthesize bIsTagNameChange=_bIsTagNameChange;
@property(nonatomic) BOOL bIsAlreadyDisMissSelf; // @synthesize bIsAlreadyDisMissSelf=_bIsAlreadyDisMissSelf;
@property(nonatomic) unsigned int curEventID; // @synthesize curEventID=_curEventID;
@property(strong, nonatomic) NSMutableArray *curMemberContactList; // @synthesize curMemberContactList=_curMemberContactList;
@property(strong, nonatomic) ContactTagData *contactTagData; // @synthesize contactTagData=_contactTagData;
@property(nonatomic) long long curActionType; // @synthesize curActionType=_curActionType;
@property(strong, nonatomic) MMTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) int commonSearchScene; // @synthesize commonSearchScene=_commonSearchScene;

- (void)setContactLabel:(id)arg1 withRetCode:(int)arg2 andEventId:(unsigned int)arg3;
- (void)onAddContactLabel:(id)arg1 withRetCode:(int)arg2 andEventId:(unsigned int)arg3;
- (void)updateContactLabelName:(id)arg1 withRetCode:(int)arg2 andEventId:(unsigned int)arg3;
- (unsigned int)updateTagMember;
- (BOOL)isTagNameEmptyOrExist:(id)arg1;
- (unsigned int)createOrUpdateTagName;
- (void)updateRightBarButtonStatus;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onTagNameEditViewControllerRetWithTagName:(id)arg1;
- (void)reloadMemberListAndView:(id)arg1 isChatRoomList:(BOOL)arg2;
- (void)onMultiSelectContactReturn:(id)arg1;
- (void)onSaveBarButtonPress:(id)arg1;
- (void)onDismissBarButtonPress:(id)arg1;
- (void)internalDisMissSelfAnimated:(BOOL)arg1;
- (void)setSaveButtonEnable:(BOOL)arg1;
- (void)onClickContactItemCellWithIndexPath:(id)arg1;
- (void)onClickAddMemberCell;
- (void)onClickTagNameCell;
- (void)makeMemberContactCellContent:(id)arg1 WithIndexPath:(id)arg2;
- (void)makeAddMemberCellContent:(id)arg1;
- (void)makeTagNameCellContent:(id)arg1;
- (void)makeTagDetailEditHeaderContent:(id)arg1;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)handleDeleteContactAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (BOOL)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)sortTagContactsV2;
- (void)sortTagContacts;
- (id)addContactSectionKey:(id)arg1;
- (void)processContactSectionData:(id)arg1;
- (void)initView;
- (void)reloadData;
- (void)initData;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initViewControllerWithCreateNewTag;
- (id)initViewControllerWithContactTagData:(id)arg1;
- (id)init;
- (void)dealloc;

@end

