//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "FaceRecogNumbersViewDelegate.h"

@class AnimationStatusView, FaceRecogNumbersView, FaceRecogRectView, MMUILabel, NSString, UIButton, UIImageView, UIView;

@interface FaceRecogVerifyViewController : MMUIViewController <FaceRecogNumbersViewDelegate>
{
    UIView *_prepareView;
    AnimationStatusView *_waitView;
    UIImageView *_faceIcon;
    UIView *_previewView;
    UIButton *_cancelButton;
    UIButton *_closeButton;
    UIButton *_retryButton;
    FaceRecogRectView *_faceRectView;
    UIView *_faceRectBackView;
    UIView *_faceGradientView;
    FaceRecogNumbersView *_numberView;
    MMUILabel *_bigTipFaceTitle;
    MMUILabel *_errTip;
    UIImageView *_loadingBlurView;
    _Bool _finished;
    id <FaceRecogVerifyViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FaceRecogVerifyViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)numberViewDidEndAnimation;
- (void)numberViewDidBeginAnimation;
- (void)retryButtonDone;
- (void)closeButtonDone;
- (void)cancelButtonDone;
- (void)procedureDidFailed:(id)arg1 canRetry:(_Bool)arg2;
- (void)procedureDidFinish;
- (void)procedureDidStartRecogning;
- (void)showPrepareView;
- (void)procedureDidStartReadNumber:(id)arg1 Time:(double)arg2;
- (void)procedureDidStartDetectFace;
- (void)procedureDidGotFrameResult:(id)arg1 currentMotionType:(unsigned long long)arg2;
- (void)attachPreviewLayer:(id)arg1;
- (void)initCancelBtn;
- (void)initNumberView;
- (void)initFaceRectView;
- (void)initPrepareView:(id)arg1 tip:(id)arg2;
- (void)initErrorMsg:(id)arg1;
- (void)initBitTipTitle:(id)arg1;
- (void)initView;
- (void)resetViews;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewDidBeDismissed:(_Bool)arg1;
- (void)viewWillBePresented:(_Bool)arg1;
- (void)viewDidLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

