//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"
#import "PBMessageObserverDelegate.h"
#import "MMSayHelloViewControllerDelegate.h"

@class CContact, NSString, UITextField;

@interface MMSayHelloViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, PBMessageObserverDelegate, UIAlertViewDelegate>
{
    UITextField *m_sayHelloTextView;
    NSString *m_helloContent;
    CContact *m_helloReceiver;
    unsigned int m_eventID;
    id <MMSayHelloViewControllerDelegate> m_delegate;
}

@property(nonatomic, weak) id <MMSayHelloViewControllerDelegate> delegate; // @synthesize delegate=m_delegate;
@property(strong, nonatomic) CContact *helloReceiver; // @synthesize helloReceiver=m_helloReceiver;
@property(strong, nonatomic) NSString *helloContent; // @synthesize helloContent=m_helloContent;
@property(strong, nonatomic) UITextField *sayHelloTextView; // @synthesize sayHelloTextView=m_sayHelloTextView;

- (void)quitSayHello;
- (void)updateWordCount:(id)arg1;
- (void)onCancelSendSayHello;
- (void)onSendSayHello:(id)arg1;
- (NSString *)filterString:(NSString *)content;
- (BOOL)doSayHello:(id)arg1;


@end

