//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IUiUtilExt.h"
#import "MMUIViewControllerDelegate.h"

@class MMDelegateProxy<UIGestureRecognizerDelegate>, MMLoadingView, MMTitleView, MMUINavigationBar, NSMutableArray, NSMutableDictionary, NSString, UIBarButtonItem, UIColor, UILabel, UINavigationController, UIResponder, UIView;

@interface MMUIViewController : UIViewController <IUiUtilExt, MMUIViewControllerDelegate, UIGestureRecognizerDelegate>
{
    BOOL m_isPopByClickingURL;
    MMLoadingView *m_loadingViewX;
    unsigned int m_uiVcType;
    BOOL m_bKeyboardShowForGesture;
    UILabel *m_newsTitleRecordLabel;
    NSMutableArray *m_fullScreenViews;
    BOOL m_bAnimated;
    BOOL m_bIsBeingPoped;
    BOOL m_bInteractivePopEnabled;
    BOOL m_bDisableAdjustInsetAndOffset;
    double lastScreenWidth;
    UINavigationController *m_navigationController;
    MMTitleView *m_baseTitleView;
    NSMutableDictionary *m_dicDeepLink;
    NSMutableDictionary *m_dicContentInsetAutolayout;
    NSMutableDictionary *m_dicTopOffsetAutolayout;
    NSMutableArray *m_arrEndUserOpInfo;
    MMDelegateProxy<UIGestureRecognizerDelegate> *m_interactivePopGestureRecognizerDelegate;
    UIResponder *previousResponder;
    UIBarButtonItem *m_leftBarBtnItem;
    UIBarButtonItem *m_rightBarBtnItem;
    UIColor *m_titleColor;
    MMUINavigationBar *fakeNaviView;
    BOOL m_hasAppear;
    UIView *bottomView;
}

@property(nonatomic) BOOL m_bStopPopWhenDeleteContact;
@property(nonatomic) BOOL m_bAnimating; // @synthesize m_bAnimating=_m_bAnimating;
@property(nonatomic, weak) UIViewController *presentedModalViewController;
@property(nonatomic, weak) UIViewController *presentingModalViewController;
@property(strong, nonatomic) NSMutableArray *m_arrEndUserOpInfo; // @synthesize m_arrEndUserOpInfo;
@property(nonatomic, weak) UIResponder *previousResponder; // @synthesize previousResponder;
@property(nonatomic) BOOL m_bDisableAdjustInsetAndOffset; // @synthesize m_bDisableAdjustInsetAndOffset;
@property(nonatomic) BOOL m_bInteractivePopEnabled; // @synthesize m_bInteractivePopEnabled;
@property(nonatomic) BOOL m_bIsBeingPoped; // @synthesize m_bIsBeingPoped;
@property(nonatomic) BOOL m_bAnimated; // @synthesize m_bAnimated;
@property(strong, nonatomic) NSMutableArray *m_fullScreenViews; // @synthesize m_fullScreenViews;
@property(strong, nonatomic) UIView *bottomView; // @synthesize bottomView;
@property(strong, nonatomic) UILabel *m_newsTitleRecordLabel; // @synthesize m_newsTitleRecordLabel;
@property(nonatomic) unsigned int m_uiVcType; // @synthesize m_uiVcType;
@property(strong, nonatomic) MMLoadingView *loadingViewX; // @synthesize loadingViewX=m_loadingViewX;

/**
 控制器切换操作

 @param navigationController 导航控制器
 @param arg2 <#arg2 description#>
 @param fromViewController 开始
 @param toViewController 目标
 @return id
 */
- (id)mmNavigationController:(UINavigationController *)navigationController
animationControllerForOperation:(long long)arg2
          fromViewController:(UIViewController *)fromViewController
            toViewController:(UIViewController *)toViewController;
- (void)reportEndOpInfo;
- (void)appendEndOpInfo:(id)arg1;
- (void)parseDeepLink:(id)arg1 animation:(BOOL)arg2;
- (id)getVCWithDeepLinkName:(id)arg1;
- (void)setDeepLinkParam:(id)arg1;
- (void)initDeepLinkConfig;
- (void)safeSetEdgesForExtendedLayout:(unsigned long long)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (BOOL)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (BOOL)shouldEnableKeyboardInteractivePop;
- (BOOL)shouldInteractivePop;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (BOOL)interactivePopGestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)didEndEditing:(id)arg1;
- (void)didBeginEditing:(id)arg1;
- (BOOL)isSubviewResponder:(id)arg1;
- (void)resignSubviewResponder:(id)arg1;
- (void)viewWillDismiss:(BOOL)arg1;
- (void)viewWillPresent:(BOOL)arg1;
- (void)viewDidPop:(BOOL)arg1;
- (void)viewWillPop:(BOOL)arg1;
- (void)viewDidPush:(BOOL)arg1;
- (void)viewWillPush:(BOOL)arg1;
- (void)viewDidBeDismissed:(BOOL)arg1;
- (void)viewWillBeDismissed:(BOOL)arg1;
- (void)viewDidBePresented:(BOOL)arg1;
- (void)viewWillBePresented:(BOOL)arg1;
- (void)viewDidBePoped:(BOOL)arg1;
- (void)viewWillBePoped:(BOOL)arg1;
- (void)viewDidBePushed:(BOOL)arg1;
- (void)viewWillBePushed:(BOOL)arg1;
- (void)removeFakeNaviView;
- (void)internalAddFakeNaviView:(id)arg1;
- (void)addFakeNaviView;
- (BOOL)useCustomNavibar;
- (BOOL)useTransparentNavibar;
- (BOOL)useBlackStatusbar;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)setBackBarButton;
- (void)removeDuplicateBarButton;
- (void)didMoveToParentViewController:(id)arg1;
- (id)getNavigationRightButton:(id)arg1;
- (id)getNavigationLeftButton:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)beginAppearanceTransition:(BOOL)arg1 animated:(BOOL)arg2;
- (void)willAppearanceTransition;
- (BOOL)isPresentedIn;
- (BOOL)isPushedIn;
- (id)tagForCurrentPage;
- (id)tagForActivePage;
- (id)getViewController;
- (void)resetViewStatus;
- (void)startForcedRotationToPortrait;
- (unsigned long long)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (BOOL)isSvrErrorTipForbidden;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)protectStatusBarFromBeingFuckedByForeGround:(SEL)arg1;
- (long long)preferredStatusBarStyle;
- (BOOL)prefersStatusBarHidden;
- (void)setStatusBarFontBlack;
- (void)setStatusBarFontWhite;
- (void)setStatusBarHidden:(BOOL)arg1 withAnimation:(long long)arg2;
- (void)setStatusBarHidden:(BOOL)arg1;
- (void)setTopBarsHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (void)changeTopBarsHiddenAnimated:(BOOL)arg1;
- (void)postNotification;
- (void)setOutLine:(BOOL)arg1;
- (void)setSubView:(id)arg1 OutLine:(BOOL)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)setTitleOnly:(id)arg1;
- (void)willDismissAndShow;
- (void)setTitleInterfaceOritation:(long long)arg1;
- (double)getRightBarButtonWidth;
- (double)getLeftBarButtonWidth;
- (void)setTitleView:(id)arg1;
- (id)getTitleColor;
- (void)setTitleColor:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)willShow;
- (void)willDisshow;
- (void)didDisshow;
- (void)didAppear;
- (void)willDisappear;
- (void)adjustView;
- (void)willAppear;
- (void)setIsPopByClickingURL;
- (void)handleUrl:(id)arg1 DisableFirstGetA8Key:(BOOL)arg2 extraInfo:(id)arg3;
- (void)restoreNavigationBarBkg;
- (void)removeNavigationBarBkg;
- (void)resetTableViewOffset:(id)arg1;
- (void)onMainWindowFrameChanged;
- (void)RemoveFullScreenViewList;
- (void)AddViewToFullScreenViewList:(id)arg1;
- (void)onTopBarHiddenChanged:(long long)arg1;
- (void)onTaskBarHiddenChanged:(BOOL)arg1 withAnimation:(long long)arg2;
- (void)onTopBarFrameChanged;
- (void)ReLayoutFullScreenViews;
- (void)viewDidLayoutSubviews;
- (void)viewDidTransitionToNewSize;
- (void)setAutolayoutTopOffset:(double)arg1 forView:(id)arg2;
- (void)setAutolayoutContentInset:(struct UIEdgeInsets)arg1 forScrollView:(id)arg2;
- (double)getSearchBarSearchingY;
- (double)getVisibleHeightOri:(long long)arg1;
- (double)getVisibleHeight;
- (double)getContentViewHeight;
- (double)getContentViewYforTranslucentNaviBar;
- (double)getContentViewY;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)init;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (BOOL)accessibilityPerformEscape;
- (void)disMissSelf;
- (void)adjustViewAndNavBarRect;
- (void)adjustSubviewRects;
- (void)adjustTableViewInset:(id)arg1;
- (void)adjustTableViewRect;
- (void)stopLoading;
- (void)startLoadingNonBlock;
- (void)startLoadingBlocked;
- (void)startLoadingWithText:(id)arg1 block:(BOOL)arg2;
- (void)stopLoadingWithFailText:(id)arg1;
- (void)stopLoadingWithOKText:(id)arg1;
- (void)startLoadingWithText:(id)arg1;
- (void)stopBizLoading;
- (void)startBizLoading;
- (void)setWCBizAuthTitle:(id)arg1;

@end

