//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


#import "IUiUtilExt.h"
#import "MMUIViewControllerDelegate.h"

@class MMDelegateProxy<UIGestureRecognizerDelegate>, MMLoadingView, MMTitleView, MMUINavigationBar;

@interface MMUIViewController : UIViewController <IUiUtilExt, MMUIViewControllerDelegate, UIGestureRecognizerDelegate>
{
    BOOL m_isPopByClickingURL;
    MMLoadingView *m_loadingViewX;
    unsigned int m_uiVcType;
    BOOL m_bKeyboardShowForGesture;
    UILabel *m_newsTitleRecordLabel;
    NSMutableArray *m_fullScreenViews;
    BOOL m_bAnimated;
    BOOL m_bIsBeingPoped;
    BOOL m_bInteractivePopEnabled;
    BOOL m_bDisableAdjustInsetAndOffset;
    CGFloat lastScreenWidth;
    UINavigationController *m_navigationController;
    MMTitleView *m_baseTitleView;
    NSMutableDictionary *m_dicDeepLink;
    NSMutableDictionary *m_dicContentInsetAutolayout;
    NSMutableDictionary *m_dicTopOffsetAutolayout;
    NSMutableArray *m_arrEndUserOpInfo;
    MMDelegateProxy<UIGestureRecognizerDelegate> *m_interactivePopGestureRecognizerDelegate;
    //    UIResponder *previousResponder;
    UIBarButtonItem *m_leftBarBtnItem;
    UIBarButtonItem *m_rightBarBtnItem;
    UIColor *m_titleColor;
    MMUINavigationBar *fakeNaviView;
    BOOL m_hasAppear;
    UIView *bottomView;
}

@property(nonatomic) BOOL m_bStopPopWhenDeleteContact;
@property(nonatomic) BOOL m_bAnimating; // @synthesize m_bAnimating=_m_bAnimating;
@property(nonatomic, weak) UIViewController *presentedModalViewController;
@property(nonatomic, weak) UIViewController *presentingModalViewController;
@property(strong, nonatomic) NSMutableArray *m_arrEndUserOpInfo; // @synthesize m_arrEndUserOpInfo;
@property(nonatomic, weak) UIResponder *previousResponder; // @synthesize previousResponder;
@property(nonatomic) BOOL m_bDisableAdjustInsetAndOffset; // @synthesize m_bDisableAdjustInsetAndOffset;
@property(nonatomic) BOOL m_bInteractivePopEnabled; // @synthesize m_bInteractivePopEnabled;
@property(nonatomic) BOOL m_bIsBeingPoped; // @synthesize m_bIsBeingPoped;
@property(nonatomic) BOOL m_bAnimated; // @synthesize m_bAnimated;
@property(strong, nonatomic) NSMutableArray *m_fullScreenViews; // @synthesize m_fullScreenViews;
@property(strong, nonatomic) UIView *bottomView; // @synthesize bottomView;
@property(strong, nonatomic) UILabel *m_newsTitleRecordLabel; // @synthesize m_newsTitleRecordLabel;
@property(nonatomic) unsigned int m_uiVcType; // @synthesize m_uiVcType;
@property(strong, nonatomic) MMLoadingView *loadingViewX; // @synthesize loadingViewX=m_loadingViewX;

- (void)setTitle:(NSString *)title;

/**
 控制器切换操作
 @param navigationController 导航控制器
 @param arg2 <#arg2 description#>
 @param fromViewController 开始
 @param toViewController 目标
 @return id
 */
- (id)mmNavigationController:(UINavigationController *)navigationController
animationControllerForOperation:(NSInteger)arg2
          fromViewController:(UIViewController *)fromViewController
            toViewController:(UIViewController *)toViewController;
- (void)reportEndOpInfo;
- (void)appendEndOpInfo:(id)arg1;
- (void)parseDeepLink:(id)arg1 animation:(BOOL)animated;
- (id)getVCWithDeepLinkName:(id)arg1;
- (void)setDeepLinkParam:(id)arg1;
- (void)initDeepLinkConfig;
- (void)safeSetEdgesForExtendedLayout:(NSUInteger)arg1;
- (BOOL)shouldEnableKeyboardInteractivePop;
- (BOOL)shouldInteractivePop;
- (BOOL)interactivePopGestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)didEndEditing:(id)arg1;
- (void)didBeginEditing:(id)arg1;
- (BOOL)isSubviewResponder:(id)arg1;
- (void)resignSubviewResponder:(id)arg1;
- (void)removeFakeNaviView;
- (void)internalAddFakeNaviView:(id)arg1;
- (void)addFakeNaviView;
- (BOOL)useCustomNavibar;
- (BOOL)useTransparentNavibar;
- (BOOL)useBlackStatusbar;

/**
 viewWillDismiss
 
 @param animated animated
 */
- (void)viewWillDismiss:(BOOL)animated;

/**
 viewWillPresent
 
 @param animated animated description
 */
- (void)viewWillPresent:(BOOL)animated;

/**
 viewDidPop
 
 @param animated animated description
 */
- (void)viewDidPop:(BOOL)animated;

/**
 viewWillPop
 
 @param animated animated description
 */
- (void)viewWillPop:(BOOL)animated;

/**
 viewDidPush
 
 @param animated animated description
 */
- (void)viewDidPush:(BOOL)animated;

/**
 viewWillPush
 
 @param animated animated description
 */
- (void)viewWillPush:(BOOL)animated;

/**
 viewDidBeDismissed
 
 @param animated animated description
 */
- (void)viewDidBeDismissed:(BOOL)animated;

/**
 viewWillBeDismissed
 
 @param animated animated description
 */
- (void)viewWillBeDismissed:(BOOL)animated;

/**
 viewDidBePresented
 
 @param animated animated description
 */
- (void)viewDidBePresented:(BOOL)animated;

/**
 viewWillBePresented
 
 @param animated animated description
 */
- (void)viewWillBePresented:(BOOL)animated;

/**
 viewDidBePoped
 
 @param animated animated description
 */
- (void)viewDidBePoped:(BOOL)animated;

/**
 viewWillBePoped
 
 @param animated animated description
 */
- (void)viewWillBePoped:(BOOL)animated;

/**
 viewDidBePushed
 
 @param animated animated description
 */
- (void)viewDidBePushed:(BOOL)animated;

/**
 viewWillBePushed
 
 @param animated animated description
 */
- (void)viewWillBePushed:(BOOL)animated;

- (void)setBackBarButton;
- (void)removeDuplicateBarButton;
- (UIButton *)getNavigationRightButton:(UIButton *)rightButton;
- (UIButton *)getNavigationLeftButton:(UIButton *)leftButton;

- (void)willAppearanceTransition;
- (BOOL)isPresentedIn;
- (BOOL)isPushedIn;
- (id)tagForCurrentPage;
- (id)tagForActivePage;
- (void)resetViewStatus;
- (void)startForcedRotationToPortrait;
- (BOOL)isSvrErrorTipForbidden;
- (void)protectStatusBarFromBeingFuckedByForeGround:(SEL)selector;
- (void)setStatusBarFontBlack;
- (void)setStatusBarFontWhite;
- (void)setStatusBarHidden:(BOOL)hidden withAnimation:(NSInteger)animation;
- (void)setStatusBarHidden:(BOOL)hidden;
- (void)setTopBarsHidden:(BOOL)hidden animated:(BOOL)animated;
- (void)changeTopBarsHiddenAnimated:(BOOL)animated;
- (void)postNotification;
- (void)setOutLine:(BOOL)outLine;
- (void)setSubView:(id)arg1 OutLine:(BOOL)arg2;
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section;
- (UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section;
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section;
- (void)setTitleOnly:(id)arg1;
- (void)willDismissAndShow;
- (void)setTitleInterfaceOritation:(NSInteger)interfaceOritation;
- (CGFloat)getRightBarButtonWidth;
- (CGFloat)getLeftBarButtonWidth;
- (void)setTitleView:(UIView *)titleView;
- (UIColor *)getTitleColor;
- (void)setTitleColor:(UIColor *)color;
- (void)willShow;
- (void)willDisshow;
- (void)didDisshow;
- (void)didAppear;
- (void)willDisappear;
- (void)adjustView;
- (void)willAppear;
- (void)setIsPopByClickingURL;
- (void)handleUrl:(id)url DisableFirstGetA8Key:(BOOL)shouldDisable extraInfo:(id)extraInfo;
- (void)restoreNavigationBarBkg;
- (void)removeNavigationBarBkg;
- (void)resetTableViewOffset:(id)arg1;
- (void)RemoveFullScreenViewList;
- (void)AddViewToFullScreenViewList:(id)arg1;
- (void)onTopBarHiddenChanged:(NSInteger)arg1;
- (void)ReLayoutFullScreenViews;


- (void)viewDidTransitionToNewSize;
- (void)setAutolayoutTopOffset:(CGFloat)offset forView:(UIView *)view;
- (void)setAutolayoutContentInset:(UIEdgeInsets)edgeInsets forScrollView:(UIScrollView *)scrollView;
- (CGFloat)getSearchBarSearchingY;
- (CGFloat)getVisibleHeightOri:(NSInteger)height;
- (CGFloat)getVisibleHeight;
- (CGFloat)getContentViewHeight;
- (CGFloat)getContentViewYforTranslucentNaviBar;
- (CGFloat)getContentViewY;


/**
 disMissSelf
 */
- (void)disMissSelf;

/**
 adjustViewAndNavBarRect
 */
- (void)adjustViewAndNavBarRect;

/**
 adjustSubviewRects
 */
- (void)adjustSubviewRects;

/**
 adjustTableViewInset
 
 @param edgeInsets edgeInsets description
 */
- (void)adjustTableViewInset:(UIEdgeInsets)edgeInsets;

/**
 adjustTableViewRect
 */
- (void)adjustTableViewRect;

/**
 stopLoading
 */
- (void)stopLoading;

/**
 startLoadingNonBlock
 */
- (void)startLoadingNonBlock;

/**
 startLoadingBlocked
 */
- (void)startLoadingBlocked;

/**
 startLoadingWithText
 
 @param text text description
 @param isBlock isBlock description
 */
- (void)startLoadingWithText:(NSString *)text block:(BOOL)isBlock;

/**
 stopLoadingWithFailText
 
 @param failText failText description
 */
- (void)stopLoadingWithFailText:(NSString *)failText;

/**
 stopLoadingWithOKText
 
 @param OKText OKText description
 */
- (void)stopLoadingWithOKText:(NSString *)OKText;

/**
 startLoadingWithText
 
 @param text text description
 */
- (void)startLoadingWithText:(NSString *)text;

/**
 stopBizLoading
 */
- (void)stopBizLoading;

/**
 startBizLoading
 */
- (void)startBizLoading;

/**
 setWCBizAuthTitle
 
 @param arg1 arg1 description
 */
- (void)setWCBizAuthTitle:(id)arg1;

@end
