//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IUiUtilExt.h"
#import "MMUIViewControllerDelegate.h"

@class MMDelegateProxy<UIGestureRecognizerDelegate>, MMLoadingView, MMTitleView, MMUINavigationBar;

@interface MMUIViewController : UIViewController <IUiUtilExt, MMUIViewControllerDelegate, UIGestureRecognizerDelegate>
{
    BOOL m_isPopByClickingURL;
    MMLoadingView *m_loadingViewX;
    unsigned int m_uiVcType;
    BOOL m_bKeyboardShowForGesture;
    UILabel *m_newsTitleRecordLabel;
    NSMutableArray *m_fullScreenViews;
    BOOL m_bAnimated;
    BOOL m_bIsBeingPoped;
    BOOL m_bInteractivePopEnabled;
    BOOL m_bDisableAdjustInsetAndOffset;
    CGFloat lastScreenWidth;
    UINavigationController *m_navigationController;
    MMTitleView *m_baseTitleView;
    NSMutableDictionary *m_dicDeepLink;
    NSMutableDictionary *m_dicContentInsetAutolayout;
    NSMutableDictionary *m_dicTopOffsetAutolayout;
    NSMutableArray *m_arrEndUserOpInfo;
    MMDelegateProxy<UIGestureRecognizerDelegate> *m_interactivePopGestureRecognizerDelegate;
//    UIResponder *previousResponder;
    UIBarButtonItem *m_leftBarBtnItem;
    UIBarButtonItem *m_rightBarBtnItem;
    UIColor *m_titleColor;
    MMUINavigationBar *fakeNaviView;
    BOOL m_hasAppear;
    UIView *bottomView;
}

@property(nonatomic) BOOL m_bStopPopWhenDeleteContact;
@property(nonatomic) BOOL m_bAnimating; // @synthesize m_bAnimating=_m_bAnimating;
@property(nonatomic, weak) UIViewController *presentedModalViewController;
@property(nonatomic, weak) UIViewController *presentingModalViewController;
@property(strong, nonatomic) NSMutableArray *m_arrEndUserOpInfo; // @synthesize m_arrEndUserOpInfo;
@property(nonatomic, weak) UIResponder *previousResponder; // @synthesize previousResponder;
@property(nonatomic) BOOL m_bDisableAdjustInsetAndOffset; // @synthesize m_bDisableAdjustInsetAndOffset;
@property(nonatomic) BOOL m_bInteractivePopEnabled; // @synthesize m_bInteractivePopEnabled;
@property(nonatomic) BOOL m_bIsBeingPoped; // @synthesize m_bIsBeingPoped;
@property(nonatomic) BOOL m_bAnimated; // @synthesize m_bAnimated;
@property(strong, nonatomic) NSMutableArray *m_fullScreenViews; // @synthesize m_fullScreenViews;
@property(strong, nonatomic) UIView *bottomView; // @synthesize bottomView;
@property(strong, nonatomic) UILabel *m_newsTitleRecordLabel; // @synthesize m_newsTitleRecordLabel;
@property(nonatomic) unsigned int m_uiVcType; // @synthesize m_uiVcType;
@property(strong, nonatomic) MMLoadingView *loadingViewX; // @synthesize loadingViewX=m_loadingViewX;

/**
 控制器切换操作

 @param navigationController 导航控制器
 @param arg2 <#arg2 description#>
 @param fromViewController 开始
 @param toViewController 目标
 @return id
 */
- (id)mmNavigationController:(UINavigationController *)navigationController
animationControllerForOperation:(NSInteger)arg2
          fromViewController:(UIViewController *)fromViewController
            toViewController:(UIViewController *)toViewController;
- (void)reportEndOpInfo;
- (void)appendEndOpInfo:(id)arg1;
- (void)parseDeepLink:(id)arg1 animation:(BOOL)animated;
- (id)getVCWithDeepLinkName:(id)arg1;
- (void)setDeepLinkParam:(id)arg1;
- (void)initDeepLinkConfig;
- (void)safeSetEdgesForExtendedLayout:(NSUInteger)arg1;
- (BOOL)shouldEnableKeyboardInteractivePop;
- (BOOL)shouldInteractivePop;
- (BOOL)interactivePopGestureRecognizerShouldBegin:(id)arg1;
- (BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)keyboardDidHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)didEndEditing:(id)arg1;
- (void)didBeginEditing:(id)arg1;
- (BOOL)isSubviewResponder:(id)arg1;
- (void)resignSubviewResponder:(id)arg1;
- (void)removeFakeNaviView;
- (void)internalAddFakeNaviView:(id)arg1;
- (void)addFakeNaviView;
- (BOOL)useCustomNavibar;
- (BOOL)useTransparentNavibar;
- (BOOL)useBlackStatusbar;



- (void)viewWillDismiss:(BOOL)animated;
- (void)viewWillPresent:(BOOL)animated;
- (void)viewDidPop:(BOOL)animated;
- (void)viewWillPop:(BOOL)animated;
- (void)viewDidPush:(BOOL)animated;
- (void)viewWillPush:(BOOL)animated;
- (void)viewDidBeDismissed:(BOOL)animated;
- (void)viewWillBeDismissed:(BOOL)animated;
- (void)viewDidBePresented:(BOOL)animated;
- (void)viewWillBePresented:(BOOL)animated;
- (void)viewDidBePoped:(BOOL)animated;
- (void)viewWillBePoped:(BOOL)animated;
- (void)viewDidBePushed:(BOOL)animated;
- (void)viewWillBePushed:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)setBackBarButton;
- (void)removeDuplicateBarButton;
- (UIButton *)getNavigationRightButton:(UIButton *)rightButton;
- (UIButton *)getNavigationLeftButton:(UIButton *)leftButton;

- (void)willAppearanceTransition;
- (BOOL)isPresentedIn;
- (BOOL)isPushedIn;
- (id)tagForCurrentPage;
- (id)tagForActivePage;
- (void)resetViewStatus;
- (void)startForcedRotationToPortrait;
- (BOOL)isSvrErrorTipForbidden;
- (void)protectStatusBarFromBeingFuckedByForeGround:(SEL)selector;
- (void)setStatusBarFontBlack;
- (void)setStatusBarFontWhite;
- (void)setStatusBarHidden:(BOOL)hidden withAnimation:(NSInteger)animation;
- (void)setStatusBarHidden:(BOOL)hidden;
- (void)setTopBarsHidden:(BOOL)hidden animated:(BOOL)animated;
- (void)changeTopBarsHiddenAnimated:(BOOL)animated;
- (void)postNotification;
- (void)setOutLine:(BOOL)outLine;
- (void)setSubView:(id)arg1 OutLine:(BOOL)arg2;
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section;
- (UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section;
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section;
- (void)setTitleOnly:(id)arg1;
- (void)willDismissAndShow;
- (void)setTitleInterfaceOritation:(NSInteger)interfaceOritation;
- (CGFloat)getRightBarButtonWidth;
- (CGFloat)getLeftBarButtonWidth;
- (void)setTitleView:(UIView *)titleView;
- (UIColor *)getTitleColor;
- (void)setTitleColor:(UIColor *)color;
- (void)willShow;
- (void)willDisshow;
- (void)didDisshow;
- (void)didAppear;
- (void)willDisappear;
- (void)adjustView;
- (void)willAppear;
- (void)setIsPopByClickingURL;
- (void)handleUrl:(id)arg1 DisableFirstGetA8Key:(BOOL)arg2 extraInfo:(id)arg3;
- (void)restoreNavigationBarBkg;
- (void)removeNavigationBarBkg;
- (void)resetTableViewOffset:(id)arg1;
- (void)RemoveFullScreenViewList;
- (void)AddViewToFullScreenViewList:(id)arg1;
- (void)onTopBarHiddenChanged:(NSInteger)arg1;
- (void)ReLayoutFullScreenViews;


- (void)viewDidTransitionToNewSize;
- (void)setAutolayoutTopOffset:(CGFloat)offset forView:(id)arg2;
- (void)setAutolayoutContentInset:(UIEdgeInsets)edgeInsets forScrollView:(id)arg2;
- (CGFloat)getSearchBarSearchingY;
- (CGFloat)getVisibleHeightOri:(NSInteger)height;
- (CGFloat)getVisibleHeight;
- (CGFloat)getContentViewHeight;
- (CGFloat)getContentViewYforTranslucentNaviBar;
- (CGFloat)getContentViewY;


- (void)disMissSelf;
- (void)adjustViewAndNavBarRect;
- (void)adjustSubviewRects;
- (void)adjustTableViewInset:(id)arg1;
- (void)adjustTableViewRect;
- (void)stopLoading;
- (void)startLoadingNonBlock;
- (void)startLoadingBlocked;
- (void)startLoadingWithText:(id)arg1 block:(BOOL)isBlock;
- (void)stopLoadingWithFailText:(id)arg1;
- (void)stopLoadingWithOKText:(id)arg1;
- (void)startLoadingWithText:(id)arg1;
- (void)stopBizLoading;
- (void)startBizLoading;
- (void)setWCBizAuthTitle:(id)arg1;

@end

