//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ContactSelectViewDelegate.h"
#import "GroupSelectContactsViewControllerDelegate.h"
#import "MMSearchBarDelegate.h"
#import "NewContactsSearchPanelViewDelegate.h"
#import "SelectTagContactsViewControllerDelegate.h"
#import "TipsViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "MultiSelectContactsViewControllerDelegate.h"

@class ContactSelectView, NSDictionary, NSIndexPath, NSMutableDictionary, NSString, NewContactsSearchPanelView, TipsView, UIBarButtonItem, UIButton, UIView;

/**
 联系人多选视图控制器
 */
@interface MultiSelectContactsViewController : MMUIViewController <SelectTagContactsViewControllerDelegate, ContactSelectViewDelegate, UISearchDisplayDelegate, MMSearchBarDelegate, WCActionSheetDelegate, NewContactsSearchPanelViewDelegate, GroupSelectContactsViewControllerDelegate, TipsViewDelegate>
{
//    id <MultiSelectContactsViewControllerDelegate> m_delegate;
    NSDictionary *m_dicExistContact;
    NSDictionary *m_dicIgnoreContact;
    BOOL m_bShowHistoryGroup;
    BOOL m_bShowRadarCreateRoom;
    BOOL m_bShowBrandContact;
    NSMutableDictionary *m_dicMultiSelect;
    NSIndexPath *m_indexPathToBeDeleted;
    NewContactsSearchPanelView *m_panelView;
    UIButton *m_panelBtn;
    UIBarButtonItem *m_panelBtnItem;
    NSUInteger m_uiGroupScene;
    NSUInteger m_memberCountLimit;
    NSString *m_showTip;
    TipsView *m_tipView;
    BOOL m_tempForbidLayout;
    ContactSelectView *m_selectView;
    int m_commonSearchScene;
    UIView *_tableFooterView;
    NSString *nsCurrentSearchText;
}

@property(nonatomic) BOOL m_onlyChatRoom;
@property(nonatomic) BOOL m_bKeepCurViewAfterSelect;
@property(nonatomic) int m_commonSearchScene; // @synthesize m_commonSearchScene;
@property(strong, nonatomic) NSMutableDictionary *m_dicMultiSelect; // @synthesize m_dicMultiSelect;
@property(strong, nonatomic) NSString *m_showTip; // @synthesize m_showTip;
@property(nonatomic) NSUInteger m_memberCountLimit; // @synthesize m_memberCountLimit;
@property(strong, nonatomic) UIBarButtonItem *m_panelBtnItem; // @synthesize m_panelBtnItem;
@property(strong, nonatomic) UIButton *m_panelBtn; // @synthesize m_panelBtn;
@property(nonatomic) NSUInteger m_uiGroupScene; // @synthesize m_uiGroupScene;
@property(nonatomic) BOOL m_bShowBrandContact; // @synthesize m_bShowBrandContact;
@property(nonatomic) BOOL m_bShowRadarCreateRoom; // @synthesize m_bShowRadarCreateRoom;
@property(nonatomic) BOOL m_bShowHistoryGroup; // @synthesize m_bShowHistoryGroup;
@property(strong, nonatomic) NSDictionary *m_dicIgnoreContact; // @synthesize m_dicIgnoreContact;
@property(strong, nonatomic) NSDictionary *m_dicExistContact; // @synthesize m_dicExistContact;
@property(nonatomic, weak) id <MultiSelectContactsViewControllerDelegate> m_delegate;

#pragma mark -

- (id)makeFiterContactToTagSearchView:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tryShowSelectTip:(NSUInteger)arg1 currentSelectCount:(NSUInteger)arg2;
- (NSUInteger)getTotalSelectCount;
- (void)onDone:(id)arg1;
- (void)onCancel:(id)arg1;
- (void)updatePanelView:(id)arg1;
- (void)updatePanelBtn;
- (BOOL)isExisted:(id)arg1;
- (BOOL)isIgnore:(id)arg1;
- (void)UpdateForChatGroup:(id)arg1;



@end

