//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTabBarBaseViewController.h"
#import "CreateChatLogicDelegate.h"
#import "IAcctStorageMgrExt.h"
#import "IAutoSetRemarkExt.h"
#import "IMMFacebookMgrExt.h"
#import "IVOIPUILogicMgrExt.h"
#import "IWCDeviceBrandMgrExt.h"
#import "IWXTalkPresentExt.h"
#import "MMKernelExt.h"
#import "MMSearchBarDelegate.h"
#import "MMVoiceSearchBarDelegate.h"
#import "MMVoiceSearchDelegate.h"
#import "MainFrameHeaderDelegate.h"
#import "MainTableDelegate.h"
#import "SelectContactsViewControllerDelegate.h"
#import "WCActionSheet.h"
#import "WCBarMessageWindowDelegate.h"
#import "contactInfoDelegate.h"
#import "mainFrameLogicControllerDelegate.h"

@class CreateChatLogic, MFTitleView, MMLoadingView, MMMainTableView, MMSessionInfo, MainFrameHeaderLogic, MainFrameLogicController, NSString, UIDynamicAnimator, UIImageView, VoiceSearchMutilLevelViewController, WCBarMessageWindow;

@interface NewMainFrameViewController : MMTabBarBaseViewController <SelectContactsViewControllerDelegate, IMMFacebookMgrExt, mainFrameLogicControllerDelegate, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, UISearchDisplayDelegate, WCActionSheetDelegate, contactInfoDelegate, CreateChatLogicDelegate, MMVoiceSearchDelegate, MMSearchBarDelegate, MMVoiceSearchBarDelegate, MMKernelExt, IWXTalkPresentExt, IVOIPUILogicMgrExt, IAutoSetRemarkExt, UIGestureRecognizerDelegate, IAcctStorageMgrExt, UIAlertViewDelegate, WCBarMessageWindowDelegate, MainTableDelegate, IWCDeviceBrandMgrExt, MainFrameHeaderDelegate>
{
    MainFrameLogicController *m_mainFrameLogicController;
    MMMainTableView *m_tableView;
    UIImageView *logoImageView;
    MFTitleView *m_titleView;
    MMLoadingView *m_loadingView;
    BOOL m_bSearching;
    struct CGPoint m_tableContentOffset;
    BOOL m_bFromReg;
    unsigned int m_uiTipStatus;
    CreateChatLogic *m_createChatLogic;
    BOOL m_tableViewReady;
    MainFrameHeaderLogic *m_headerLogic;
    NSString *m_nsTitle;
    int m_voiceSearchLevelNumber;
    VoiceSearchMutilLevelViewController *voiceSearchMultilLevelViewController;
    BOOL m_bFirstInitView;
    BOOL m_bOnMemoryWarningToFinishedSearchBar;
    struct CGPoint m_tableViewOffset;
    BOOL m_bIsLastViewStatusBarHidden;
    BOOL m_hasAddBlurEffectView;
    BOOL m_needResetTableViewOffset;
    double m_preContentOffset;
    WCBarMessageWindow *m_barMessageWindow;
    BOOL m_forbidShowTip;
    MMSessionInfo *_peekedSession;
    BOOL m_firstLoadFinished;
    BOOL m_searchDimmingViewRemoved;
    BOOL m_canSearchAfterInit;
    double m_messageCellHeight;
    long long m_lastRowNum;
    unsigned int _startTime;
    id <UIViewControllerPreviewing> _previewingContext;
    UIDynamicAnimator *_animator;
}

@property(retain, nonatomic) UIDynamicAnimator *animator; // @synthesize animator=_animator;
@property(retain, nonatomic) NSString *m_nsTitle; // @synthesize m_nsTitle;
@property(retain, nonatomic) CreateChatLogic *m_createChatLogic; // @synthesize m_createChatLogic;
@property(nonatomic) BOOL m_bFromReg; // @synthesize m_bFromReg;

- (id)tagForCurrentPage;
- (void)traitCollectionDidChange:(id)arg1;
- (void)previewingContext:(id)arg1 commitViewController:(id)arg2;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)checkDBAutoRecover;
- (void)initDeepLinkConfig;
- (id)getVCWithDeepLinkName:(id)arg1;
- (void)openMassSend;
- (void)onWCDeviceUnbindEnd:(id)arg1 Error:(id)arg2;
- (void)onBarTipClicked;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (id)getSubImage:(struct CGRect)arg1 inImage:(id)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onSettingChange;
- (void)onSetStrangerRemark:(id)arg1;
- (void)OnTrackRoomMemberChange:(id)arg1 withNewMemberList:(id)arg2;
- (void)OnRoomMemberChange:(id)arg1 withNewMemberList:(id)arg2;
- (void)onVideoVoipViewDisappear;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (void)updateItem:(id)arg1;
- (void)onAuthOK;
- (void)displayControllerSetActive:(BOOL)arg1 animated:(BOOL)arg2;
- (id)getSessionInfoByContact:(id)arg1;
- (void)SearchBarBecomeUnActive;
- (BOOL)shouldShowTabbar;
- (void)SearchBarBecomeActive;
- (void)addBlurEffectView;
- (void)setSearchTableResultText:(id)arg1;
- (void)OnVoiceSearchButtonDown;
- (void)updateViewWhenSelectTab:(BOOL)arg1;
- (void)changeNetworkStatus:(unsigned int)arg1;
- (unsigned int)getTotalUnreadCount;
- (void)clearResource;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 animated:(BOOL)arg3;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 animated:(BOOL)arg3 FromOtherTab:(BOOL)arg4;
- (void)newMessageByContact:(id)arg1 msgWrapToAdd:(id)arg2 animated:(BOOL)arg3 FromOtherTab:(BOOL)arg4 reuse:(BOOL)arg5 extraInfo:(id)arg6;
- (void)resetTableViewOffset:(id)arg1;
- (void)tapStatusBarMessage;
- (void)animationShow;
- (void)newMessageFromContactInfo:(id)arg1;
- (void)popToMainFrameAnimated:(BOOL)arg1;
- (void)updateStatusBar;
- (void)stopLoading;
- (void)startLoading;
- (void)stopLoadingForSessionRebuild;
- (void)startLoadingForSessionRebuild;
- (void)initLoadingView;
- (void)deleteSessionCell:(unsigned int)arg1 withUser:(id)arg2;
- (void)selectCellForName:(id)arg1;
- (void)cancelSelectedCell;
- (void)updateAllItemTimeLabel;
- (void)updateSession:(id)arg1;
- (void)clearSessionCache;
- (void)reloadSessions;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)applySearchBeginAnimation:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)MMVoiceSearchBarCancelButtonClicked:(id)arg1;
- (void)MMVoiceSearchBarSearchButtonClicked:(id)arg1;
- (void)MMVoiceSearchBar:(id)arg1 textDidChange:(id)arg2;
- (BOOL)MMVoiceSearchBarShouldBeginEditing:(id)arg1;
- (void)cancelSearch;
- (void)showBrandUnsubscribeActionSheet:(unsigned long long)arg1;
- (void)handleBrandUnsubscribe:(id)arg1;
- (void)handleCommitEdit:(unsigned long long)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showEditActionSheet:(unsigned long long)arg1;
- (id)getDestructiveBtnTitle:(unsigned long long)arg1;
- (id)getActionSheetTitle:(unsigned long long)arg1;
- (void)handleSelectIndexPath:(id)arg1 tableView:(id)arg2;
- (void)openContactInfoView:(id)arg1;
- (BOOL)isNeedMutilLevelView:(id)arg1;
- (BOOL)isNeedShowProfileInVoiceSearch:(int)arg1;
- (BOOL)isOpenPluginContactInfoView:(id)arg1;
- (void)openPluginContactInfoView:(id)arg1;
- (void)makeCellBackGroundBySession:(id)arg1 cell:(id)arg2 showTopList:(BOOL)arg3;
- (long long)getSectionType:(long long)arg1;
- (void)tryMoveToMainFrameTab;

#pragma mark - 进入聊天视图控制器页面
- (void)openMessageContentView:(id)arg1 startSendMessage:(BOOL)arg2 msgWrapToAdd:(id)arg3 animated:(BOOL)arg4 jumpToFirstUnreadNode:(BOOL)arg5 indexPath:(id)arg6 reuse:(BOOL)arg7 extraInfo:(id)arg8;
- (void)openMessageContentView:(id)arg1 startSendMessage:(BOOL)arg2 msgWrapToAdd:(id)arg3 animated:(BOOL)arg4 jumpToFirstUnreadNode:(BOOL)arg5 indexPath:(id)arg6;
- (void)openMessageContentView:(id)arg1 startSendMessage:(BOOL)arg2 msgWrapToAdd:(id)arg3 animated:(BOOL)arg4 jumpToFirstUnreadNode:(BOOL)arg5;

- (void)openEnterpriseChatSessionListView:(id)arg1 animated:(BOOL)arg2;
- (void)openEnterpriseBrandSessionView:(id)arg1;
- (void)openWeAppSessionView;
- (void)openBrandSessionView;
- (void)openSyncPhoneContactsView;
- (void)openFloatBottleContentView;
- (void)openQQOfflineMsgView;
- (void)openWeSportView:(id)arg1;
- (void)updateNearMode;
- (void)onCreateChatContactReturn:(id)arg1;
- (void)tryHideSearchGuideView;
- (void)tryInitViewOfSearchController;
- (void)removeSearchDimmingView;
- (BOOL)isSeachActive;
- (void)onMainWindowFrameChanged;
- (void)hideSearchBar;
- (BOOL)shouldShowTitleWindow;
- (void)finishSearchBarImmediately;
- (BOOL)hasShowSearchBar;
- (void)resetSearchBar;
- (id)getVoiceSearchBar;
- (BOOL)isTopRightMenuShowID:(id)arg1;
- (void)initBarItem;
- (void)reloadHeaderView;
- (void)initSearchController;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)resetViewStatus;
- (void)unLoadView;
- (void)unLoadData;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidPush:(BOOL)arg1;
- (void)viewDidPop:(BOOL)arg1;
- (void)viewWillPop:(BOOL)arg1;
- (void)removeMainFrameTip;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setTableViewContentInsetForSearchBar;
- (void)initView;
- (void)showInviteFriendList;
- (void)initFooterView;
- (void)initBarMessageWindow;
- (void)initStatusBar;
- (void)OpenContactInfo:(id)arg1;
- (void)PopViewContoller;
- (void)PushViewController:(id)arg1;
- (void)updateRow:(unsigned int)arg1;
- (void)removeRow:(unsigned int)arg1;
- (void)insertRow:(unsigned int)arg1;
- (BOOL)checkHeaderRowValid:(unsigned int)arg1;
- (void)reloadAll;
- (void)onShowPhoneFriend;
- (void)onShowGoogleFriend;
- (void)resetHeaderView;
- (void)initHeaderView;
- (void)initTableView;
- (double)getMainTableBottomInset;
- (void)initShadowLogo;
- (double)getLogoContentInsetTop;
- (void)initTitle;
- (void)initTitleView;
- (void)checkDelayLoadData;
- (void)setReadyToLoadData;
- (void)initData;
- (void)viewDidLayoutSubviews;
- (void)viewDidTransitionToNewSize;
- (void)reLayoutSubviews;
- (void)popToSelfViewController;
- (void)updateUnReadCount;
- (void)willAppear;
- (void)setNewMainFrameTableViewContentOffsetToTheFirstUnreadSession;
- (void)setNewMainFrameTableViewContentOffset:(struct CGPoint)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)openSelectReceiveOrPayMoneyFromShortcut;
- (void)openSelectReceiveOrPayMoney;
- (void)openFace2FaceReceiveMoney;
- (void)onRadar;
- (void)onMassSend;
- (void)openAlbum;
- (void)showQRInfoView;
- (void)showEmoticonStoreView;
- (void)showWCPayView;
- (void)showMyWCView;
- (void)onSelectContactReturn:(id)arg1 atScene:(unsigned int)arg2;
- (BOOL)onFilterContactCandidate:(id)arg1;
- (void)createVideoVOIPChat;
- (void)createVoiceVOIPChat;
- (void)onCreateNewMessage;

@end

