//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CommonImageBrowserDelegate.h"
#import "ContactRemarkImgExt.h"
#import "MMImagePickerManagerDelegate.h"
#import "MMTableViewInfoDelegate.h"
#import "WCActionSheet.h"
#import "MMTableViewCell.h"

@class CContact, ContactRemarkLogic, MMTableViewInfo, MMTableViewSectionInfo, NSMutableArray, NSMutableDictionary, NSString, UIImage, UIImageView, UILabel, UITextField, UITextView, UIView;

@interface RemarkViewController : MMUIViewController <ContactRemarkImgExt, UITextViewDelegate, UITextFieldDelegate, WCActionSheetDelegate, MMImagePickerManagerDelegate, CommonImageBrowserDelegate, UIAlertViewDelegate, MMTableViewInfoDelegate>
{
    MMTableViewInfo *m_tableViewInfo;
    MMTableViewSectionInfo *m_phoneSection;
    MMTableViewSectionInfo *m_descSection;
    NSMutableArray *m_arrPhoneItem;
    ContactRemarkLogic *m_logic;
    CContact *m_contact;
    UIImage *m_cardImg;         /**< 名片图像 */
    UITextField *m_nameView; /**< 名字 */
    UITextView *m_descView; /**< 描述TextView */
    UILabel *m_descHint;
    UIView *m_tagView;
    UIImageView *m_imageView;
    NSMutableDictionary *m_phoneEdit;
    NSInteger m_firstResponderIndex;
    BOOL m_downloadingImg;
    BOOL m_isDownloadFail;
    BOOL m_hasEditImg;
    BOOL m_needEditState;
    BOOL m_deleteHashPhone;
    NSString *m_recommandRemark;
    BOOL m_bNeedReloadSubviews;
    BOOL m_bIsRemarkEdit;
}

@property(strong, nonatomic) NSString *recommandRemark; // @synthesize recommandRemark=m_recommandRemark;
@property(strong, nonatomic) CContact *m_contact; // @synthesize m_contact;
@property(nonatomic) BOOL needEditState; // @synthesize needEditState=m_needEditState;

- (void)scrollRectToVisibleForView:(id)arg1;
- (void)adjustDescTextView;

/**
 执行修改
 */
- (void)executeOpLog;
- (void)showImg:(id)arg1;
- (void)showTagEdit;
- (void)useRecommandRemark;
- (void)hideKeyboard;
- (void)keyboardWillHide:(id)arg1;
- (id)getPhoneTextFieldAt:(NSInteger)arg1;
- (id)getPhoneItemInfoAt:(NSUInteger)arg1;
- (void)reloadTableView;
- (void)startDownCardImg;
- (void)makeRemarkCell:(MMTableViewCell *)tableViewCell CellInfo:(MMTableViewCellInfo *)tableViewCellInfo;
- (void)makeTagsCell:(MMTableViewCell *)tableViewCell CellInfo:(MMTableViewCellInfo *)tableViewCellInfo;

/**
 配置描述cell

 @param tableViewCell cell
 @param tableViewCellInfo cellInfo
 */
- (void)makeDescriptionCell:(MMTableViewCell *)tableViewCell CellInfo:(MMTableViewCellInfo *)tableViewCellInfo;
- (void)makeImageCell:(MMTableViewCell *)tableViewCell CellInfo:(MMTableViewCellInfo *)tableViewCellInfo;
- (void)makePhoneCell:(MMTableViewCell *)tableViewCell CellInfo:(MMTableViewCellInfo *)tableViewCellInfo;
- (void)makeDescView;
- (void)fixDescViewHeight:(CGFloat)height;
- (void)makeImageView;
- (void)dottedLine:(id)arg1;
- (void)showPhoneTip;
- (void)onAddPhone;
- (void)reflashImageCell;
- (id)makeRecommBtnView;
- (BOOL)needRecommBtn;
- (id)getRemarkText;
- (void)uploadCardImg;

/**
 完成按钮响应事件
 */
- (void)onPerformEdit;
- (BOOL)checkEdit;
- (id)checkEditPhone;
- (void)showImagePicker:(NSInteger)arg1;
- (void)deleteImage;
- (void)onDeleteItemAtIndex:(NSUInteger)arg1;
@end

