//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchBarDisplayController.h"

#import "AddMemLogicDelegate.h"
#import "ChatRoomMemberGridViewDelegate.h"
#import "DelMemLogicDelegate.h"
#import "IContactMgrExt.h"
#import "MMTableViewInfoDelegate.h"
#import "NewChatRoomMemberItemViewDelegate.h"
#import "NewContactsSearchPanelViewDelegate.h"
#import "tableViewDelegate.h"
#import "RoomContactSelectDelegate.h"

@class AddMemLogic, CBaseContact, CContact, DelMemLogic, MMTableView, MMTableViewInfo, NSArray, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NewContactsSearchPanelView;

/**
 删除成员多选视图控制器
 */
@interface RoomContactSelectViewController : MMSearchBarDisplayController <AddMemLogicDelegate, DelMemLogicDelegate, tableViewDelegate, UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, NewContactsSearchPanelViewDelegate, ChatRoomMemberGridViewDelegate, MMTableViewInfoDelegate, NewChatRoomMemberItemViewDelegate, IContactMgrExt>
{
    MMTableView *m_tableView;
    NSMutableArray *m_arrRoomMembers;
    NSMutableArray *m_arrKeys;
    NSMutableDictionary *m_dicRoomMembers;
    CBaseContact *m_roomContact;
    NSMutableArray *m_arrFilterdFriends;
    NSMutableSet *m_setFilteredFriends;
    id <RoomContactSelectDelegate> m_delegate;
    NewContactsSearchPanelView *m_panelView;
    int m_commonSearchScene;
    unsigned int m_scene;
    NSArray *m_customMemberList;
    MMTableViewInfo *m_tableViewInfo;
    CContact *m_chatRoomContact;
    unsigned long long m_nCellCnt;
    unsigned long long m_nCellCol;
    NSArray *m_arrMemberList;
    _Bool m_bDeleteStatus;
    AddMemLogic *m_addMemLogic;
    DelMemLogic *m_delMemLogic;
    _Bool m_bShowWithGrid;
    _Bool _m_bShowSelf;
    _Bool _m_bSortByTime;
    _Bool _m_bCustomMakeCell;
    _Bool _m_bEnableEdit;
    _Bool _m_bMultiSelect;
    _Bool _m_bShowIsFriend;
    struct CGPoint m_bContentOffset;
}

@property(nonatomic) _Bool m_bShowIsFriend; // @synthesize m_bShowIsFriend=_m_bShowIsFriend;
@property(nonatomic) _Bool m_bMultiSelect; // @synthesize m_bMultiSelect=_m_bMultiSelect;
@property(nonatomic) _Bool m_bEnableEdit; // @synthesize m_bEnableEdit=_m_bEnableEdit;
@property(nonatomic) _Bool m_bCustomMakeCell; // @synthesize m_bCustomMakeCell=_m_bCustomMakeCell;
@property(nonatomic) _Bool m_bSortByTime; // @synthesize m_bSortByTime=_m_bSortByTime;
@property(nonatomic) _Bool m_bShowSelf; // @synthesize m_bShowSelf=_m_bShowSelf;
@property(retain, nonatomic) NSArray *m_customMemberList; // @synthesize m_customMemberList;
@property(nonatomic) unsigned int m_scene; // @synthesize m_scene;
@property(retain, nonatomic) CContact *m_chatRoomContact; // @synthesize m_chatRoomContact;
@property(nonatomic) struct CGPoint m_bContentOffset; // @synthesize m_bContentOffset;
@property(nonatomic) _Bool m_bShowWithGrid; // @synthesize m_bShowWithGrid;
@property(nonatomic) int m_commonSearchScene; // @synthesize m_commonSearchScene;
@property(retain, nonatomic) NewContactsSearchPanelView *m_panelView; // @synthesize m_panelView;
@property(nonatomic) __weak id <RoomContactSelectDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) CBaseContact *m_roomContact; // @synthesize m_roomContact;

#pragma mark - DelMemLogicDelegate
- (void)onDelMemLogicStop:(BOOL)onDel;

- (void)didSearchViewTableSelect:(id)arg1;
- (double)heightForSearchViewTable:(id)arg1;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (void)doSearch:(id)arg1 Pre:(_Bool)arg2;
- (void)didDeleteLastWithKey:(id)arg1;
- (void)didClickImageAtIndex:(unsigned int)arg1 withKey:(id)arg2;

- (void)doSearch:(id)arg1;
- (void)showDelMemView;
- (void)setShowRemoveMember;
- (void)onAddMemLogicStop:(_Bool)arg1;
- (void)addMember;



- (void)didSelectContact:(id)arg1;
- (void)makeCell:(id)arg1 contact:(id)arg2;

- (void)onCancel:(id)arg1;
- (void)onDeleteMember:(id)arg1;

- (void)OnDataChange;
- (void)initView;
- (void)initSearchBar;
- (void)initTableView;
- (id)getMemberList;
- (void)reloadMemberListAndView;
- (void)reloadView;
- (void)initData;
- (id)getContactWith:(id)arg1;
- (void)addContact:(id)arg1;
- (id)addSectionKey:(id)arg1;
- (id)GetCompareStrByContact:(id)arg1;
- (void)updateTitleView;
- (void)onModifyContact:(id)arg1;
- (void)openContactInfo:(id)arg1;
- (void)loadMemberList;
- (void)resortMemList;
- (void)reloadProfileGridTableData;
- (void)makeMemListSection:(id)arg1;
- (void)makeWhiteCell:(id)arg1 CellInfo:(id)arg2;
- (void)makeMemListCell:(id)arg1 CellInfo:(id)arg2;
- (void)updateMemberView;
- (void)updateToNormalStatusEx;

@end

