//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "ICertInfoMgrExt.h"
#import "IUpdateProfileMgrExt.h"
#import "PBMessageObserverDelegate.h"
#import "PasswordLogicDelegate.h"
#import "VerifyPhoneDelegate.h"
#import "VoicePrintSwitchOpDelegate.h"
#import "WCAccountSetPasswordViewControllerDelegate.h"
#import "settingModifyAliasDelegate.h"

@class CertInfo, MMTableViewInfo, NSMutableArray, NSString, PasswordLogic, VPSwitchOpCgi;

@interface SettingMyAccountInfoViewController : MMUIViewController <VoicePrintSwitchOpDelegate, VerifyPhoneDelegate, ICertInfoMgrExt, WCAccountSetPasswordViewControllerDelegate, PasswordLogicDelegate, settingModifyAliasDelegate, IUpdateProfileMgrExt, PBMessageObserverDelegate>
{
    VPSwitchOpCgi *m_switchOpCgiHandle;
    CertInfo *m_certInfo;
    PasswordLogic *m_passwdLogic;
    MMTableViewInfo *m_tableViewInfo;
    NSMutableArray *m_arrDevicelist;
    unsigned int m_uiHasVoice;
    unsigned int m_uiOpenVoice;
    unsigned int m_uiHasFace;
    unsigned int m_uiOpenFace;
    unsigned int m_uiHasWxPwd;
}

- (void).cxx_destruct;
- (void)initDeepLinkConfig;
- (void)OnSwitchOpErrorWithScene:(unsigned int)arg1 andErrorCode:(int)arg2;
- (void)OnSwitchOp:(int)arg1 andSwitch:(int)arg2 withScene:(unsigned int)arg3;
- (void)saveNewAlias;
- (void)willShow;
- (void)ReloadData;
- (void)onSetPasswordOK;
- (void)onSetPasswordBack;
- (void)unknownFail:(id)arg1;
- (void)checkHaveNotSetPassword:(id)arg1;
- (void)checkHaveSetPassword:(id)arg1;
- (void)setPasswordOK:(id)arg1;
- (void)passwordLogicPause:(id)arg1;
- (void)passwordLogicStart:(id)arg1;
- (void)passwordLogicCancel:(id)arg1;
- (void)verifyPasswordOK:(id)arg1 logic:(id)arg2;
- (void)verifyPasswordFail:(id)arg1;
- (void)openSecurityCenter;
- (void)setTrustedFriends;
- (void)showMoreAccount;
- (void)setSaveDevice;
- (void)setVoicePrint;
- (void)setPassword;
- (void)showSetPassword:(id)arg1;
- (void)showWhatsVView;
- (void)bindPhoneReturn;
- (void)showBindPhone;
- (void)makeVInfoCell:(id)arg1;
- (void)makeBindPhoneCell:(id)arg1 cellInfo:(id)arg2;
- (void)OnUpdateCertInfo;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)startGetSafetyInfo;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)undoRegester;
- (void)doRegester;
- (void)reloadTableData;
- (void)initVerifyCellData;
- (void)initSecurityCellData;
- (void)initWeChatIDView;
- (void)showModifyUserName;
- (int)getLinesForV:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

