//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UISlider, UIView<WAStreamPlayerInterface>;

@interface WAFullVideoViewController : UIViewController
{
    long long _statusBarStyle;
    _Bool _landScape;
    UIView<WAStreamPlayerInterface> *_video;
    UISlider *_volumeViewSlider;
}

@property(retain, nonatomic) UISlider *volumeViewSlider; // @synthesize volumeViewSlider=_volumeViewSlider;
@property(nonatomic) __weak UIView<WAStreamPlayerInterface> *video; // @synthesize video=_video;
@property(nonatomic) _Bool landScape; // @synthesize landScape=_landScape;
- (void).cxx_destruct;
- (void)setVolumeIncrease:(double)arg1;
- (void)setStatusBarHidden:(_Bool)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLayoutSubviews;
- (_Bool)shouldAutorotate;
- (void)dealloc;
- (void)enterBackground;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

