//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WAJSEventHandler_BaseEvent.h"

@interface WAJSEventHandler_launchMiniProgram : WAJSEventHandler_BaseEvent
{
    _Bool _isTrustInputUserName;
}

@property(nonatomic) _Bool isTrustInputUserName; // @synthesize isTrustInputUserName=_isTrustInputUserName;
- (void)launchWeApp:(id)arg1 launchAppID:(id)arg2 launchDebugMode:(unsigned int)arg3 pagePath:(id)arg4 extraData:(id)arg5;
- (_Bool)isAllowLaunchWeApp:(id *)arg1;
- (id)getLaunchUserNameWithAppId:(id)arg1;
- (void)mainThread_handleJSEvent:(id)arg1;
- (void)handleJSEvent:(id)arg1;

@end

