//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CBaseContact, CContact, CEmoticonWrap, CMessageWrap, ImageInfo, MMInputToolView, MMWebViewController, ServiceAppData, TranslateInfo;

@protocol BaseMsgContentDelgate <NSObject>
- (BOOL)ShouldShowMultiSelectMode;
- (BOOL)shouldPreventViewcontrollerAutorotate;
- (void)DeleteAtUserList;
- (void)AddAtUser:(NSString *)arg1;
- (NSString *)nameForHeadImageLongPressed:(CBaseContact *)arg1;
- (BOOL)canReloadViewIfMemoryWarning;
- (void)didSelectSearchResultForMessageWrap:(CMessageWrap *)arg1;
- (NSArray *)previewActionItems;
- (BOOL)shouldSearchedMsgHightlight;
- (unsigned int)getSearchedMsgLocalID;

/**
 是否使所有操作不可用

 @return 可用标识
 */
- (BOOL)shouldDisableAllOperation;
- (BOOL)ShouldShowSearchedAnyMsg;
- (BOOL)ShouldShowSearchResultMessageArray;
- (BOOL)ShouldShowSearchCompleteRightBarButton;
- (BOOL)ShouldShowSearchBar;
- (NSString *)GetRightBarButtonTitle;
- (NSString *)GetRightBarButtonImageName;

/**
 停止播放

 @param messageWrap 消息对象
 */
- (void)StopPlaying:(CMessageWrap *)messageWrap;

/**
 开始播放消息

 @param messageWrap 消息模型
 @param fromTouch 是否来自用户点击
 */
- (void)StartPlaying:(CMessageWrap *)messageWrap FromTouch:(BOOL)fromTouch;

/**
 正在录音

 @return BOOL
 */
- (BOOL)IsRecording;

/**
 关闭录音
 */
- (void)CancelRecording;

/**
 停止录音
 */
- (void)StopRecording;

/**
 开始录音
 */
- (void)StartRecording;

/**
 获取联系对象

 @return 联系对象
 */
- (CBaseContact *)GetContact;

/**
 文字变化操作

 @param textChange 变化的文本
 @param range 范围
 */
- (void)onTextChange:(NSString *)textChange selectedRange:(NSRange)range;
- (void)setNeedUpdateTitle:(BOOL *)arg1;
- (UIImage *)GetTitleImage;
- (void)onSaveDraft;
- (void)onWillPushFromNavigationController;
- (void)onWillPopFromNavigationController;
- (void)onBackFromNavigationController;
- (void)onPopFromNavigationController;
- (BOOL)EnabledOfHeaderButtonAtIndex:(unsigned int)arg1;
- (UIImage *)ImageOfHeaderButtonAtIndex:(unsigned int)arg1;
- (NSString *)TitleOfHeaderButtonsAtIndex:(unsigned int)arg1;
- (unsigned int)NumberOfHeaderButtons;

/**
 重发消息

 @param messageWrap 消息对象
 */
- (void)ResendMessage:(CMessageWrap *)messageWrap;
- (void)StateChanged;

/**
 语音模式按钮点击
 */
- (void)VoiceModeClicked;
- (void)ViewWillDisappear;
- (void)ViewWillAppear;
- (void)ViewDidAppear;
- (void)ViewDidInit;
- (void)ViewWillInit;
- (NSString *)GetUsrTitleCPKey;
- (BOOL)isUsrTitleUnsafe;
- (NSString *)GetUsrTitleTail;
- (NSString *)GetUsrTitleFront;
- (NSString *)GetUsrTitle;
- (BOOL)HasCustomToolBar;
- (void)HasCustomInputToolViewAndDontNeedShowToolView:(BOOL *)arg1;
- (void)OpenEmoticonToolView:(MMInputToolView *)arg1;
- (void)CustomToolViewEX:(MMInputToolView *)arg1;
- (BOOL)onLoadDownMoreMessage;

/**
 点击更多消息事件

 @return 消息列表
 */
- (NSMutableArray *)onLoadMoreMessage;
- (void)onSendCaptrueImage:(NSURL *)imageUrl;
- (void)onOpenCameraController;
- (void)onOpenMediaBrowser;
- (void)DelMsgWithMsgList:(NSArray *)arg1 DelAll:(BOOL)arg2;
- (void)clearDownLeftCount;
- (void)clearLastCreateTime;
- (NSMutableArray *)GetMessageArray;
- (void)onOpenServiceApp:(ServiceAppData *)arg1;
- (void)onGroupPayButtonClick;
- (void)onRedEnvelopesControlLogic;
- (void)onTransferMoneyControlLogic;
- (void)onOpenServiceAppListController;
- (void)onOpenMyCardPkgViewController;
- (void)onOpenMyFavoritesListController;
- (void)onVideoVoipInvite;
- (void)onVoipInvite;
- (void)ViewLocation:(CMessageWrap *)arg1;
- (void)SelectLocation:(BOOL)arg1;
- (void)onMultiTalkButtonClick;
- (void)ShareCard;
- (void)SendNotGameEmoticonMessage:(CMessageWrap *)arg1 errorMsg:(NSString *)arg2;

/**
 发送颜文字消息

 @param emotionWrap 颜文字对象
 */
- (void)SendEmoticonMessage:(CEmoticonWrap *)emotionWrap;
- (void)SendEmojiArtMessage:(NSString *)arg1;
- (void)SendTextMessage:(NSString *)msg;    /**< 发送文本消息 */

/**
 发送消息对象

 @param messageWrap 消息
 */
- (void)SendMessageWrap:(CMessageWrap *)messageWrap;

/**
 根据图片获取消息对象

 @param image 图片
 @return 消息对象
 */
- (CMessageWrap *)GetMessageFromImage:(UIImage *)image;

/**
 发送图片消息

 @param image 图片
 @param imageInfo 图片消息封装
 */
- (void)SendImageMessage:(UIImage *)image ImageInfo:(ImageInfo *)imageInfo;
- (BOOL)CanShowSight;
- (BOOL)CanShowBanner;
- (BOOL)CanOpenServiceAppList;
- (BOOL)CanSelectMyFavoritesItemForSendingMsg;
- (BOOL)CanRotateOrientation;
- (BOOL)CanWXTalk;
- (BOOL)CanSendEmoticonMessage;
- (BOOL)CanAddApp;
- (BOOL)CanOpenCamera;
- (BOOL)CanLongPressHeadImage;
- (BOOL)CanSend3rdMsg;
- (BOOL)CanSendVoipMsg;
- (BOOL)CanOpenTrackRoom;
- (BOOL)CanSendLocationMsg;
- (BOOL)CanSendVideoMsg;
- (BOOL)CanSendVoiceMsg;
- (BOOL)CanSendImageMsg:(UIImage *)arg1;
- (BOOL)CanSendTextMsg:(NSString *)arg1;
- (void)didShowFirstUnReadMessage;
- (void)setLastCreateTime:(unsigned long long)arg1;
- (NSMutableArray *)GetMessageArrayFrom:(unsigned int)arg1 createTime:(unsigned long long)timeStamp;

/**
 获取第一条未读消息

 @return 消息对象
 */
- (CMessageWrap *)GetFirstUnReadMessage;
- (NSMutableArray *)GetSearchedResultContentMessageArray;
- (NSMutableArray *)GetDownMessageArray;

/**
 打开联系人信息

 @param aContact 联系人对象
 */
- (void)OpenContactInfo:(CBaseContact *)aContact;
- (void)OpenDetailInfo;

@optional
- (NSString *)tagForCurrentPage;
- (void)onClickPlayMusicBtn:(CMessageWrap *)arg1 isPlay:(BOOL)arg2;
- (void)onClickMsg:(CMessageWrap *)arg1;
- (void)onDeleteMsg:(CMessageWrap *)arg1;
- (void)onClickFavMenu:(CMessageWrap *)arg1;
- (void)onClickVoiceTranslate:(CMessageWrap *)arg1;
- (void)onClickTranslateMsg:(CMessageWrap *)arg1 translateInfo:(TranslateInfo *)arg2;
- (void)onClickTextFloatPreView:(CMessageWrap *)arg1;
- (BOOL)isChatStatusNotifyOpen;
- (void)headerImageClickedWithMsg:(CMessageWrap *)arg1;
- (void)onExposeTemplateMsg:(CMessageWrap *)arg1;
- (void)openOpenSDKAppBrand:(CMessageWrap *)arg1;
- (void)openWaApp:(CMessageWrap *)arg1;
- (void)shareDataToOpenSDK:(CMessageWrap *)arg1;
- (void)onClickWeAppReceiveSessionMsg;
- (void)onClickReceiveBrandMsg;
- (void)onClickShieldBrandMsg;
- (void)clickLinkToDealWithSysXml:(CMessageWrap *)arg1 fromScene:(NSString *)arg2;
- (void)setExtraInfo;
- (NSMutableDictionary *)getExtraInfo;
- (NSString *)genMsgSource;
- (void)hasTapReaderNodeView;
- (BOOL)shouldHideToolViewWhenKeyboardHide;
- (void)viewDidRotateToOrientation:(long long)arg1;
- (void)viewWillRotateToOrientation:(long long)arg1;
- (void)RevokeMsg:(CMessageWrap *)arg1;
- (void)SetMsgPlayed:(CMessageWrap *)arg1;
- (void)exitTracking;
- (void)openTrackRoom:(NSNumber *)arg1;
- (void)clearNewInvApprove;
- (void)clearNewInvCount;
- (void)clearAtMeCount;
- (void)onInputTextDeleteAll;
- (void)onMultiMsgSelected:(NSMutableArray *)arg1 Username:(NSString *)arg2;
- (void)resetWithMessageWrap:(CMessageWrap *)arg1;
- (void)sendMultiMsgBySystemMail:(NSMutableArray *)arg1;
- (void)onMultiSelectCancel;
- (void)onMultiMsgDelete:(NSMutableArray *)arg1;
- (void)downloadMultiMsg:(NSMutableArray *)arg1 saveToAlbum:(BOOL)arg2;
- (void)sendMultiMsgToBrandContact:(NSMutableArray *)arg1 To:(CContact *)arg2;
- (void)sendMultiMsgByMail:(NSMutableArray *)arg1;
- (void)sendMultiMsgToFriend:(NSMutableArray *)arg1;
- (void)addMultiMsgToMyFav:(NSMutableArray *)arg1;
- (void)toBeEditing:(BOOL)arg1;
- (UIBarButtonItem *)getLeftBarButton;
- (void)onMassSendSendAgain:(NSArray *)arg1;
- (BOOL)isShowHeadImage:(CMessageWrap *)arg1;
- (MMWebViewController *)getPreviewForLink:(NSString *)arg1;
- (void)OnTagLink:(NSString *)arg1 messageWrap:(CMessageWrap *)arg2;
- (UIBarButtonItem *)GetRightBarBtn;
- (BOOL)hasDownMoreMsg;
- (BOOL)hasMoreMsg;
- (BOOL)canShowChatRoomInfo;
- (UIView *)getBackgroundView;
- (void)OnVideoPlayEnd:(CMessageWrap *)arg1 isForceStop:(BOOL)arg2;
- (void)StartPlayVideo:(CMessageWrap *)arg1;
- (void)StartDownloadShortVideo:(CMessageWrap *)arg1;
- (void)StartDownloadVideo:(CMessageWrap *)arg1 DownloadMode:(NSUInteger)arg2;
- (void)StartDownloadVideo:(CMessageWrap *)arg1;
- (void)StartUploadVideo:(CMessageWrap *)arg1;
- (void)StopDownloadVideo:(CMessageWrap *)arg1;
- (void)StopUploadVideo:(CMessageWrap *)arg1;
- (BOOL)NeedRightButtonRedDot;
- (UIImage *)GetTitleTailImage;
- (UIImage *)HighlightedImageOfHeaderButtonAtIndex:(unsigned int)buttonIndex;
@end

