//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class CContact;

@protocol ContactsDataLogicDelegate <NSObject>
- (BOOL)onFilterContactCandidate:(CContact *)contact;
- (void)onContactsDataChange;

@optional
- (void)onContactAsynSearchSectionResultChanged:(NSArray *)resultList sectionTitles:(NSDictionary *)titlesDic sectionResults:(NSDictionary *)resultsDic;
@end

