//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ForwardMessageLogicController;
@class WAAppMsgItem;

@protocol ForwardMessageLogicDelegate <NSObject>
- (UIViewController *)getCurrentViewController;

@optional
- (void)OnForwardWeAppMessageSend:(NSString *)message appMsgItem:(WAAppMsgItem *)appMsgItem;
- (void)OnForwardMessageStayAtWeChat:(ForwardMessageLogicController *)aForwardMessageLogicController;
- (BOOL)shouldShowSendSuccessView:(ForwardMessageLogicController *)aForwardMessageLogicController;
- (void)OnForwardMessageSelectSession:(ForwardMessageLogicController *)aForwardMessageLogicController;
- (void)OnForwardMessageBackToApp:(ForwardMessageLogicController *)aForwardMessageLogicController;
- (void)OnForwardMessageException:(ForwardMessageLogicController *)aForwardMessageLogicController;
- (void)OnForwardMessageCancel:(ForwardMessageLogicController *)aForwardMessageLogicController;
- (void)OnForwardMessageSend:(ForwardMessageLogicController *)aForwardMessageLogicController;
@end

