//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GetGameIndex2Response_TypeNavModule_Item;

@protocol GameCenterNavCategoryViewDelegate <NSObject>
- (void)onNavCategoryItemClicked:(GetGameIndex2Response_TypeNavModule_Item *)arg1 ItemIndex:(int)arg2;
@end

