//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CContact;

@protocol IContactMgrExt

@optional
- (void)onBrandContactHeadImageURLChange:(NSString *)headImageURL;
- (void)onFailedToGetContactsFromSvr;
- (void)OnChangeNotifyStatus:(NSString *)notifyStatus withStatus:(BOOL)status;
- (void)onContactListUpdate:(unsigned int)update;
- (void)onRemoveContactFromAddressBook:(CContact *)contact;
- (void)onDeleteContact:(CContact *)contact;
- (void)onModifyCustomMenu:(CContact *)contact;
- (void)onModifySelfContact:(CContact *)contact;
- (void)onModifyContact:(CContact *)contact;
- (void)onNewContact:(CContact *)contact;
- (void)onModifyContactHeadImage:(NSString *)headImage;
@end

