//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


/**
 通讯录标签成员管理器拓展
 */
@protocol IContactLabelMgrExt <NSObject>

@optional
- (void)onContactTagNameUpdate:(NSDictionary *)arg1;
- (void)onAllTagNameUpdate;
- (void)setContactLabel:(NSArray *)arg1 withRetCode:(int)retCode andEventId:(NSUInteger)eventId;
- (void)updateContactLabelName:(NSArray *)arg1 withRetCode:(int)retCode andEventId:(NSUInteger)eventId;
- (void)onDeleteContactLabel:(NSArray *)arg1 withRetCode:(int)retCode andEventId:(NSUInteger)eventId;
- (void)onAddContactLabel:(NSArray *)arg1 withRetCode:(int)retCode andEventId:(NSUInteger)eventId;
- (void)onAllContactLabelUpdated:(NSArray *)arg1 withRetCode:(int)retCode andEventId:(NSUInteger)eventId;
@end

