//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@class OplogErrMsg, ProtobufCGIWrap;

@protocol IOplogExt <NSObject>
- (void)oplogRet:(int)ret errMsg:(OplogErrMsg *)errorMsg eventID:(NSUInteger)eventID cgiWrap:(ProtobufCGIWrap *)aProtobufCGIWrap;
@end

