//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CContact;

@protocol IStrangerContactMgrExt <NSObject>

@optional
- (void)onStrangerContactUpdateForbidden:(NSString *)arg1;
- (void)onStrangerContactUpdated:(NSString *)arg1 Contact:(CContact *)aContact;
- (void)onStrangerContactUpdated:(NSArray *)arg1;
@end

