//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol ISysCallCheckExt

@optional

/**
 OnSysCallState

 @param state state description
 */
- (void)OnSysCallState:(int)state;

/**
 InputIsAvailableChanged

 @param isAvailableChanged isAvailableChanged description
 */
- (void)InputIsAvailableChanged:(BOOL)isAvailableChanged;

/**
 结束中断
 */
- (void)EndInterruption;

/**
 开始中断
 */
- (void)BeginInterruption;
@end

