//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol IUiUtilExt <NSObject>

@optional
- (void)onTaskBarHiddenChanged:(BOOL)changed withAnimation:(NSInteger)animation;
- (void)onTopBarHiddenChanged:(BOOL)changed withAnimation:(NSInteger)animation;
- (void)onStatusBarHiddenChanged:(NSInteger)status;
- (void)onTopBarFrameChanged;
- (void)onStatusBarFrameChanged;
- (void)onMainWindowFrameChanged;
@end

