//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CContact;

@protocol IVOIPExt

@optional
- (void)OnStopPlaySound;
- (void)onVideoOrientationChangeTo:(NSInteger)videoOrientation;
- (void)OnCallOverLoad:(CContact *)aContact errNo:(int)errNo errMsg:(NSString *)errMsg;
- (void)OnCallBanned:(CContact *)aContact errNo:(int)errNo errMsg:(NSString *)errMsg;
- (void)OnAutoHangUp:(CContact *)aContact;
- (void)OnCallInterrupt:(CContact *)aContact;
- (void)OnLightInterrupt:(BOOL)shouldLightInterrupt;
- (void)OnTellMeViewIsExist:(BOOL *)isExist;
- (void)OnMonitorWithSendRecvInfo:(int)sendRecvInfo andSendFPS:(int)sendFPS andRecvFPS:(int)recvFPS andSendKbps:(int)sendKbps andRecvKbps:(int)recvKbps andP2SInfo:(NSString *)P2SInfo andSpeed:(int *)speed;
- (void)OnMonitorWithSendFPS:(int)sendFPS andRecvFPS:(int)recvFPS;
- (void)OnMonitorChannelInfo:(unsigned int)channel andChannelType:(int)channelType andConnStrategy:(int)connStrategy;
- (void)OnTalkBrokenError:(CContact *)aContact ErrNo:(int)errNo;
- (void)OnNetWorkError:(CContact *)aContact ErrNo:(int)errNo;
- (void)OnSyncError:(CContact *)aContact ErrNo:(int)errNo;
- (void)OnError:(CContact *)aContact ErrNo:(int)errNo;
- (void)OnTimeOut:(CContact *)aContact;
- (void)OnInterrupt:(CContact *)aContact;
- (void)OnBeginTalk:(CContact *)aContact;
- (void)OnBeginConnect:(CContact *)aContact;
- (void)OnBeHanguped:(CContact *)aContact;
- (void)OnBeRejected:(CContact *)aContact;
- (void)OnPreConnect:(CContact *)aContact;
- (void)OnBeAccepted:(CContact *)aContact;
- (void)OnNoAnswer:(CContact *)aContact;
- (void)OnAccept:(CContact *)aContact ErrNo:(int)errNo;
- (void)OnCall:(CContact *)aContact ErrNo:(int)errNo;
@end

