//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CLLocation, CLHeading;

@protocol LocationRetrieveDelegate <NSObject>
- (void)onRetrieveLocationError:(int)errorCode;
- (void)onRetrieveLocationTimeOut:(CLLocation *)location;
- (void)onRetrieveLocationOK:(CLLocation *)location;

@optional
- (void)onRetrieveHeadingError:(int)errorCode;
- (void)onRetrieveHeadingOK:(CLHeading *)heading;
@end

