//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol MCssParserDelegate <NSObject>
- (void)onCssParseEnd;
- (void)onCssParseStart;
- (NSString *)onNextCssFile;
- (void)onParseErrorInFile:(NSString *)filepath onLineNumber:(NSNumber *)lineNumber withText:(NSString *)text withErrorMessage:(NSString *)message;
- (void)onScriptFunctionWithSelectors:(NSArray *)arg1 withStatements:(NSArray *)arg2;
- (void)onReceiveCssRulesetWithSelectors:(NSArray *)arg1 withDeclarations:(NSDictionary *)arg2;
@end

