//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CBaseContact, CContact, CMessageWrap, MMUIViewController, PushMailWrap, TranslateInfo;

@protocol MessageNodeViewDelegate <NSObject>

@optional
- (void)onClickPlayMusicBtn:(CMessageWrap *)aCMessageWrap isPlay:(BOOL)isPlay;
- (void)onClickFavMenu:(CMessageWrap *)aCMessageWrap;
- (void)onClickVoiceTranslate:(CMessageWrap *)aCMessageWrap;
- (void)onClickTextFloatPreView:(CMessageWrap *)aCMessageWrap;
- (void)onClickTranslateMsg:(CMessageWrap *)aCMessageWrap translateInfo:(TranslateInfo *)aTranslateInfo;
- (void)clickNewAASysMsg:(NSString *)arg1 withMsgLocalID:(unsigned int)arg2;
- (void)shareMsgToOpenSDKByNodeView:(CMessageWrap *)aCMessageWrap;
- (void)clickWeAppReceiveSessionMsg;
- (void)clickReceiveBrandMsg;
- (void)clickShieldBrandMsg;
- (void)clickLinkToDealWithSysXml:(CMessageWrap *)aCMessageWrap fromScene:(NSString *)arg2;
- (void)clickLinkToExpose;
- (void)onFullScreenWindowWillHide;
- (void)willShowMenuController:(id)arg1;
- (void)filterShowMenuItem:(NSMutableArray *)arg1 sender:(id)arg2;
- (BOOL)isMsgLastSend:(CMessageWrap *)aCMessageWrap;
- (BOOL)isMsgCanRevoke:(CMessageWrap *)aCMessageWrap;
- (void)revokeMsgByNodeView:(CMessageWrap *)aCMessageWrap;
- (void)SetMsgPlayed:(CMessageWrap *)aCMessageWrap;
- (void)switchEarMode;
- (void)jumpToUserProfile:(NSString *)username Displayname:(NSString *)displayname Scence:(unsigned int)scence;
- (void)onHideKeyboard;
- (void)onMoreOperateWithMsgId:(NSString *)arg1;
- (void)onForwardMessageOK;
- (void)onMassSendSendAgain:(NSArray *)arg1;
- (void)onScrollToBottom;
- (void)tagLink:(NSString *)arg1 messageWrap:(CMessageWrap *)aCMessageWrap;
- (MMUIViewController *)getViewController;
- (void)hasTapReaderNodeView;
- (void)longPressOnHeadImageForDebug:(CMessageWrap *)aCMessageWrap;
- (void)longPressOnHeadImage:(CBaseContact *)aCBaseContact;
- (BOOL)canLongPressOnHeadImage:(CBaseContact *)aCBaseContact;
- (void)deleteNode:(CMessageWrap *)aCMessageWrap;
- (void)StartDownloadShortVideo:(CMessageWrap *)aCMessageWrap;
- (void)StartDownloadVideo:(CMessageWrap *)aCMessageWrap DownloadMode:(NSUInteger)downloadMode;
- (void)StartDownloadVideo:(CMessageWrap *)aCMessageWrap;
- (void)StartUploadVideo:(CMessageWrap *)aCMessageWrap;
- (void)StopDownloadVideo:(CMessageWrap *)aCMessageWrap;
- (void)StopUploadVideo:(CMessageWrap *)aCMessageWrap;
- (void)onExposeTemplateMsg:(CMessageWrap *)aCMessageWrap;
- (void)readerViewClickedWithMsg:(CMessageWrap *)aCMessageWrap;
- (void)headerImageClickedWithMsg:(CMessageWrap *)aCMessageWrap;
- (void)headerImageClicked:(CBaseContact *)arg1;
- (void)OnEndPlaying:(CMessageWrap *)aCMessageWrap;
- (void)EndPlaying:(CMessageWrap *)aCMessageWrap;
- (void)BeginPlaying:(CMessageWrap *)aCMessageWrap FromTouch:(BOOL)arg2;
- (void)PlayVideo:(CMessageWrap *)aCMessageWrap soundable:(BOOL)arg2;
- (void)tapWeAppImage_NodeView:(id)arg1;
- (void)tapAppNodeView:(id)arg1;
- (void)tapFriendCard_NodeView:(id)arg1 WithContact:(CContact *)aContact WithMsg:(CMessageWrap *)aCMessageWrap;
- (void)tapVideoStatus_NodeView:(id)arg1 DownloadMode:(NSUInteger)downloadMode;
- (void)tapPushMail_NodeView:(id)arg1 withPushMailWrap:(PushMailWrap *)pushMailWrap;
- (void)tapVideoStatus_NodeView:(id)arg1;
- (void)tapStatus_NodeView:(id)arg1;
- (void)tapLocation_NodeView:(id)arg1;
- (void)tapImage_NodeView:(id)arg1;
@end

