//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MMAsset,SightDraft;

@protocol MMImagePickerManagerDelegate <NSObject>
- (void)MMImagePickerManagerDidCancel:(UINavigationController *)navigationController;
- (void)MMImagePickerManager:(UINavigationController *)navigationController didFinishPickingImageWithInfo:(NSArray *)info;

@optional
- (void)MMImagePickerManager:(UINavigationController *)navigationController didFinishPickingGifWithData:(NSData *)data;
- (void)MMImagePickerManager:(UINavigationController *)navigationController didFinishPickingSightWithAsset:(MMAsset *)asset;
- (void)MMImagePickerManager:(UINavigationController *)navigationController didFinishPickingSightWithInfo:(SightDraft *)aSightDraft;
- (void)MMImagePickerManager:(UINavigationController *)navigationController didFinishPickingVideoWithInfo:(NSDictionary *)info;
@end

