//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CEmoticonWrap, MMUIViewController, ServiceAppData;

@protocol MMInputToolViewDelegate <NSObject>

@optional
- (BOOL)isHiddenInputChangeButton;
- (void)onToolViewDidMoveToWindow;
- (BOOL)shouldHideToolViewOnKeyboardHide;
- (BOOL)shouldInitWXEmoticonView;
- (void)keyboardWillHide;
- (MMUIViewController *)GetCurrentViewController;
- (void)initAllowNameCardFollowRedEnvelope;
- (void)initAllowWxTalkFollowSight;
- (void)initAllowShareCard;
- (void)initAllowRecommendApp;
- (void)initAllowMultiTalk;
- (void)initAllowWxTalk;
- (void)initAllowVoiceInput;
- (void)initAllowVoip;
- (BOOL)isViewControllerAnimated;
- (BOOL)ShouldShowKeyboardAnimation;
- (void)onTextDeleteAll;
- (void)sendCaptruedImage:(NSURL *)sendURL;
- (void)pasteImage:(UIImage *)image;
- (NSString *)getCurrentChatName;
- (void)redEnvelopesLogic;
- (void)transferMoneyLogic;
- (void)openServiceAppListController;
- (BOOL)hasGroupPayEntry;
- (BOOL)hasCardPkgEntry;
- (BOOL)hasRedEnvelopesEntry;
- (BOOL)hasTransferMoneyEntry;
- (BOOL)hasServiceEntry;
- (NSArray *)getServiceAppList;
- (NSArray *)getAttachmentViewServiceAppList;
- (void)openServiceApp:(ServiceAppData *)aServiceAppData;
- (void)onStreamVoiceInputButtonClick;
- (NSString *)chatUserNameForSightStatistics;
- (void)onGroupPayButtonClick;
- (void)onOpenMyCardPkgViewController;
- (void)openMyFavoritesListController;
- (void)openEnterpriseBrandEntry;
- (BOOL)canShowEnterpriseBrandEntry;
- (BOOL)canShowLocation;
- (BOOL)canShowFavEntry;
- (BOOL)canShowSight;
- (void)onOpenTrackRoom:(unsigned int)room;
- (BOOL)shouldShowOpenTrackRoom;
- (void)onSelectLocation;
- (void)onVideoVoipInvite;
- (void)onVoipInvite;
- (void)onMultiTalkButtonClick;
- (void)onShareCard;
- (void)SendEmoticonMesssageToolView:(CEmoticonWrap *)aCEmotionWrap;
- (void)TextDidChanged:(NSString *)text selectedRange:(NSRange)range;
- (void)onSightPictureTaken:(UIImage *)pictureImage withFrontCamera:(BOOL)arg2;
- (void)onShortVideoTaken:(NSString *)arg1 thumbImg:(UIImage *)img sentImmediately:(BOOL)shouldImmediately isMuted:(BOOL)isMuted;
- (void)openCameraController;
- (void)openMediaBrowser;
- (void)CancelRecording;
- (void)StopRecording;
- (void)StartRecording;
- (void)onPositionModeChangeTo:(int)arg1 Animated:(BOOL)animated;
- (void)HasCustomInputToolViewAndDontNeedShowToolView:(BOOL *)arg1;
- (void)ToolViewPositionDidChanged:(BOOL)didChanged animated:(BOOL)animated;
- (void)SendEmojiArtMessageToolView:(NSString *)emojiArtMsg;
- (void)SendTextMessageToolView:(NSString *)textMsg;
@end

