//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol MMMultiSelectToolViewDelegate <NSObject>

@optional
- (void)OnMultiDeleteMessage:(id)arg1;
- (void)OnMultiMsgMoreOperation:(UIButton *)sender;
- (void)OnMultiEmailMessage:(id)arg1;
- (void)OnMultiForwardMessage;
- (void)OnMultiFavAddMessage;
@end

