//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMUIViewController, TextFloatViewController, UIScrollView;

@protocol MMRichTextCopyEventDelegate <NSObject>
- (TextFloatViewController *)getTextFloatViewController;
- (void)setTextFloatViewHidden:(_Bool)arg1;
- (MMUIViewController *)getUIViewController;
- (UIScrollView *)getScrollView;
- (void)onRichTextViewExit;
@end

