//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MMScrollActionSheet, MMScrollActionSheetItem;

@protocol MMScrollActionSheetDelegate <NSObject>

@optional
- (void)scrollActionSheet:(MMScrollActionSheet *)scrollActionSheet clickCustomBtn:(id)customBtn;
- (void)scrollActionSheetWillDismiss:(MMScrollActionSheet *)scrollActionSheet;
- (void)scrollActionSheetDidScroll:(MMScrollActionSheet *)scrollActionSheet;
- (void)scrollActionSheetDidCancel:(MMScrollActionSheet *)scrollActionSheet;
- (void)scrollActionSheetDidAppeared:(MMScrollActionSheet *)scrollActionSheet;
- (void)scrollActionSheet:(MMScrollActionSheet *)scrollActionSheet didSelecteItem:(MMScrollActionSheetItem *)scrollActionSheetItem;
@end

