//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MMSearchBar;

@protocol MMSearchBarDelegate <NSObject>

@optional
- (BOOL)shouldHighlightRowAtIndexPath:(NSIndexPath *)indexPath;
- (NSString *)titleForHeaderInSection:(NSInteger)section ForSearchViewTable:(UITableView *)tableView;
- (UIView *)viewForHeaderInSection:(NSInteger)section ForSearchViewTable:(UITableView *)tableView;
- (CGFloat)heightForHeaderInSection:(NSInteger)section ForSearchViewTable:(UITableView *)tableView;
- (NSInteger)numberOfRowsInSection:(NSInteger)section ForSearchViewTable:(UITableView *)tableView;
- (NSInteger)numberOfSectionsForSearchViewTable:(UITableView *)tableView;
- (UITableViewCell *)cellForIndex:(NSIndexPath *)indexPath ForSearchViewTable:(UITableView *)tableView;
- (void)didSearchViewTableSelect:(NSIndexPath *)indexPath;
- (CGFloat)heightForSearchViewTable:(NSIndexPath *)indexPath;
- (UITableViewCell *)cellForSearchViewTable:(UITableViewCell *)tableViewCell index:(NSIndexPath *)indexPath;
- (void)didScrollViewBeginDragging:(UIScrollView *)scrollView;
- (void)didScrollViewScroll:(UIScrollView *)scrollView;
- (BOOL)shouldShowTabbarAfterSearchBarBecomeUnActive;
- (void)SearchBarShouldEnd;
- (void)SearchBarBecomeUnActive;
- (void)SearchBarBecomeActive;
- (void)mmSearchDisplayControllerDidHideSearchResultsTableView:(UITableView *)tableView;
- (void)mmSearchDisplayControllerWillHideSearchResultsTableView:(UITableView *)tableView;
- (void)mmSearchDisplayControllerDidShowSearchResultsTableView:(UITableView *)tableView;
- (void)mmSearchDisplayControllerWillShowSearchResultsTableView:(UITableView *)tableView;
- (void)mmSearchDisplayControllerDidEndSearch;
- (void)mmSearchDisplayControllerWillEndSearch;
- (void)mmSearchDisplayControllerDidBeginSearch;
- (void)mmSearchDisplayControllerWillBeginSearch;
- (void)mmSearchBarDidEnd;
- (void)mmSearchBarTextDidChange:(NSString *)text;
- (BOOL)mmsearchBarShouldChangeTextInRange:(NSRange)range replacementText:(NSString *)text;
- (void)mmsearchBarTextDidBeginEditing:(UISearchBar *)searchBar;
- (void)mmsearchBarCancelButtonClicked:(MMSearchBar *)searchBar;
- (void)mmsearchBarSearchButtonClicked:(MMSearchBar *)searchBar;
- (void)cancelSearch;
- (void)doSearch:(NSString *)content Pre:(BOOL)isPre;
@end

