//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol MMVoiceSearchBarDelegate <NSObject>
- (void)MMVoiceSearchBarCancelButtonClicked:(UISearchBar *)searchBar;
- (void)MMVoiceSearchBarSearchButtonClicked:(UISearchBar *)searchBar;
- (void)MMVoiceSearchBar:(UISearchBar *)searchBar textDidChange:(NSString *)changedText;

@optional
- (BOOL)MMVoiceSearchBarShouldBeginEditing:(UISearchBar *)searchBar;
@end

