//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CMessageWrap, ImageInfo, MMAsset;

@protocol MsgDelegate <NSObject>

@optional
- (void)ClearUnRead:(NSString *)userName FromID:(unsigned int)fromID ToID:(unsigned int)toID;
- (unsigned int)GetUnReadCount:(NSString *)arg1;
- (void)DelMsg:(NSString *)arg1 MsgList:(NSArray *)msgList DelAll:(BOOL)shouldDelAll;
- (NSMutableArray *)GetMsg:(NSString *)arg1 FromID:(unsigned int)fromID Limit:(unsigned int)limit LeftCount:(unsigned int *)leftCount LeftUnreadCount:(unsigned int *)leftUnreadCount;
- (void)ModMsg:(NSString *)arg1 MsgWrap:(CMessageWrap *)msgWrap;
- (void)AddMsg:(NSString *)arg1 MsgWrap:(CMessageWrap *)msgWrap;
- (CMessageWrap *)formImageMsgByMMAsset:(MMAsset *)aMMAsset toUserName:(NSString *)userName;
- (CMessageWrap *)FormImageMsg:(NSString *)imageMsg withImage:(UIImage *)image withData:(NSData *)data withImageInfo:(ImageInfo *)imageInfo;
- (CMessageWrap *)FormImageMsg:(NSString *)imageMsg withImage:(UIImage *)image withData:(NSData *)data;
- (CMessageWrap *)FormImageMsg:(NSString *)imageMsg withImage:(UIImage *)image;
- (CMessageWrap *)FormTextMsg:(NSString *)textMsg withText:(NSString *)text;
@end

