//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CMessageWrap, MsgImgFullScreenViewController, MsgImgPreviewData;

@protocol MsgImgFullScreenViewControllerDelegate <NSObject>

@optional
- (void)onMsgImgPreviewDataRequired:(MsgImgPreviewData *)aMsgImagePreviewData;
- (void)onCurrentPageMsgReMoved:(CMessageWrap *)aCMessageWrapaCMessageWrap;
- (void)onMsgImgWindowWillHideToMsg:(CMessageWrap *)aCMessageWrap;
- (void)onSightViewDetail:(NSString *)arg1 vc:(MsgImgFullScreenViewController *)aMsgImgFullScreenViewController;
- (void)onImgMsgLocate:(CMessageWrap *)aCMessageWrap vc:(MsgImgFullScreenViewController *)aMsgImgFullScreenViewController;
- (void)onPlayAttachVideo:(CMessageWrap *)aCMessageWrap vc:(MsgImgFullScreenViewController *)aMsgImgFullScreenViewController;
@end

