//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CBaseEvent, CLocalInfo;

@protocol NotifyFromEventDelegate

@optional
- (CLocalInfo *)GetLocalInfo;
- (unsigned int)GetNetworkReachabilitySeed;
- (BOOL)IsLogIn;
- (void)SpeedyNotifyFromEvent:(CBaseEvent *)event Message:(unsigned int)msg MessageInfo:(NSDictionary *)msgInfo;
- (void)NotifyFromEvent:(CBaseEvent *)event Message:(unsigned int)msg MessageInfo:(NSDictionary *)msgInfo;
@end

