//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol PeopleNearByListViewControllerDelegate <NSObject>

/**
 绑定qq按钮点击事件
 */
- (void)onBindQQBtnClicked;

/**
 上传名片夹按钮点击事件
 */
- (void)onUploadAddressbookBtnClicked;

/**
 绑定手机按钮点击事件
 */
- (void)onBindPhoneBtnClicked;
- (void)onChatRoomNearByBtnClicked;
@end

