//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class LbsContactInfoList, LbsRecommendPoiItem, LbsRoomResponse, MMLbsContactInfo;

@protocol SeePeopleNearByUIDelegate <NSObject>

@optional
- (void)onGetLBSRecommendPoiList:(NSArray *)poiList;
- (void)onJoinChatRoomFailed;
- (void)onJoinChatRoomFinishedWithResult:(LbsRoomResponse *)aLbsRoomresponse;
- (void)onJoinChatRoomStart;
- (void)showMessage:(NSString *)message;
- (void)onGetCertificationFinish;
- (void)onSelectedWithLbsContactInfo:(MMLbsContactInfo *)aMMLbsContactInfo;
- (void)onSelectedWithLbsPoiItem:(LbsRecommendPoiItem *)aLbsRecommendPoiItem;
- (void)onUpdateLbsContactInfoError:(int)errorCode;
- (void)onUpdateLbsContactInfoFinishedWithData:(LbsContactInfoList *)aLbsContactInfoList;
- (void)onClearMyLbsDataFinishedWithResult:(BOOL)shouldClear;
@end

