//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol ShortVideoBarDelegate <NSObject>
- (void)onCameraResign;
- (void)onSightPictureTaken:(UIImage *)picture withFrontCamera:(BOOL)should;
- (void)onShortVideoTaken:(NSString *)arg1 thumbImg:(UIImage *)thumbImg sentImmediately:(BOOL)shouldImmediately isMuted:(BOOL)isMuted;
- (void)onShortVideoToolBtnClick:(int)buttonIndex;

@optional
- (NSString *)chatUserNameForSightStatistics;
- (void)onStopRecord;
- (void)onStartRecord;
- (void)onDeactiveAnimStart:(CGFloat)animStart;
- (void)onPanelDrag:(CGFloat)drag;
- (void)onDeactiveAnimEnd;
@end

