//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol tableViewDelegate <NSObject>

@optional
- (void)didFinishedLoading:(id)arg1;
- (void)touchesCancelled_TableView:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesEnded_TableView:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesMoved_TableView:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesBegan_TableView:(NSSet *)touches withEvent:(UIEvent *)event;
@end

