//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol textViewDelegate <NSObject>

@optional
- (void)onAccessoryViewFrameChanged:(CGRect)changeFrame;
- (void)textview:(UITextView *)textView pasteImage:(UIImage *)image;
- (BOOL)textview:(UITextView *)textView shouldPasteImage:(UIImage *)image;
- (void)touchesCancelled_TextView:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesEnded_TextView:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesMoved_TextView:(NSSet *)touches withEvent:(UIEvent *)event;
- (void)touchesBegan_TextView:(NSSet *)touches withEvent:(UIEvent *)event;
@end

