//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class TipsView;

@protocol TipsViewDelegate <NSObject>

@optional
- (void)onPerformExposeAction:(TipsView *)tipsView;
- (void)onPerformIconAction:(TipsView *)tipsView;
- (void)onPerformAction:(TipsView *)tipsView;
- (void)onTipsViewClose:(TipsView *)tipsView;
- (void)onTipsViewClick:(TipsView *)tipsView;
@end

