//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol VerifyPhoneDelegate <NSObject>

@optional
- (void)loginByPhoneVerifiedWithUserName:(NSString *)userName ticket:(NSString *)aTicket;
- (void)loginByPhoneVerifiedWithUserName:(NSString *)userName pwd:(NSString *)aPwd;
- (void)bindPhoneReturn;
@end

