//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol WAAppDetailInfoManagerExtension <NSObject>
- (void)onGetAppAuthInfoList:(NSArray *)arg1 appid:(NSString *)arg2 errorCode:(int)arg3;
@end

