//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol WAVideoPlayerCoreDelegate <NSObject>

@optional
- (void)onCurrentTimeUpdate:(double)arg1;
- (void)onTotalTimeUpdate:(double)arg1;
- (void)onCacheUpdate:(double)arg1;
- (void)onNetWorkError:(long long)arg1;
- (void)onVideoPlayEnd;
- (void)onLoadingEnd;
- (void)onLoadingBegin;
- (void)onStateChange:(long long)arg1;
@end

