//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol WCAccountMainLoginViewControllerDelegate <NSObject>

@optional
- (void)onMainLoginUseBothDevice;
- (void)onMainLoginFacebookConnect;
- (void)onMainLoginProblem;
- (void)onMainLoginGotoSecurityCenter;
- (void)onMainLoginBack;
- (void)onMainLoginUserName:(NSString *)userName Pwd:(NSString *)pwd;
- (void)onMainLoginNext:(NSString *)arg1 phoneNumber:(NSString *)phoneNumber;
@end

