//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol WCAccountLoginLastUserViewControllerDelegate <NSObject>
- (void)onLastUserVoicePrintLogin:(id)arg1;
- (void)onLastUserChangeAccountWithView:(UIView *)arg1;
- (void)onLastUserChangeAccount:(id)arg1;
- (void)onLastUserRegister;
- (void)onLastUserGoToHelpCenter:(id)arg1;
- (void)onLastUserGoToSecurityCenter:(id)arg1;
- (void)onLastUserProblem:(id)arg1;
- (void)onLastUserLoginUserName:(NSString *)userName Pwd:(NSString *)password;
@end

