//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class WCCanvasComponent;

@protocol WCCanvasPageViewControllerDelegate <NSObject>

@optional
- (void)canvasComponent:(WCCanvasComponent *)aWCCanvasComponent willExistAndJumpUrl:(NSString *)jumpUrl;
- (void)onCloseCanvasPageView;
@end

