//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class MMUIViewController, NSString, UIView, UIViewController;

@protocol WCForceTouchPreviewProtocol <NSObject>
- (BOOL)canPeek;

@optional
- (CGRect)previewingSourceRectForLocation:(CGPoint)arg1 inCoordinateView:(UIView *)arg2;
- (NSString *)urlForPreView:(MMUIViewController *)arg1;
- (UIViewController *)viewControllerForPreview:(MMUIViewController *)arg1;
- (UIViewController *)viewControllerToPreviewWithFromController:(MMUIViewController *)arg1 forLocation:(CGPoint)arg2 inCoordinateView:(UIView *)arg3;
@end

