//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class CBaseContact;

@protocol WCNetworkMediaPlayerDelegate <NSObject>
- (void)onClosePlayer;

@optional
- (BOOL)needHiddenMoreMenu;
- (void)onShareVideoToTimeline:(BOOL)shouldShare;
- (void)onCancelShareVideoToFriend;
- (void)onShareVideoToFriend:(CBaseContact *)aCBaseContact;
- (void)onClickFavVideoMenu;
- (void)willAnimateRotation:(BOOL)animated;
- (void)onClosePlayerForViewDetail:(NSString *)arg1;
- (BOOL)stopAtLastVideoFrameWhenPlayEnd;
- (void)onEndPlayer;
- (void)onPausePlayer;
- (void)onStartPlayer;
@end

